### ISSUE TITLE
Error on parser ( TypeError: Cannot read property 'ban' of undefined )

### ISSUE THREAD

**Issue by DanteSparda3556** [mysqljs/mysql#1445]
```
handshake complete
Logged in!
[SERVER] Trade offer incoming
/var/www/bot/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'ban' of undefined
    at Query._callback (/var/www/bot/sell.js:589:21)
    at Query.Sequence.end (/var/www/bot/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query._handleFinalResultPacket (/var/www/bot/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/var/www/bot/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/var/www/bot/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/bot/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

**Comment by dougwilson** [comment]
Hi @DanteSparda3556, this error is not related to this module, rather you have an error in your file `/var/www/bot/sell.js` on line 589, where you have an undefined variable and are trying to access the `ban` property on it.
