### ISSUE TITLE
Error: logon fail: 85, sessionID: ****** HELP-ME

### ISSUE THREAD

**Issue by DanteSparda3556** [mysqljs/mysql#1450]
```
root@ubuntu-1gb-nyc2-01:/var/www/Bot# node tradebot.js
socket timed out
socket closed
connecting to 146.66.152.13:27019
socket timed out
socket closed
connecting to 146.66.152.14:27018
socket timed out
socket closed
connecting to 72.165.61.175:27018
connected
encrypt request
handshake complete
logon fail: 85, sessionID: ******
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Logon fail: 85
    at SteamClient.handlers.(anonymous function) (/var/www/Bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/var/www/Bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/var/www/Bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/var/www/Bot/node_modules/steam/lib/steam_client.js:106:26)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection._readPacket (/var/www/Bot/node_modules/steam/lib/connection.js:50:8)
    at emitNone (events.js:67:13)
    at Connection.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:419:10)
```

**Comment by DanteSparda3556** [comment]
My node-steam is updated

**Comment by dougwilson** [comment]
Hi @DanteSparda3556, there is not enough context here to help. What leads you to believe this is a bug in this module? Can you provide more details?

**Comment by dougwilson** [comment]
I'm going to close this issue, as this module isn't even in the stack trace you posted.
