### ISSUE TITLE
test-query-dates-as-strings fails 

### ISSUE THREAD

**Issue by powellquiring** [mysqljs/mysql#1458]
ok 15 test/integration/connection/test-query-empty.js
    not ok 16 test/integration/connection/test-query-dates-as-strings.js
      /vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Parser.js:78
              throw err; // Rethrow non-MySQL errors
              ^
    
      Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '0000-00-00' for column 'dt' at row 1
          at Query.Sequence._packetToError (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/sequences/Sequence.js:51:14)
          at Query.ErrorPacket (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/sequences/Query.js:83:18)
          at Protocol._parsePacket (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Protocol.js:280:23)
          at Parser.write (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Parser.js:74:12)
          at Protocol.write (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Protocol.js:39:16)
          at Socket.<anonymous> (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/Connection.js:109:28)
          at emitOne (events.js:77:13)
          at Socket.emit (events.js:169:7)
          at readableAddChunk (_stream_readable.js:153:18)
          at Socket.Readable.push (_stream_readable.js:111:10)
          --------------------
          at Protocol._enqueue (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Protocol.js:141:48)
          at Connection.query (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/Connection.js:214:25)
          at /vagrant/git/github.ibm.com/cc109-sql/mysql/test/integration/connection/test-query-dates-as-strings.js:20:14
          at Handshake._callback (/vagrant/git/github.ibm.com/cc109-sql/mysql/test/common.js:117:5)
          at Handshake.Sequence.end (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/sequences/Sequence.js:85:24)
          at Handshake.Sequence.OkPacket (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/sequences/Sequence.js:94:8)
          at Protocol._parsePacket (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Protocol.js:280:23)
          at Parser.write (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Parser.js:74:12)
          at Protocol.write (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/protocol/Protocol.js:39:16)
          at Socket.<anonymous> (/vagrant/git/github.ibm.com/cc109-sql/mysql/lib/Connection.js:109:28)
    
    ok 17 test/integration/connection/test-query-escaping.js
    
    vagrant@ubuntu-14:/vagrant/git/github.ibm.com/cc109-sql/mysql$ npm version
    { mysql: '2.11.1',
      npm: '2.15.5',
      ares: '1.10.1-DEV',
      http_parser: '2.5.2',
      icu: '56.1',
      modules: '46',
      node: '4.4.6',
      openssl: '1.0.2h',
      uv: '1.8.0',
      v8: '4.5.103.36',
      zlib: '1.2.8' }
    
    docker run -d -p 3306:3306 -d --name mysql -e MYSQL_ROOT_PASSWORD=rootpassword mysql
    
    export MYSQL_HOST="localhost"
    MYSQL_PORT=3306 MYSQL_DATABASE=node_mysql_test MYSQL_USER=root MYSQL_PASSWORD=rootpassword FILTER=integration npm test

**Comment by dougwilson** [comment]
Hi @powellquiring, it sounds like your server is set to a sql mode that does not allow zero dates. Can you post what your `sql_mode` is set to during the tests?

**Comment by scottaj** [comment]
I'm having the same issue when I run the tests locally. My `sql_mode` is `ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

The above set of modes seems to be the default for a fresh install of MySQL 5.7.13.

Any advice on the best way to fix this? I can just turn off `NO_ZERO_IN_DATE` obviously, but should there be a documentation update about that since it is a default? Or should the test turn that mode off? or should the test be rethought somehow?
