### ISSUE TITLE
can save string which contains special char

### ISSUE THREAD

**Issue by ouonet** [mysqljs/mysql#1504]
use node-mysql to save a special string , 
e.g.  this is a special string  :  hello 󰄫 world , contains special chars: 󰄫.
after insert into database , only "hello " is saved ,"󰄫 world" is missing.
how can I save such strings ?

**Comment by sidorares** [comment]
Is it this symbol? http://www.fileformat.info/info/unicode/char/f012b/index.htm

It's 4 bytes in utf8 and default `utf8_unicode_ci` cannot handle it ( utf8 in mysql is actually [cesu-8](https://en.wikipedia.org/wiki/CESU-8)

Can you try to connect with charset set to be `UTF8MB4_GENERAL_CI` ?

**Comment by octachrome** [comment]
@ouonet @sidorares I ran into the same issue. I fixed it by:

1. Setting the `charset` connect option to `UTF8MB4_GENERAL_CI`, as suggested above.
2. Creating the MySQL tables with `DEFAULT CHARSET=utf8mb4`, e.g.:

    CREATE TABLE testing (name VARCHAR(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

It seems that if your tables use `DEFAULT CHARSET=utf8` there is no way you can ever get 4-byte characters inserted into them correctly.

I did notice that the Java MySQL connector rejects 4-byte characters with an error if the table does not support them. It would be nice if the Node driver did the same:

    java.sql.SQLException: Incorrect string value: '\xF0\x9F\x91\x8C' for column 'name' at row 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
        at com.mysql.jdbc.jdbc2.optional.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:875)

**Comment by sidorares** [comment]
@octachrome there are plans for better encodings support (and error reporting)

> It seems that if your tables use DEFAULT CHARSET=utf8 there is no way you can ever get 4-byte characters inserted into them correctly.

Just discovered 2 days ago thanks to @dougwilson that this is actually possible if character is encoded with cesu-8 , see some discussion at https://github.com/sidorares/node-mysql2/pull/374

**Comment by dougwilson** [comment]
In addition, @octachrome that error string from Java you are showing is actually coming from the MySQL server, not something that Java module or this one implemented. You can get the same error with this module if you set the mode your server is running in to error when the server truncates a string instead of just inserting the truncated version.

Setting your sql mdoe in your server to `STRICT_ALL_TABLES` is what will produce that error message, and this module would in turn report the error just the same as the Java driver did.
