### ISSUE TITLE
Connect to mysql server without database name - how to ?

### ISSUE THREAD

**Issue by o1lab** [mysqljs/mysql#1541]
I want to connect to mysql without specifying database in below example.

Then I have a sql script which I load in my application which does: create database (create tables, index, triggers etc..)

How to do this ?

```
var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'me',
  password : 'secret',
  database : 'my_db'
});
 
connection.connect();
```

**Comment by dougwilson** [comment]
Hi @o1lab you would just not include the `database` key pair in the object. For example:
```js
var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'me',
  password : 'secret'
});
```

**Comment by o1lab** [comment]
Oops, I am able to connect but with minor other changes in sql script as below. Thank you @dougwilson 

create my_database - good
use my_database - good.

create table () - **show tables - ERROR Error: ER_NO_DB_ERROR: No database selected**
create my_database.table () - good

**show tables - ERROR Error: ER_NO_DB_ERROR: No database selected**
show tables in my_database - good

Is there a way I could avoid using database name in create table ?

**Comment by dougwilson** [comment]
Hi @o1lab , after you create the database, you can issue the `USE` SQL command (https://dev.mysql.com/doc/refman/5.7/en/use.html) to switch to the new database:
```js
connection.query('USE my_database');
```

**Comment by o1lab** [comment]
Im using USE statement - please see sequence of statements above.

**Comment by dougwilson** [comment]
Sorry, I didn't see that initially. I wrote code to do what you are describing and it worked fine after the USE I did not have to write out the table name.

Is is possible you can share the full code you are using that is not working, perhaps?

**Comment by o1lab** [comment]
Sorry - this can be closed. My mistake.
The problem was in my REPL kind of setup I have with this package : where I type in a query to get results. Since I was creating a connection each time to mysql - I had to provide USE before other statements.

**Comment by mikeynova** [comment]
I'm having the same issue. I'm getting the same error as o1lab

```javascript
var mysql = require('mysql');
var db = 'newMusic';

var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'password'
});

var table = ('CREATE TABLE IF NOT EXISTS Artist (id INT(100) NOT NULL AUTO_INCREMENT, name TINYTEXT, PRIMARY KEY(id))');

connection.connect(function(err) {
	if (err) {
		connection.query('CREATE DATABASE ' + db + 'IF NOT EXISTS', function(err) {
				if (err) {
					console.log('ignoring error');
				}
		connection.query('USE ' + db);
		})
	connection.end();
	}
	connection.connect(function(err) {
		connection.query(table, function(err) {
			if (err) {
				console.log('error in creating tables', err)
			}
		})
	})
})

module.exports = connection;
```

and this is the error that i'm getting in my terminal

```
error in creating tables { Error: ER_NO_DB_ERROR: No database selected
[1]     at Query.Sequence._packetToError (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
[1]     at Query.ErrorPacket (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
[1]     at Protocol._parsePacket (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:280:23)
[1]     at Parser.write (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Parser.js:74:12)
[1]     at Protocol.write (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:39:16)
[1]     at Socket.<anonymous> (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/Connection.js:109:28)
[1]     at emitOne (events.js:96:13)
[1]     at Socket.emit (events.js:188:7)
[1]     at readableAddChunk (_stream_readable.js:176:18)
[1]     at Socket.Readable.push (_stream_readable.js:134:10)
[1]     --------------------
[1]     at Protocol._enqueue (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:141:48)
[1]     at Connection.query (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/Connection.js:214:25)
[1]     at Handshake._callback (/Users/michaelterranova/Desktop/wordOfMouth/server/db/dbConfig.js:23:14)
[1]     at Handshake.Sequence.end (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
[1]     at /Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:226:14
[1]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[1]     at process._tickCallback (internal/process/next_tick.js:98:9)
[1]   code: 'ER_NO_DB_ERROR',
[1]   errno: 1046,
[1]   sqlState: '3D000',
[1]   index: 0 }
```
