### ISSUE TITLE
Unable to get json field 

### ISSUE THREAD

**Issue by siddVotw** [mysqljs/mysql#1565]
My database schema has a json data type but when I am running my select query, my query is erroring out and if i comment only the json data type column I am able to get my data.

**Comment by siddVotw** [comment]
also I am using connection pooling and I have tried the code snippet 
```
typeCast: function(field, next) {
        if (field.type == 'JSON') {
            return (JSON.parse(field.string()));
        }
        return next();
    }

``` 
but this does not work for me :(

**Comment by dougwilson** [comment]
Hi @siddVotw , I was able to use your example without issue. Can you please provide the following information?

1. The version of node.js you are using
2. The version of this module you are using.
3. The error + stack trace you are getting
4. The DDL needed to setup a table to reproduce the issue
5. A complete program that reproduces the issue so I can copy and paste it and run it to debug.

Thanks!

**Comment by siddVotw** [comment]
Hi @dougwilson I am using
1. nodejs version v6.9.1
2. mysql version 2.12.0
3. error stack is 

```
Error: ER_UNKNOWN_TABLE: Unknown table 'servicemaster' in field list
    at Query.Sequence._packetToError (C:\Siddharth\1.SublimeWorkspace\votw-ref\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (C:\Siddharth\1.SublimeWorkspace\votw-ref\node_modules\mysql\lib\protocol\sequences\Query.js:83:18)
    at Protocol._parsePacket (C:\Siddharth\1.SublimeWorkspace\votw-ref\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Siddharth\1.SublimeWorkspace\votw-ref\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (C:\Siddharth\1.SublimeWorkspace\votw-ref\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Siddharth\1.SublimeWorkspace\votw-ref\node_modules\mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread [as _obOriginalOnread] (net.js:548:20)
    at TCP.instrumented [as onread] (C:\Siddharth\1.Su
```
The same query works if I comment out the json column from the select query

4. The ddl is 
   ```
 CREATE TABLE IF NOT EXISTS `testTable` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `someId` INT(11) UNSIGNED NOT NULL,
  `jsonField` json DEFAULT NULL,
  PRIMARY KEY (`id`)
ENGINE = INNODB
DEFAULT CHARACTER SET = utf8;
```

**Comment by o1lab** [comment]
**ER_UNKNOWN_TABLE**: Unknown table 'testTable2'
There is a typo while specifying table name. testTable != testTable2

**Comment by dougwilson** [comment]
Yea, that error has nothing to do with JSON being used.  Can you provide

1. The DDL needed to setup all the tables needed to reproduce the issue
2. A complete program that reproduces the issue so I can copy and paste it and run it to debug.

Without something to debug, I'm not sure how well I can track down your issue.

**Comment by dougwilson** [comment]
I'm going to close this since I haven't heard back.
