### ISSUE TITLE
MySQL library error. PLEASE HELP ME FAST!!!

### ISSUE THREAD

**Issue by aIgor100** [mysqljs/mysql#1593]
Hello.
Im' getting this error:
```
C:\project\node_modules\mysql\lib\protocol\Parser.js:82
        throw err;
        ^

TypeError: Cannot read property 'value' of undefined
    at Query._callback (C:\project\bot.js:574:23)
    at Query.Sequence.end (C:\project\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\project\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\project\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\project\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\project\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\project\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\project\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by ifsnow** [comment]
@aIgor100 

Could you show me what your query and parameters are?
I'm afraid it's hard to find out a clue with your error messages alone.

**Comment by aIgor100** [comment]
Ok. It's it:
`
var maxprice=0;
									mysqlConnection.query('SELECT `value` FROM `info` WHERE `name`=\'maxprice\'', function(err, row, fields) {
									maxbet=row[0].value;
									
									if(sum > row[0].value) { 
										num = 0;
										offers.declineOffer({tradeOfferId: offer.tradeofferid});
										mysqlConnection.query('INSERT INTO `messages` (`userid`,`msg`,`from`, `win`, `system`, `time`) VALUES (\''+offer.steamid_other+'\',\'Value is too high.\',\'System\', \'0\', \'1\', \''+unixtime+'\')', function(err, row, fields) {});
										console.log('[SERVER] Declined offer #'+offer.tradeofferid+' - Sent by: '+offer.steamid_other+' - Reason: Exceeds the maximum skin value');
										
										return;
									}
								});
`

**Comment by dougwilson** [comment]
Since the error is `TypeError: Cannot read property 'value' of undefined` and your code has `maxbet=row[0].value` as the first statement within the callback, it would mean that the error is happening because your `SELECT` query is returning zero rows, thus `rows[0]` is `undefined`, as `rows.length === 0`.
