### ISSUE TITLE
Connect to mysql server without database name - how to ?

### ISSUE THREAD

**Issue by mikeynova** [mysqljs/mysql#1594]
I'm having a very similar issue to #1541 

I'm getting the same error that was referenced in that ticket. 

i.e **ERROR Error: ER_NO_DB_ERROR: No database selected** even after I use USE on my newly created db.

Here is my code and the error I'm receiving below. 
```javascript
var mysql = require('mysql');
var db = 'newMusic';

var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'password'
});

var table = ('CREATE TABLE IF NOT EXISTS Artist (id INT(100) NOT NULL AUTO_INCREMENT, name TINYTEXT, PRIMARY KEY(id))');

connection.connect(function(err) {
	if (err) {
		connection.query('CREATE DATABASE ' + db + 'IF NOT EXISTS', function(err) {
				if (err) {
					console.log('ignoring error');
				}
		connection.query('USE ' + db);
		})
	connection.end();
	}
	connection.connect(function(err) {
		connection.query(table, function(err) {
			if (err) {
				console.log('error in creating tables', err)
			}
		})
	})
})

module.exports = connection;
```

and this is the error that i'm getting in my terminal

```
error in creating tables { Error: ER_NO_DB_ERROR: No database selected
[1]     at Query.Sequence._packetToError (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
[1]     at Query.ErrorPacket (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
[1]     at Protocol._parsePacket (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:280:23)
[1]     at Parser.write (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Parser.js:74:12)
[1]     at Protocol.write (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:39:16)
[1]     at Socket.<anonymous> (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/Connection.js:109:28)
[1]     at emitOne (events.js:96:13)
[1]     at Socket.emit (events.js:188:7)
[1]     at readableAddChunk (_stream_readable.js:176:18)
[1]     at Socket.Readable.push (_stream_readable.js:134:10)
[1]     --------------------
[1]     at Protocol._enqueue (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:141:48)
[1]     at Connection.query (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/Connection.js:214:25)
[1]     at Handshake._callback (/Users/michaelterranova/Desktop/wordOfMouth/server/db/dbConfig.js:23:14)
[1]     at Handshake.Sequence.end (/Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
[1]     at /Users/michaelterranova/Desktop/wordOfMouth/node_modules/mysql/lib/protocol/Protocol.js:226:14
[1]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[1]     at process._tickCallback (internal/process/next_tick.js:98:9)
[1]   code: 'ER_NO_DB_ERROR',
[1]   errno: 1046,
[1]   sqlState: '3D000',
[1]   index: 0 }
```
Any idea what my issue is?

**Comment by ifsnow** [comment]
@mikeynova 

I think this might be what you want.
You can change the database at any time using `changeUser` function.

```js
var mysql = require('mysql');
var db = 'newMusic';

var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'password'
});

var table = ('CREATE TABLE IF NOT EXISTS Artist (id INT(100) NOT NULL AUTO_INCREMENT, name TINYTEXT, PRIMARY KEY(id))');

connection.query('CREATE DATABASE IF NOT EXISTS ??', db, function(err, results) {
  if (err) {
    console.log('error in creating database', err);
    return;
  }

  console.log('created a new database');

  connection.changeUser({
    database : db
  }, function(err) {
    if (err) {
      console.log('error in changing database', err);
      return;
    }

    connection.query(table, function(err) {
      if (err) {
        console.log('error in creating tables', err);
        return;
      }

      console.log('created a new table');
    });
  });
});

module.exports = connection;
```

**Comment by mikeynova** [comment]
Thank you so much @ifsnow; this worked!

I am curious though.  What is the difference between ```'CREATE DATABASE IF NOT EXISTS ??'``` and ```'CREATE DATABASE IF NOT EXISTS'``` What are the ??'s for?

**Comment by ifsnow** [comment]
@mikeynova 

The manual is as follows.

***

you can use ?? characters as placeholders for identifiers you would like to have escaped like this:

```js
var userId = 1;
var columns = ['username', 'email'];
var query = connection.query('SELECT ?? FROM ?? WHERE id = ?', [columns, 'users', userId], function(err, results) {
  // ...
});

console.log(query.sql); // SELECT `username`, `email` FROM `users` WHERE id = 1
```
