### ISSUE TITLE
Error: read ETIMEDOUT while streaming large SELECT *

### ISSUE THREAD

**Issue by Whipgit** [mysqljs/mysql#1605]
Does this error ring any bell for you guys?

I get this error while streaming in a SELECT * of 1.8 million rows.
I don't have a memory leak.

I get it at 4% or at 40% or at 80%... it varies.

```
{ Error: read ETIMEDOUT
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
    --------------------
    at Protocol._enqueue (/opt/repos/driver/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/opt/repos/driver/node_modules/mysql/lib/Connection.js:214:25)
    at Promise (/opt/repos/driver/cli/migrateToMongo.js:63:31)
    at Promise._execute (/opt/repos/driver/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/opt/repos/driver/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/opt/repos/driver/node_modules/bluebird/js/release/promise.js:77:14)
    at transferData (/opt/repos/driver/cli/migrateToMongo.js:58:10)
    at tryCatcher (/opt/repos/driver/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/repos/driver/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/repos/driver/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/repos/driver/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/repos/driver/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/opt/repos/driver/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/repos/driver/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/opt/repos/driver/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'read',
  fatal: true }
```

**Comment by Whipgit** [comment]
My way around it is to select the total first. and use a counter in the stream.
The select * has become a 'select * from .. limit currentRecord, totalRecords'

If the error occurs I reselect and resume the stream from the totalRecords.

**Comment by dougwilson** [comment]
Hi @Whipgit is there anyway you can put together a program and instructions for how we can reproduce the issue?

**Comment by Whipgit** [comment]
Sorry for the late reply. My current workload does not allow me much time to do this @dougwilson I will try and do that when the time becomes available.
