### ISSUE TITLE
SSL - Cannot connect to remote database : ssl3_check_cert_and_algorithm:dh key too small

### ISSUE THREAD

**Issue by BkSouX** [mysqljs/mysql#1615]
Hi,

I have an issue trying to connect to a remote database with SSL.
It's working with CLI and MySql Workbench but I have that error with node : 

Here is the command that actually works : 

```
mysql --host=xxxxx --port=xxxx --user=xxxxx --ssl-ca=ca.crt --ssl-cert=cert.crt --ssl-key=clientkey.pem --database=xxxx
```

Here is the JS code

```
var connection = mysql.createConnection({
    host: 'xxxx,
    port: 'xxxx',
    user: 'xxxx',
    database: 'xxxx',
    ssl: {
        ca: fs.readFileSync(__dirname + '/ca.crt'),
        key: fs.readFileSync(__dirname + '/clientkey.pem'),
        cert: fs.readFileSync(__dirname + '/cert.crt')
    }
});
```

I cannot see a difference between the two configurations but I have an error with the node mysql driver.

Here is the full error : 

```
error connecting: Error: 139850844571456:error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small:../deps/openssl/openssl/ssl/s3_clnt.c:3613:

    at Error (native)
    --------------------
    at Protocol._enqueue (/home/bsousa/Projects/sarbacane-auto-js/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/bsousa/Projects/sarbacane-auto-js/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/home/bsousa/Projects/sarbacane-auto-js/node_modules/mysql/lib/Connection.js:136:18)
    at Object.<anonymous> (/home/bsousa/Projects/sarbacane-auto-js/index.js:16:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

Am I doing something wrong or is that a bug ?

Thank you :)

**Comment by dougwilson** [comment]
Node,js made a change that makes anything Node.js no longer connect to servers that have a DH key that is too short.

**Comment by Checkson** [comment]
Execuse me, is there any other solution to the above problems?
