### ISSUE TITLE
Handshake inactivity timeout on trying pooled connection

### ISSUE THREAD

**Issue by soletan** [mysqljs/mysql#1616]
Hi, I'm trying to use `mysql` to connect to some remote MySQL RDBMS. This works with non-pooled connections (though taking a remarkable time of several seconds to actually establish connection to some local VM), but fails when using pooled connections.

Here is my test script:

```javascript
const db = require( "mysql" );
const _  = require( "lodash" );

const config = {
	adapter: "mysql",
	user: "importer",
	password: "importer",
	host: "192.168.200.89",
	database: "jjw_15",
	debug: true
};


console.log( "connecting..." );

/* enable this for non-pooled connection
let connection = db.createConnection( config );
connection.connect( function( err ) {
	onConnected( err, connection );
} );
*/

/* enable this for pooled connection
let pool = db.createPool( config );
pool.getConnection( onConnected );
*/


function onConnected( err, link ) {
	if ( err ) {
		console.error( "connection failed", err );
		return;
	}

	console.log( "connection established" );

	link.query( "SELECT COUNT(*) FROM country", function( err, rows, fields ) {
		if ( err ) {
			console.error( "query failed", err );
			return;
		}

		console.dir( rows );
	} );

	link.end();
}
```

Here is stdout when running with non-pooled connection:

```
connecting...
<-- HandshakeInitializationPacket
HandshakeInitializationPacket {
  protocolVersion: 10,
  serverVersion: '5.7.16-0ubuntu0.16.04.1',
  threadId: 51,
  scrambleBuff1: <Buffer 7f 48 5b 37 79 3e 2b 57>,
  filler1: <Buffer 00>,
  serverCapabilities1: 63487,
  serverLanguage: 8,
  serverStatus: 2,
  serverCapabilities2: 33279,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 00 00 00 00>,
  scrambleBuff2: <Buffer 4e 6e 08 3c 36 3c 02 79 68 3c 39 2b>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password',
  protocol41: true }

--> ClientAuthenticationPacket
ClientAuthenticationPacket {
  clientFlags: 455631,
  maxPacketSize: 0,
  charsetNumber: 33,
  filler: undefined,
  user: 'importer',
  scrambleBuff: <Buffer fe 60 ef 3e b0 4a 6c 4a 2a 25 eb 1d cb 44 e2 e1 d2 2e 24 5b>,
  database: 'jjw_15',
  protocol41: true }

<-- OkPacket
OkPacket {
  fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }

connection established
--> ComQueryPacket
ComQueryPacket { command: 3, sql: 'SELECT COUNT(*) FROM country' }

<-- ResultSetHeaderPacket
ResultSetHeaderPacket { fieldCount: 1, extra: undefined }

<-- FieldPacket
FieldPacket {
  catalog: 'def',
  db: '',
  table: '',
  orgTable: '',
  name: 'COUNT(*)',
  orgName: '',
  charsetNr: 63,
  length: 21,
  type: 8,
  flags: 129,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- EofPacket
EofPacket {
  fieldCount: 254,
  warningCount: 0,
  serverStatus: 2,
  protocol41: true }

<-- RowDataPacket
RowDataPacket { 'COUNT(*)': 25 }

<-- EofPacket
EofPacket {
  fieldCount: 254,
  warningCount: 0,
  serverStatus: 2,
  protocol41: true }

[ RowDataPacket { 'COUNT(*)': 25 } ]
--> ComQuitPacket
ComQuitPacket { command: 1 }

```

_(After printing **connecting ...** it takes about 13s until rest of output is generated.)_

And this output is generated on trying pooled connection:

```
connecting...
connection failed { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (C:\Users\cepharum\PhpstormProjects\jjw-importer\node_modules\mysql\lib\protocol\Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:185:7)
    at Handshake._onTimeout (C:\Users\cepharum\PhpstormProjects\jjw-importer\node_modules\mysql\lib\protocol\sequences\Sequence.js:127:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (C:\Users\cepharum\PhpstormProjects\jjw-importer\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (C:\Users\cepharum\PhpstormProjects\jjw-importer\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (C:\Users\cepharum\PhpstormProjects\jjw-importer\node_modules\mysql\lib\Connection.js:136:18)
    at Pool.getConnection (C:\Users\cepharum\PhpstormProjects\jjw-importer\node_modules\mysql\lib\Pool.js:48:16)
    at Object.<anonymous> (C:\Users\cepharum\PhpstormProjects\jjw-importer\dbtest.js:52:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
```

See my `npm version`:

```
{ 'dbtest': '0.0.1',
  npm: '3.10.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.2',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.88',
  zlib: '1.2.8' }
```

Test was run using mysql v2.12.0.

Tested system in Win10 x64 ... but I think this shouldn't matter here.

**Comment by dougwilson** [comment]
Depending on how your code works without using the pool, you are probably not giving the connect a timeout, while the pool does by default. You can always increase the `acquireTimeout` option to something higher. Without a network packet capture, it's hard to say why connecting takes so long for you.

**Comment by soletan** [comment]
Basically, there wasn't any more code to what was given above. 

But thanks for the hint on network capture. This way I found out that there is no traffic to be captured on behalf of server as well. Finally it turned out to be a firewall issue: it was permitting TCP on 3306, only. By additionally permitting UDP everything was working instantly and as expected ... sorry for bothering you.

**Comment by dougwilson** [comment]
Oh, sorry, I didn't really look at that commented-out code above :) This missing code I was referring to you had in a comment, haha, the `connection.connect( function( err ) {` part. That doesn't specify a timeout, which is what the difference between when you used the non-pooled vs the pooled (which internally calls `connection.connect` but with a timeout value).

Glad you got it figured out!
