### ISSUE TITLE
ER_PARSE_ERROR : print the sql when this error throws 

### ISSUE THREAD

**Issue by magicdawn** [mysqljs/mysql#1628]
I met this error this morning

```
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'undefined' at li
ne 17
    at Query.Sequence._packetToError (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
    --------------------
    at Protocol._enqueue (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at __QUERY__ (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/lib/adapter.js:106:25)
    at afterwards (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/lib/connections/spawn.js:84:5)
    at /export/content/pushmanager-20170119T1527/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Ping.onOperationComplete [as _callback] (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:99:5)
    at Ping.Sequence.end (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/export/content/pushmanager-20170119T1527/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
```

basicly I'm blind to this error, hard for trouble shooting.
I figured out to add some code in `Connection.prototype.query`, but that prints too much sql. With sql attached with the error stack will be nice!

**Comment by dougwilson** [comment]
Hi @magicdawn currently that error is the exact text your MySQL server sends back to this module. There is a PR #1462 to add this that has not responded to feedback. If you could help move it along, that would be great!

**Comment by magicdawn** [comment]
I'm just throwing the problem.
