### ISSUE TITLE
Create database when ER_BAD_DB_ERROR?

### ISSUE THREAD

**Issue by Bizarrus** [mysqljs/mysql#1658]
Hey :)

I've tried to create a database, if `ER_BAD_DB_ERROR` is present on `error`.

    _connection.query(statement, parameters, function(error, results, fields) {
        // Handle errors for the actual query
	switch(error.code) {
		case 'PROTOCOL_CONNECTION_LOST':
		case 'ECONNREFUSED':
			alert('[MySQL] ' + error.message);				
		break;

               // CREATE Database, when error appears
		case 'ER_BAD_DB_ERROR':
			console.log('Create database ' + Config.get('database.database'));
					
                        // Create...
			_instance.query('CREATE DATABASE :name', {
				name:	Config.get('database.database')
			}, function(error, results, fields) {
				console.log(error);

                                // Try the old Query
				_instance.query(statement, parameters, callback);
			});
		break;
	}
			
	callback(error, results, fields);
    });

But, i've get a `Cannot enqueue Query after fatal error.` error:

```
Error: ER_BAD_DB_ERROR: Unknown database 'ossm'
    at Handshake.Sequence._packetToError (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Handshake.ErrorPacket (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\sequences\Handshake.js:103:18)
    at Protocol._parsePacket (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at Connection.connect (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\Connection.js:130:18)
MySQL.js:50 Create database ossm
MySQL.js:55 Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:199:16)
    at Protocol._enqueue (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:135:13)
    at Connection.query (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\Connection.js:208:25)
    at Query.Sequence.end (C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:399:18
    at Array.forEach (native)
    at C:\Users\Bizzi\AppData\Local\Temp\nw28252_25782\node_modules\mysql\lib\protocol\Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

How i can fix this?

**Comment by dougwilson** [comment]
Hi @Bizarrus based on the stack trace, it looks like you're specifying a non-existent database as the `database` option to the connection. If this is the case, then your MySQL server will simply out right deny the connection altogether, meaning you never actually established a database connection to even use to query on.

You can find out more information in our error handling documentation (https://github.com/mysqljs/mysql#error-handling) about how to determine if an error is fatal and what that means.

If you don't think this is the case, can you please provide all the following:

1. The version of Node.js you're using
2. The version of this module you're using
3. Complete code I can run to reproduce the issue (not just a snipplet)
4. Complete instructions on how to run your code to reproduce the issue.

**Comment by dougwilson** [comment]
Hi @Bizarrus I'm going to close this since I haven't heard anything back.
