### ISSUE TITLE
ECONNRESET when after call end()

### ISSUE THREAD

**Issue by justinjzs** [mysqljs/mysql#1662]
I use mysql in PassportJS. 
ervery time I login, the ERROR ECONNRESET occur
```javascript
const client = () => mysql.createConnection(config);
let LocalStrategy = require('passport-local').Strategy
passport.use(new LocalStrategy(function(username, password, done) {
  let dbclient = client();
  const hash = crypto.createHash('sha1');
  hash.update(password);
  const values = [username, hash.digest('hex')];
  dbclient.connect();
  dbclient.query(`select u_id from users where u_name = ? and u_pwd = ?`,
    values,
    (err, result) => {
      if (err) {console.log(err); return done(err);}
      const user = result[0]; //{ key: [Number] } or undefined
      if(user)  
        done(null, user); //success
      else
        done(null ,false);  //failure    
    });
    dbclient.end();
}))
```

the error detail is:
(/home/bae/app/controller/auth.js:38:12) is the query line in before code
```javascript
#Error: read ECONNRESET
# at exports._errnoException (util.js:870:11)
# at TCP.onread (net.js:552:26)
#---------------------------------------------
# at Socket.Readable.on (_stream_readable.js:673:33)
# at Connection.connect (/home/bae/app/.bae/node_modules/mysql/lib/Connection.js:112:18)
# at Strategy._verify (/home/bae/app/controller/auth.js:38:12)
# at Strategy.authenticate (/home/bae/app/.bae/node_modules/passport-local/lib/strategy.js:90:12)
# at attempt (/home/bae/app/.bae/node_modules/koa-passport/node_modules/passport/lib/middleware/authenticate.js:348:16)
# at authenticate (/home/bae/app/.bae/node_modules/koa-passport/node_modules/passport/lib/middleware/authenticate.js:349:7)
# at Object.cont (/home/bae/app/.bae/node_modules/koa-passport/lib/framework/koa.js:132:7)
# at /home/bae/app/.bae/node_modules/co/index.js:136:8
# at new Promise (/home/bae/app/.bae/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
# at Object.thunkToPromise (/home/bae/app/.bae/node_modules/co/index.js:135:10)
# at Object.toPromise (/home/bae/app/.bae/node_modules/co/index.js:119:55)
# at next (/home/bae/app/.bae/node_modules/co/index.js:99:29)
# at onFulfilled (/home/bae/app/.bae/node_modules/co/index.js:69:7)
# at /home/bae/app/.bae/node_modules/co/index.js:54:5
# at new Promise (/home/bae/app/.bae/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
```

**Comment by dougwilson** [comment]
The error is coming from Node.js core and it's happening on the connect, so seems like perhaps you have a network firewall blocking?

**Comment by justinjzs** [comment]
@dougwilson  
no, there is no network firewall.
I try  remove the `dbclient.end()` , and 30s after `createConnection()` the mysql server turn down the connection, and the same ERROR occur, even the error details are the same as before
The query results returned by mysql are handled by callback correctly,  but the client seems keep reading the socket even the callback fun end, so when  `dbclient.end()` end the connection, the client still try to read the socket so that the ERROR occur.

**Comment by dougwilson** [comment]
Hm. Weird. I can certainly take a look, but need some help to get the issue reproducible if you're not able to come up with a patch.

**Comment by dougwilson** [comment]
Gotcha. Also, from taking another look at your code, I think the following change from new connections to a pool will improve your performance and take care of that type of error automatically for you:
```js
const pool = mysql.createPool(config);
let LocalStrategy = require('passport-local').Strategy
passport.use(new LocalStrategy(function(username, password, done) {
  const hash = crypto.createHash('sha1');
  hash.update(password);
  const values = [username, hash.digest('hex')];
  pool.query(`select u_id from users where u_name = ? and u_pwd = ?`,
    values,
    (err, result) => {
      if (err) {console.log(err); return done(err);}
      const user = result[0]; //{ key: [Number] } or undefined
      if(user)  
        done(null, user); //success
      else
        done(null ,false);  //failure    
    });
}))
```
