### ISSUE TITLE
Connection error to MySQL server on Windows Bash

### ISSUE THREAD

**Issue by rafaelubal** [mysqljs/mysql#1672]
I'm not sure if this is an issue with Windows Bash, with NodeJS, or with node-mysql. When trying to connect to the database, this error shows up:

```
Error: connect Unknown system errno -1
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
    --------------------
    at Protocol._enqueue (/home/ubal/topoftrees/server/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/home/ubal/topoftrees/server/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/ubal/topoftrees/server/node_modules/mysql/lib/Connection.js:109:18)
    at Pool.getConnection (/home/ubal/topoftrees/server/node_modules/mysql/lib/Pool.js:45:23)
    at Pool.query (/home/ubal/topoftrees/server/node_modules/mysql/lib/Pool.js:183:8)
    at Function.DB.query (/home/ubal/topoftrees/server/lib/db.js:642:23)
    at /home/ubal/topoftrees/server/node_modules/promise/lib/node-extensions.js:25:10
    at doResolve (/home/ubal/topoftrees/server/node_modules/promise/lib/core.js:91:5)
    at new Promise (/home/ubal/topoftrees/server/node_modules/promise/lib/core.js:71:3)
    at Function.pQuery (/home/ubal/topoftrees/server/node_modules/promise/lib/node-extensions.js:17:12)
```

**Comment by dougwilson** [comment]
Weird, I have never encountered such an error before. Even searching on Google only just brings up your SO post :) What I can say is that that error is coming from the Node.js core code, most likely coming directly from the underlying libuv. The Node.js core folks may be the only ones who would know where to start on diagnosing this.

**Comment by dougwilson** [comment]
Basically the error is when we call the [Node.js core `net.createConnection` function](https://nodejs.org/dist/latest-v6.x/docs/api/net.html#net_net_createconnection_options_connectlistener) at https://github.com/mysqljs/mysql/blob/master/lib/Connection.js#L91 , Node.js then emits the error "connect Unknown system errno -1" as the error event on the socket object, which results in us passing it back to your code.

**Comment by rafaelubal** [comment]
Thank you for the quick reply! I'll post this on the Node.js core project then.
