### ISSUE TITLE
Issues with connecting

### ISSUE THREAD

**Issue by Killer-Bunny** [mysqljs/mysql#1689]
Hi,
I've installed your library in my project via console, but it doesn't work properly.
here's the code:
```js
var mysql = require('mysql');

var connection = mysql.createConnection({
   host: 'localhost',
    user: 'root',
    password: '1234',
    port: '8100',
    database: 'sys'

});

connection.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
    if (err){
        throw err;
    }

    console.log('The solution is: ', rows[0].solution);
});

connection.end();


```

and this is the error:

```sh
c:\Users\ooly\Documents\HotelReserv\mysql-node\db.js:12
    if (err) throw err;
             ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (c:\Users\ooly\Documents\HotelReserv\mysql-node\node_modules\mysql\lib\protocol\Protocol.js:109:13)
    at Socket.<anonymous> (c:\Users\ooly\Documents\HotelReserv\mysql-node\node_modules\mysql\lib\Connection.js:115:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    --------------------
    at Protocol._enqueue (c:\Users\ooly\Documents\HotelReserv\mysql-node\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (c:\Users\ooly\Documents\HotelReserv\mysql-node\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at Connection.connect (c:\Users\ooly\Documents\HotelReserv\mysql-node\node_modules\mysql\lib\Connection.js:136:18)
    at Connection._implyConnect (c:\Users\ooly\Documents\HotelReserv\mysql-node\node_modules\mysql\lib\Connection.js:467:10)
    at Connection.query (c:\Users\ooly\Documents\HotelReserv\mysql-node\node_modules\mysql\lib\Connection.js:212:8)
    at Object.<anonymous> (c:\Users\ooly\Documents\HotelReserv\mysql-node\db.js:11:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

Process finished with exit code 1
```

Thanks alot:)

**Comment by Killer-Bunny** [comment]
One more thing, I'm using mysql workbench. it is reconizing a connection it just doesn't do nothing (i get no reply not on the console and not on the sql).

**Comment by dresende** [comment]
You must write your code asynchronously.

```js
var mysql = require("mysql");
var db    = mysql.createConnection("mysql://root:1234@localhost:8100/sys");

db.query("SELECT 1 + 1 AS solution", function (err, rows) {
    if (err) throw err;

    console.log('The solution is: ', rows[0].solution);

    return db.end();
});
```

**Comment by Killer-Bunny** [comment]
Hi,
First thing thanks alot.
second, by writing asynchronously you mean the structure that contain a function with a result and error, or should i split all code above in functions with timeouts?

**Comment by Killer-Bunny** [comment]
Nevermind, I managed to deal with it by self.
Thanks,
