### ISSUE TITLE
Trying to insert records to mariadb. Getting success result with serverstatus 3. But could not find the records in database. 

### ISSUE THREAD

**Issue by ramumesh** [mysqljs/mysql#1700]

**Comment by dougwilson** [comment]
Hi @ramumesh a server status of three indicates your query was within a transaction. Did you actually commit the transaction?

Otherwise, there is not enough information to help you here. Can you provide all the following?

1. Version of the MarisDB server.
2. Version of this module.
3. The complete code you're running that reproduces the issue.
4. Any instructions necessary to run.

Thank you!

**Comment by ramumesh** [comment]
Hi @dougwilson . Please find the details. Hope it helps. 
1. Version is 10.1.20-MariaDB
2.  "knex": "^0.12.8",
3. 
```
var client = require('knex');

var dbConfig = {
    host: 'xxx.xxx.xxx.com',
    user: 'root',
    password: 'xxxxxxxxx',
    db: 'xxxxxxxxx'
};

client = require('knex')({
    client: 'mariasql',
    connection: dbConfig,
    pool: {
        acquireTimeout: 10000
    }
});

client.raw('insert into `store_info` (`state_code`, `store_id`) values (\'xx\', \'xxxx\')').asCallback(function(err,data){
    if(err){
         console.log(err);
    }
    console.log(data);
});
```
4. I am trying to insert to maria db hosted in cloud which is in 3 nodes. I am getting the following result after insertion. But the row never  inserted.
```
{
  fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 3,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }
```
When I tried to do the same to my local mysql database . I am getting the following as result and the row inserted successfully. 
```
{
  fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }
```

**Comment by dougwilson** [comment]
Hi @ramumesh , I'm sorry to tell you this, but when you're using Knex and you set `client: 'mariasql'`, you're not actually using this module at all, so there is nothing I can really help with here, sorry!

**Comment by ramumesh** [comment]
I used mysql as the client .. But is is having the same result

**Comment by ramumesh** [comment]
Please dont close this issue..  Its is an actual issue.. .I am trying with both mysql and mariadb.... Still it is not working...

**Comment by dougwilson** [comment]
Hi @ramumesh I would love to help, but I need the following information, then, for your usage of _this module_:

1. Version of the MarisDB server.
2. Version of this module.
3. The complete code you're running that reproduces the issue.
4. Any instructions necessary to run.

**Comment by ramumesh** [comment]
I tried with the following code... 
```var client = require('knex');

var dbConfig = {
    host: 'xxx.xxx.xxx.com',
    user: 'root',
    password: 'xxxxxxxxx',
    db: 'xxxxxxxxx'
};

client = require('knex')({
    client: 'mysql',
    connection: dbConfig,
    pool: {
        acquireTimeout: 10000
    }
});

client.raw('insert into `store_info` (`state_code`, `store_id`) values (\'xx\', \'xxxx\')').asCallback(function(err,data){
    if(err){
         console.log(err);
    }
    console.log(data);
});
```

Still having the same result

**Comment by dougwilson** [comment]
I'm getting an error running that because I don't have a store_info table. Please provide any necessary DDL to create anything needed to run your code to see the issue. Also, I need to know what version of this module you're using as well.

**Comment by ramumesh** [comment]
Mariadb version is 10.1.20-MariaDB
"knex": "^0.12.8",

CREATE TABLE `store_info` (
  `store_id` char(5) NOT NULL,
  `state_code` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by ramumesh** [comment]
I tried with Java with mysql connector. It is working fine . Rows are inserted successfully

**Comment by dougwilson** [comment]
So this isn't the knex module, so the version I need is the one you're using for this module (mysql) not for knex.

**Comment by ramumesh** [comment]
"mysql": "^2.13.0",

**Comment by dougwilson** [comment]
Thanks, @ramumesh . So I ran your code and there is indeed an error! Running it gives me the error `Error: ER_NO_DB_ERROR: No database selected`.

This is because in your `dbConfig`, you are setting the database with an option called `db`, but there is no such option. You need to change that to `database`. Here is the log of my console running your script. If I'm missing something, please provide further detail on what I need to do.

```
$ npm i knex@0.12.8 mysql@2.13.0
/mysql-1700
├─┬ knex@0.12.8 
│ ├─┬ babel-runtime@6.23.0 
│ │ ├── core-js@2.4.1 
│ │ └── regenerator-runtime@0.10.3 
│ ├── bluebird@3.5.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.1.1 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├─┬ commander@2.9.0 
│ │ └── graceful-readlink@1.0.1 
│ ├─┬ debug@2.6.3 
│ │ └── ms@0.7.2 
│ ├── generic-pool@2.5.4 
│ ├── inherits@2.0.3 
│ ├── interpret@0.6.6 
│ ├─┬ liftoff@2.2.5 
│ │ ├── extend@3.0.0 
│ │ ├─┬ findup-sync@0.4.3 
│ │ │ ├─┬ detect-file@0.1.0 
│ │ │ │ └── fs-exists-sync@0.1.0 
│ │ │ ├─┬ is-glob@2.0.1 
│ │ │ │ └── is-extglob@1.0.0 
│ │ │ ├─┬ micromatch@2.3.11 
│ │ │ │ ├─┬ arr-diff@2.0.0 
│ │ │ │ │ └── arr-flatten@1.0.3 
│ │ │ │ ├── array-unique@0.2.1 
│ │ │ │ ├─┬ braces@1.8.5 
│ │ │ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │ │ │   ├── is-number@2.1.0 
│ │ │ │ │ │   ├─┬ isobject@2.1.0 
│ │ │ │ │ │   │ └── isarray@1.0.0 
│ │ │ │ │ │   ├── randomatic@1.1.6 
│ │ │ │ │ │   └── repeat-string@1.6.1 
│ │ │ │ │ ├── preserve@0.2.0 
│ │ │ │ │ └── repeat-element@1.1.2 
│ │ │ │ ├─┬ expand-brackets@0.1.5 
│ │ │ │ │ └── is-posix-bracket@0.1.1 
│ │ │ │ ├── extglob@0.3.2 
│ │ │ │ ├── filename-regex@2.0.0 
│ │ │ │ ├─┬ kind-of@3.1.0 
│ │ │ │ │ └── is-buffer@1.1.5 
│ │ │ │ ├─┬ normalize-path@2.1.1 
│ │ │ │ │ └── remove-trailing-separator@1.0.1 
│ │ │ │ ├─┬ object.omit@2.0.1 
│ │ │ │ │ ├─┬ for-own@0.1.5 
│ │ │ │ │ │ └── for-in@1.0.2 
│ │ │ │ │ └── is-extendable@0.1.1 
│ │ │ │ ├─┬ parse-glob@3.0.4 
│ │ │ │ │ ├─┬ glob-base@0.3.0 
│ │ │ │ │ │ └── glob-parent@2.0.0 
│ │ │ │ │ └── is-dotfile@1.0.2 
│ │ │ │ └─┬ regex-cache@0.4.3 
│ │ │ │   ├── is-equal-shallow@0.1.3 
│ │ │ │   └── is-primitive@2.0.0 
│ │ │ └─┬ resolve-dir@0.1.1 
│ │ │   ├─┬ expand-tilde@1.2.2 
│ │ │   │ └── os-homedir@1.0.2 
│ │ │   └─┬ global-modules@0.2.3 
│ │ │     ├─┬ global-prefix@0.1.5 
│ │ │     │ ├─┬ homedir-polyfill@1.0.1 
│ │ │     │ │ └── parse-passwd@1.0.0 
│ │ │     │ ├── ini@1.3.4 
│ │ │     │ └─┬ which@1.2.14 
│ │ │     │   └── isexe@2.0.0 
│ │ │     └── is-windows@0.2.0 
│ │ ├── flagged-respawn@0.3.2 
│ │ ├── rechoir@0.6.2 
│ │ └─┬ resolve@1.3.2 
│ │   └── path-parse@1.0.5 
│ ├── lodash@4.17.4 
│ ├── minimist@1.1.3 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├── pg-connection-string@0.1.3 
│ ├── safe-buffer@5.0.1 
│ ├─┬ tildify@1.0.0 
│ │ └── user-home@1.1.1 
│ ├── uuid@3.0.1 
│ └── v8flags@2.1.1 
└─┬ mysql@2.13.0 
  ├── bignumber.js@3.1.2 
  ├─┬ readable-stream@1.1.14 
  │ ├── core-util-is@1.0.2 
  │ ├── isarray@0.0.1 
  │ └── string_decoder@0.10.31 
  └── sqlstring@2.2.0 

$ cat test.js 
var client = require('knex');

var dbConfig = {
    host: 'localhost',
    user: 'root',
    password: 'xxxxxxxxx',
    db: 'xxxxxxxxx'
};

client = require('knex')({
    client: 'mysql',
    connection: dbConfig,
    pool: {
        acquireTimeout: 10000
    }
});

client.raw('insert into `store_info` (`state_code`, `store_id`) values (\'xx\', \'xxxx\')').asCallback(function(err,data){
    if(err){
         console.log(err);
    }
    console.log(data);
});

$ docker run -d -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=xxxxxxxxx -e MYSQL_DATABASE=xxxxxxxxx mariadb:10.1.20
Unable to find image 'mariadb:10.1.20' locally
10.1.20: Pulling from library/mariadb
5040bd298390: Already exists 
55370df68315: Already exists 
fad5195d69cc: Already exists 
a1034a5fbbfc: Already exists 
eb46f36a6163: Pull complete 
de7067e4ea0a: Pull complete 
fc40d1291bb9: Pull complete 
1b86d3d50a3d: Pull complete 
c464a422954a: Pull complete 
ca6a2da75737: Pull complete 
79e633b60340: Pull complete 
49a5c52e71de: Pull complete 
Digest: sha256:90b76a6759a33007babd2e74480ad22946d515baeab75a13952feb42faae0653
Status: Downloaded newer image for mariadb:10.1.20
ffd26e2d1e9b580ad99cbb636ce28b557d8ea2568d0a292e87473cf1dedd4213

$ docker exec mysql mysql -pxxxxxxxxx -e 'select version()'
version()
10.1.20-MariaDB-1~jessie

$ node test.js
{ Error: ER_NO_DB_ERROR: No database selected
    at Query.Sequence._packetToError (/mysql-1700/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/mysql-1700/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/mysql-1700/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/mysql-1700/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/mysql-1700/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/mysql-1700/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/mysql-1700/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/mysql-1700/node_modules/mysql/lib/Connection.js:208:25)
    at /mysql-1700/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/mysql-1700/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/mysql-1700/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/mysql-1700/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/mysql-1700/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/mysql-1700/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/mysql-1700/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/mysql-1700/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/mysql-1700/node_modules/bluebird/js/release/method.js:15:34)
    at /mysql-1700/node_modules/knex/lib/runner.js:65:21
    at tryCatcher (/mysql-1700/node_modules/bluebird/js/release/util.js:16:23)
    at /mysql-1700/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/mysql-1700/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mysql-1700/node_modules/bluebird/js/release/promise.js:512:31)
  code: 'ER_NO_DB_ERROR',
  errno: 1046,
  sqlState: '3D000',
  index: 0 }
undefined
```

**Comment by dougwilson** [comment]
And for further reference, here is the result of when I fixed the issue in your code, which you can see I am able to select out the inserted row from the database:
```
$ npm i knex@0.12.8 mysql@2.13.0
/mysql-1700
├─┬ knex@0.12.8 
│ ├─┬ babel-runtime@6.23.0 
│ │ ├── core-js@2.4.1 
│ │ └── regenerator-runtime@0.10.3 
│ ├── bluebird@3.5.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.1.1 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├─┬ commander@2.9.0 
│ │ └── graceful-readlink@1.0.1 
│ ├─┬ debug@2.6.3 
│ │ └── ms@0.7.2 
│ ├── generic-pool@2.5.4 
│ ├── inherits@2.0.3 
│ ├── interpret@0.6.6 
│ ├─┬ liftoff@2.2.5 
│ │ ├── extend@3.0.0 
│ │ ├─┬ findup-sync@0.4.3 
│ │ │ ├─┬ detect-file@0.1.0 
│ │ │ │ └── fs-exists-sync@0.1.0 
│ │ │ ├─┬ is-glob@2.0.1 
│ │ │ │ └── is-extglob@1.0.0 
│ │ │ ├─┬ micromatch@2.3.11 
│ │ │ │ ├─┬ arr-diff@2.0.0 
│ │ │ │ │ └── arr-flatten@1.0.3 
│ │ │ │ ├── array-unique@0.2.1 
│ │ │ │ ├─┬ braces@1.8.5 
│ │ │ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │ │ │   ├── is-number@2.1.0 
│ │ │ │ │ │   ├─┬ isobject@2.1.0 
│ │ │ │ │ │   │ └── isarray@1.0.0 
│ │ │ │ │ │   ├── randomatic@1.1.6 
│ │ │ │ │ │   └── repeat-string@1.6.1 
│ │ │ │ │ ├── preserve@0.2.0 
│ │ │ │ │ └── repeat-element@1.1.2 
│ │ │ │ ├─┬ expand-brackets@0.1.5 
│ │ │ │ │ └── is-posix-bracket@0.1.1 
│ │ │ │ ├── extglob@0.3.2 
│ │ │ │ ├── filename-regex@2.0.0 
│ │ │ │ ├─┬ kind-of@3.1.0 
│ │ │ │ │ └── is-buffer@1.1.5 
│ │ │ │ ├─┬ normalize-path@2.1.1 
│ │ │ │ │ └── remove-trailing-separator@1.0.1 
│ │ │ │ ├─┬ object.omit@2.0.1 
│ │ │ │ │ ├─┬ for-own@0.1.5 
│ │ │ │ │ │ └── for-in@1.0.2 
│ │ │ │ │ └── is-extendable@0.1.1 
│ │ │ │ ├─┬ parse-glob@3.0.4 
│ │ │ │ │ ├─┬ glob-base@0.3.0 
│ │ │ │ │ │ └── glob-parent@2.0.0 
│ │ │ │ │ └── is-dotfile@1.0.2 
│ │ │ │ └─┬ regex-cache@0.4.3 
│ │ │ │   ├── is-equal-shallow@0.1.3 
│ │ │ │   └── is-primitive@2.0.0 
│ │ │ └─┬ resolve-dir@0.1.1 
│ │ │   ├─┬ expand-tilde@1.2.2 
│ │ │   │ └── os-homedir@1.0.2 
│ │ │   └─┬ global-modules@0.2.3 
│ │ │     ├─┬ global-prefix@0.1.5 
│ │ │     │ ├─┬ homedir-polyfill@1.0.1 
│ │ │     │ │ └── parse-passwd@1.0.0 
│ │ │     │ ├── ini@1.3.4 
│ │ │     │ └─┬ which@1.2.14 
│ │ │     │   └── isexe@2.0.0 
│ │ │     └── is-windows@0.2.0 
│ │ ├── flagged-respawn@0.3.2 
│ │ ├── rechoir@0.6.2 
│ │ └─┬ resolve@1.3.2 
│ │   └── path-parse@1.0.5 
│ ├── lodash@4.17.4 
│ ├── minimist@1.1.3 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├── pg-connection-string@0.1.3 
│ ├── safe-buffer@5.0.1 
│ ├─┬ tildify@1.0.0 
│ │ └── user-home@1.1.1 
│ ├── uuid@3.0.1 
│ └── v8flags@2.1.1 
└─┬ mysql@2.13.0 
  ├── bignumber.js@3.1.2 
  ├─┬ readable-stream@1.1.14 
  │ ├── core-util-is@1.0.2 
  │ ├── isarray@0.0.1 
  │ └── string_decoder@0.10.31 
  └── sqlstring@2.2.0 

$ cat test.js 
var client = require('knex');

var dbConfig = {
    host: 'localhost',
    user: 'root',
    password: 'xxxxxxxxx',
    database: 'xxxxxxxxx'
};

client = require('knex')({
    client: 'mysql',
    connection: dbConfig,
    pool: {
        acquireTimeout: 10000
    }
});

client.raw('insert into `store_info` (`state_code`, `store_id`) values (\'xx\', \'xxxx\')').asCallback(function(err,data){
    if(err){
         console.log(err);
    }
    console.log(data);
});

$ docker run -d -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=xxxxxxxxx -e MYSQL_DATABASE=xxxxxxxxx mariadb:10.1.20
Unable to find image 'mariadb:10.1.20' locally
10.1.20: Pulling from library/mariadb
5040bd298390: Already exists 
55370df68315: Already exists 
fad5195d69cc: Already exists 
a1034a5fbbfc: Already exists 
eb46f36a6163: Pull complete 
de7067e4ea0a: Pull complete 
fc40d1291bb9: Pull complete 
1b86d3d50a3d: Pull complete 
c464a422954a: Pull complete 
ca6a2da75737: Pull complete 
79e633b60340: Pull complete 
49a5c52e71de: Pull complete 
Digest: sha256:90b76a6759a33007babd2e74480ad22946d515baeab75a13952feb42faae0653
Status: Downloaded newer image for mariadb:10.1.20
ffd26e2d1e9b580ad99cbb636ce28b557d8ea2568d0a292e87473cf1dedd4213

$ docker exec mysql mysql -pxxxxxxxxx -e 'select version()'
version()
10.1.20-MariaDB-1~jessie

$ docker exec mysql mysql -pxxxxxxxxx -Dxxxxxxxxx -e 'CREATE TABLE `store_info` (  `store_id` char(5) NOT NULL,  `state_code` varchar(5) DEFAULT NULL,  PRIMARY KEY (`store_id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;'

$ node test.js
[ OkPacket {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 },
  undefined ]
^C

$ docker exec mysql mysql -pxxxxxxxxx -Dxxxxxxxxx -e 'SELECT * FROM `store_info`;'
store_id	state_code
xxxx	xx
```

**Comment by ramumesh** [comment]
I  tested with the same.  For Maria db the database property is 'db'...  For mysql database property is 'database'....    I got the same result . row is not inserting...

**Comment by dougwilson** [comment]
Weird. I tried and had no issues. Please see https://github.com/mysqljs/mysql/issues/1700#issuecomment-295304469 . Let me know what I need to change in there to see the same behavior as you, otherwise I have no idea what is wrong if I cannot reproduce it to debug.

**Comment by ramumesh** [comment]
Now I tried with a transaction for  a single query... Its working fine....  Here is the code.... 
```
var client = require('knex');

var dbConfig = {
    host: 'xxxxxxxxxxxxx',
    user: 'root',
    password: 'xxxxxxx',
    database: 'xxxxxxx'
};

client = require('knex')({
    client: 'mysql',
    connection: dbConfig,
    pool: {
        acquireTimeout: 10000
    }
});

// Using trx as a transaction object:
client.transaction(function(trx) {
    client.insert({ state_code: 'xxxx',store_id:'ssss'})
      .into('store_info')
      .transacting(trx)
      .then(trx.commit)
      .catch(trx.rollback);
});

```

**Comment by ramumesh** [comment]
Maria db is hosted in the cloud with three nodes. It is a Cloud RDBMS. It could be the issue... I couldnt install and  test maraidb locally since I am inside a corporate environment..  we were testing mysql locally and thought the same will work for the mariadb.. i will let you know if I could test it locally with mariadb... 
Anyways thanks for helping... It could be a cloud issue that needs every query to be executed as a transaction...

**Comment by ramumesh** [comment]
Looks like I found the issue... 
I tried with  show global variables like 'autocommit';
Got the result saying autocommit is off...   
This could be the issue... 

Sorry buddy I bothered you....   Thanks for helping... You are awesome....

**Comment by ramumesh** [comment]
It would be great if you could add some message in these condition.. It is just a suggestion...

**Comment by dougwilson** [comment]
Hi @ramumesh it's no problem! I'm not sure what message to add, because there is nothing wrong with autocommit being off; in fact, it's a very normal condition to have when you only want to use transactions. This module just talks the MySQL protocol; a module like Knex is usually what adds extra bells and whistles over this, so if anything were to add such a message, you'd wan to make the request to the Knex library rather than here. The Knex is more abstracted such that it would have a good idea when you're making a mistake through it's API usage.

**Comment by dougwilson** [comment]
And as a bonus, since you had this same issue with not just this driver but others, if the message was added to Knex it would help everyone using any driver, not just this one.
