### ISSUE TITLE
Hosted my express app on heroku and used cleardb getting this error

### ISSUE THREAD

**Issue by Arpit1294** [mysqljs/mysql#1704]
So I have made an app where users can login using passport. A unique connection will be setup at each client as a particular user but as soon as 1 to 2 user logs int the system I face this error.
```
2017-04-21T12:58:48.617532+00:00 app[web.1]: memory, and will not scale past a single process.
2017-04-21T12:59:47.758436+00:00 heroku[web.1]: State changed from up to crashed
2017-04-21T12:59:47.748180+00:00 heroku[web.1]: Process exited with status 1
2017-04-21T12:59:47.704063+00:00 app[web.1]: events.js:160
2017-04-21T12:59:47.704075+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-21T12:59:47.704075+00:00 app[web.1]:       ^
2017-04-21T12:59:47.704076+00:00 app[web.1]: 
2017-04-21T12:59:47.704077+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2017-04-21T12:59:47.704078+00:00 app[web.1]:     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
2017-04-21T12:59:47.704079+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
2017-04-21T12:59:47.704080+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-04-21T12:59:47.704080+00:00 app[web.1]:     at Socket.emit (events.js:185:7)
2017-04-21T12:59:47.704081+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:974:12)
2017-04-21T12:59:47.704081+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-21T12:59:47.704082+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-21T13:15:17.726672+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-21T13:15:21.214156+00:00 heroku[web.1]: Starting process with command `node app.js`
2017-04-21T13:15:23.981814+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2017-04-21T13:15:23.981834+00:00 app[web.1]: designed for a production environment, as it will leak
2017-04-21T13:15:23.981835+00:00 app[web.1]: memory, and will not scale past a single process.
2017-04-21T13:15:24.783950+00:00 heroku[web.1]: State changed from starting to up
2017-04-21T13:16:23.719559+00:00 heroku[web.1]: Process exited with status 1
2017-04-21T13:16:23.719072+00:00 heroku[web.1]: State changed from up to crashed
2017-04-21T13:16:23.629087+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-21T13:16:23.629074+00:00 app[web.1]: events.js:160
2017-04-21T13:16:23.629088+00:00 app[web.1]:       ^
2017-04-21T13:16:23.629088+00:00 app[web.1]: 
2017-04-21T13:16:23.629091+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2017-04-21T13:16:23.629093+00:00 app[web.1]:     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
2017-04-21T13:16:23.629093+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
2017-04-21T13:16:23.629094+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-04-21T13:16:23.629094+00:00 app[web.1]:     at Socket.emit (events.js:185:7)
2017-04-21T13:16:23.629095+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:974:12)
2017-04-21T13:16:23.629096+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-21T13:16:23.629096+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-21T13:28:25.471849+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-21T13:28:37.117319+00:00 heroku[web.1]: Starting process with command `node app.js`
2017-04-21T13:28:42.497336+00:00 heroku[web.1]: State changed from starting to up
2017-04-21T13:28:42.313960+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2017-04-21T13:28:42.313974+00:00 app[web.1]: designed for a production environment, as it will leak
2017-04-21T13:28:42.313975+00:00 app[web.1]: memory, and will not scale past a single process.
2017-04-21T13:29:41.721323+00:00 heroku[web.1]: Process exited with status 1
2017-04-21T13:29:41.736229+00:00 heroku[web.1]: State changed from up to crashed
2017-04-21T13:29:41.625862+00:00 app[web.1]: events.js:160
2017-04-21T13:29:41.625872+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-21T13:29:41.625873+00:00 app[web.1]:       ^
2017-04-21T13:29:41.625874+00:00 app[web.1]: 
2017-04-21T13:29:41.625875+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2017-04-21T13:29:41.625876+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
2017-04-21T13:29:41.625876+00:00 app[web.1]:     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
2017-04-21T13:29:41.625877+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-04-21T13:29:41.625878+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:974:12)
2017-04-21T13:29:41.625878+00:00 app[web.1]:     at Socket.emit (events.js:185:7)
2017-04-21T13:29:41.625879+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-21T13:29:41.625879+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-21T13:39:13.048697+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-21T13:39:16.390654+00:00 heroku[web.1]: Starting process with command `node app.js`
2017-04-21T13:39:22.409289+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2017-04-21T13:39:22.409318+00:00 app[web.1]: designed for a production environment, as it will leak
2017-04-21T13:39:22.409319+00:00 app[web.1]: memory, and will not scale past a single process.
2017-04-21T13:39:22.810600+00:00 heroku[web.1]: State changed from starting to up
2017-04-21T13:40:21.949631+00:00 heroku[web.1]: State changed from up to crashed
2017-04-21T13:40:21.934536+00:00 heroku[web.1]: Process exited with status 1
2017-04-21T13:40:21.844812+00:00 app[web.1]: events.js:160
2017-04-21T13:40:21.844818+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-21T13:40:21.844818+00:00 app[web.1]:       ^
2017-04-21T13:40:21.844819+00:00 app[web.1]: 
2017-04-21T13:40:21.844820+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2017-04-21T13:40:21.844821+00:00 app[web.1]:     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
2017-04-21T13:40:21.844822+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
2017-04-21T13:40:21.844822+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-04-21T13:40:21.844823+00:00 app[web.1]:     at Socket.emit (events.js:185:7)
2017-04-21T13:40:21.844824+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:974:12)
2017-04-21T13:40:21.844824+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-21T13:40:21.844825+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-21T13:51:25.221003+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-21T13:51:27.904852+00:00 heroku[web.1]: Starting process with command `node app.js`
2017-04-21T13:51:30.330328+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2017-04-21T13:51:30.330341+00:00 app[web.1]: designed for a production environment, as it will leak
2017-04-21T13:51:30.330342+00:00 app[web.1]: memory, and will not scale past a single process.
2017-04-21T13:51:30.607125+00:00 heroku[web.1]: State changed from starting to up
2017-04-21T13:52:29.706992+00:00 heroku[web.1]: State changed from up to crashed
2017-04-21T13:52:29.707745+00:00 heroku[web.1]: Process exited with status 1
2017-04-21T13:52:29.624210+00:00 app[web.1]: events.js:160
2017-04-21T13:52:29.624223+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-21T13:52:29.624224+00:00 app[web.1]:       ^
2017-04-21T13:52:29.624225+00:00 app[web.1]: 
2017-04-21T13:52:29.624226+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2017-04-21T13:52:29.624227+00:00 app[web.1]:     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
2017-04-21T13:52:29.624227+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
2017-04-21T13:52:29.624228+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-04-21T13:52:29.624229+00:00 app[web.1]:     at Socket.emit (events.js:185:7)
2017-04-21T13:52:29.624229+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:974:12)
2017-04-21T13:52:29.624230+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-21T13:52:29.624231+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-21T13:57:25.078985+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=masterjisip.herokuapp.com request_id=a652bb39-51f8-4ca5-8946-1e69301cd923 fwd="103.71.76.6" dyno= connect= service= status=503 bytes= protocol=http
2017-04-21T13:57:25.810101+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=masterjisip.herokuapp.com request_id=836529a6-d310-42a1-a852-d62c67b8f7c3 fwd="103.71.76.6" dyno= connect= service= status=503 bytes= protocol=http
2017-04-21T13:57:48.898764+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=masterjisip.herokuapp.com request_id=c5b6824c-80b7-4c5b-8959-74ddfe6801ef fwd="103.71.76.6" dyno= connect= service= status=503 bytes= protocol=https
2017-04-21T13:57:49.847813+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=masterjisip.herokuapp.com request_id=da0eae24-9723-449a-84e8-b0c616952a8c fwd="103.71.76.6" dyno= connect= service= status=503 bytes= protocol=https
2017-04-21T13:58:11.319096+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=masterjisip.herokuapp.com request_id=d5edabf5-e3a9-4f7f-8387-1178f7b838b9 fwd="103.71.76.6" dyno= connect= service= status=503 bytes= protocol=https
2017-04-21T13:58:11.679208+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=masterjisip.herokuapp.com request_id=9fb862af-8342-490a-8a10-6be435b69fe5 fwd="103.71.76.6" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by dougwilson** [comment]
Hi @Arpit1294 the error you are seeing is because you had an open `connection` to the MySQL server and then server closed that (likely due to it's configured idle timeout) and you didn't have any listeners on the error event.

You can read more about server disconnects here: https://github.com/mysqljs/mysql#server-disconnects
You can read more about error handing here: https://github.com/mysqljs/mysql#error-handling

I hope this helps!
