### ISSUE TITLE
How to solve the 'Handshake inactivity timeout '

### ISSUE THREAD

**Issue by zyssyz123** [mysqljs/mysql#1719]
```sql
var pool = mysql.createPool({
        connectTimeout: 10000,
        host: '127.0.0.1',
        user: 'root',
        port: '3306',
        password: '123',
        database: 'Parser'
    });

    var sqls = [];
    // console.log(return_arr);

    for (var i = 0; i < return_arr.length; i++) {
        if (DBName == "method") {
            sqls[i] = "INSERT INTO method (methodUse, description, bel_any) values('" + escape(return_arr[i][1]) + "','" + escape(return_arr[i][2]) + "','" + escape(bel) + "')";
        } else if (DBName == "fields") {
            sqls[i] = "INSERT INTO fields (fieldsUSe, description, bel_class) values('" + escape(return_arr[i][1]) + "','" + escape(return_arr[i][2]) + "','" + escape(bel) + "')";
        } else if (DBName == "enumConstant") {
            sqls[i] = "INSERT INTO enum_constant (constantUse, description, bel_enum) values('" + escape(return_arr[i][1]) + "','" + escape(return_arr[i][2]) + "','" + escape(bel) + "')";
        } else if (DBName == "constructor") {
            sqls[i] = "INSERT INTO constructor (constructorUse, description, bel_any) values('" + escape(return_arr[i][1]) + "','" + escape(return_arr[i][2]) + "','" + escape(bel) + "')";
        }

    }

    console.log(sqls);


    async.eachSeries(sqls, function (item, callback) {
        
        pool.getConnection(function (err, connection) {
            // Use the connection
            if (err) {
                console.log(err);
            } else if (connection && 'query' in connection) {
                // process connection and connection.query
           
                connection.query({ sql: item, timeout: 10000000 }, function (error, results, fields) {
                    // And done with the connection.
                
                    console.log(results);
                    connection.release();

                    // Handle error after the release.
                    if (error) throw error;
                    console.log(results);
                    // Don't use the connection here, it has been returned to the pool.
                });
            }

        });


    }, function (err) {
        // 所有SQL执行完成后回调
        if (err) {
            console.log(err);
        } else {
            console.log("SQL全部执行成功");
        }
    });
```
this is my code 
and this is my problem
```
{ Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/songgeshuai/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:185:7)
    at Handshake._onTimeout (/Users/songgeshuai/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (/Users/songgeshuai/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/songgeshuai/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/songgeshuai/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/songgeshuai/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/songgeshuai/Desktop/javadoc-parser/method.js:435:14
    at /Users/songgeshuai/node_modules/async/dist/async.js:3047:16
    at replenish (/Users/songgeshuai/node_modules/async/dist/async.js:982:17)
    at /Users/songgeshuai/node_modules/async/dist/async.js:986:9
    at eachLimit$1 (/Users/songgeshuai/node_modules/async/dist/async.js:3133:22)
    at Object.<anonymous> (/Users/songgeshuai/node_modules/async/dist/async.js:1016:16)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
```

how to solve it ? thanks

**Comment by dougwilson** [comment]
Hi @zyssyz123 by default, the pool will only wait 10 seconds to acquire a connection. You can increase this with the `acquireTimeout` setting in the pool options. In most cases 10 seconds is more than enough time to get a connection to your database, but if this is not enough time, just put a higher limit in the  `acquireTimeout` setting in the pool options.

I hope this helps!
