### ISSUE TITLE
Handshake inactivity timeout

### ISSUE THREAD

**Issue by NeutralPlasma** [mysqljs/mysql#1737]
```
[2017-05-22 14:45:17.854] [ERROR] [default] - Cant get number from the last game
[2017-05-22 14:45:17.855] [DEBUG] [default] - { [Error: Handshake inactivity timeout]
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
Error: Handshake inactivity timeout
    at Handshake.<anonymous> (C:\Users\Gasper\Desktop\Hyper Injector\node_modules\mysql\lib\protocol\Protocol.js:160:17)
    at emitNone (events.js:67:13)
    at Handshake.emit (events.js:166:7)
    at Handshake._onTimeout (C:\Users\Gasper\Desktop\Hyper Injector\node_modules\mysql\lib\protocol\sequences\Sequence.js:127:8)
    at Timer.listOnTimeout (timers.js:92:15)
    --------------------
    at Protocol._enqueue (C:\Users\Gasper\Desktop\Hyper Injector\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (C:\Users\Gasper\Desktop\Hyper Injector\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (C:\Users\Gasper\Desktop\Hyper Injector\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (C:\Users\Gasper\Desktop\Hyper Injector\node_modules\mysql\lib\Pool.js:48:16)
    at query (C:\Users\Gasper\Desktop\Hyper Injector\site.js:595:7)
    at load (C:\Users\Gasper\Desktop\Hyper Injector\site.js:607:2)
    at Object.<anonymous> (C:\Users\Gasper\Desktop\Hyper Injector\site.js:59:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by NeutralPlasma** [comment]
Can any1 help me pls.?

**Comment by dougwilson** [comment]
Hi @NeutralPlasma the error means that it took longer than 10 seconds to establish a connection to your MySQL server. You may want to investigate packet captures to see what is making the connection establishment take so long, but you can always increase the timeout by changing the [`
acquireTimeout` pool option](https://github.com/mysqljs/mysql#pool-options).
