### ISSUE TITLE
Unusual syntax error

### ISSUE THREAD

**Issue by dextermb** [mysqljs/mysql#1752]
Hey there,
I am getting this syntax error- but it seems to just be a block of comments, so I'm unsure why this is flagging an error. I understand that it seems to be from _bignumber_ but the stack does go all the way back to _mysql_.

```
<h1>Invalid or unexpected token</h1>
<h2></h2>
<pre>/var/www/099/node_modules/bignumber.js/bignumber.js:1720
        /*
        ^^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/var/www/099/node_modules/mysql/lib/protocol/Parser.js:4:25)</pre>
```

Any ideas?

Here's my `package.json`: [package.txt](https://github.com/MikeMcl/bignumber.js/files/1082806/package.txt)

**Comment by dextermb** [comment]
Seems that it was because `npm` didn't install the latest dependencies... /t
