### ISSUE TITLE
error: UNKNOWN_CODE_PLEASE_REPORT

### ISSUE THREAD

**Issue by liesislukas** [mysqljs/mysql#1754]
I have clicked "Bring offline" in mysql workbench and got this error (below). Server reboot solved this. Service restart ended with a message that mysql can't start.

Server version: 5.7.16 MySQL Community Server (GPL)
running on Ubuntu 14.04.5 LTS

Error message says "please report", so reporting.

**mysql workbench button:**
![image](https://user-images.githubusercontent.com/2733862/27331813-ba0f6f5c-55c7-11e7-8593-a95af35258a0.png)

**Error:**
```
  error while connecting to db: { Error: UNKNOWN_CODE_PLEASE_REPORT: The server is currently in offline mode
    at Handshake.Sequence._packetToError (/Users/lukas/.../node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/Users/lukas/.../node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/Users/lukas/.../node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/lukas/.../node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/lukas/.../node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/lukas/.../node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)
    --------------------
      at Protocol._enqueue (/Users/lukas/.../node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/lukas/.../node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/Users/lukas/.../node_modules/mysql/lib/Connection.js:130:18)
    at Timeout.handleDisconnect [as _onTimeout] (/Users/lukas/.../src/api/db/v1/helpers/mysql/connection.js:18:14)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
    code: 'UNKNOWN_CODE_PLEASE_REPORT',
      errno: 3032,
      sqlState: 'HY000',
      fatal: true }
```

**Comment by dougwilson** [comment]
Wow, this is a big bug in the tooling that collects the error codes, now that I look into it. Thanks for the report, will fix soon!

**Comment by liesislukas** [comment]
thanks. I'm not sure what's that "go offline" and after clicking that i haven't found what happened and finally updated all server and reinstalled sql altogether lol. Hopefully, it's solved for future users :) thanks for your great job 
👍
