### ISSUE TITLE
 Cannot read property 'insertId' of undefined

### ISSUE THREAD

**Issue by Young1993** [mysqljs/mysql#1763]
I use the node-mysql insert data into table,but the return  insertId shows undefined, how to solve this problem
`query($sql.insertUser, [req.program_id, req.openid, req.nickName, req.avatarUrl, req.city, req.province, req.gender, req.country], function(err, results, fields) {
			console.log('id:', results.insertId);
			callback(results.insertId);
		});`

throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'insertId' of undefined
    at /home/prophet/node-wallet/pay/dao/wechatDao.js:67:35
    at Query._callback (/home/prophet/node-wallet/pay/conf/db.js:23:5)
    at Query.Sequence.end (/home/prophet/node-wallet/pay/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/home/prophet/node-wallet/pay/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/home/prophet/node-wallet/pay/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/prophet/node-wallet/pay/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/prophet/node-wallet/pay/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/prophet/node-wallet/pay/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readab

**Comment by dougwilson** [comment]
You are not using Node.js style callbacks correctly. You are not checking the `err` value. Read https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#errors_node_js_style_callbacks for more information on what Node.js style callbacks are and how you should interact with them.
