### ISSUE TITLE
testOnBorrow

### ISSUE THREAD

**Issue by willin** [mysqljs/mysql#1778]
ref to: <https://www.npmjs.com/package/generic-pool>

testOnBorrow: boolean: should the pool validate resources before giving them to clients. Requires that either factory.validate or factory.validateAsync to be specified

how to validate resources?

**Comment by ifsnow** [comment]
@willin The pool is already checking the connection whenever it's borrowed from the pool.

The connection is validated via ping check before returning.

**Comment by dougwilson** [comment]
@willin are you asking if this module has a `testOnBorrow` option (@ifsnow got that answer) or how you would implement something for that in generic-pool?

**Comment by willin** [comment]
`PROTOCOL_SEQUENCE_TIMEOUT`


```
2017-07-20 03:03:19 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:202:8)
    at Object.result.query (/home/airdwing/projects/AirX/node_modules/@dwing/mysql/src/pool.js:27:13)
    at QUERY (/home/airdwing/projects/AirX/src/lib/orm.js:24:31)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-20 03:03:29 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-20 03:03:29 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-20 03:03:29 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by willin** [comment]
``` 
2017-07-21 04:35:28 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:202:8)
    at Object.result.query (/home/airdwing/projects/AirX/node_modules/@dwing/mysql/src/pool.js:27:13)
    at QUERY (/home/airdwing/projects/AirX/src/lib/orm.js:24:31)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-21 06:09:49 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:202:8)
    at Object.result.query (/home/airdwing/projects/AirX/node_modules/@dwing/mysql/src/pool.js:27:13)
    at QUERY (/home/airdwing/projects/AirX/src/lib/orm.js:24:31)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-21 06:09:59 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-21 06:09:59 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-21 06:10:09 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-21 06:40:51 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Ping.onOperationComplete [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:101:12)
    at Ping.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-21 06:41:01 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-07-21 06:41:12 +00:00: Trace: { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/airdwing/projects/AirX/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/home/airdwing/projects/AirX/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /home/airdwing/projects/AirX/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
    at Object.module.exports [as err] (/home/airdwing/projects/AirX/src/hook/error.js:20:13)
    at /home/airdwing/projects/AirX/node_modules/koa-api-logger/src/index.js:34:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by dougwilson** [comment]
Hi @willin that happens when you go to check out a connection, and the pool contains to valid connections, so it needs to establish a _new_ connection to the database, but in the process, the handshake to the server times out (i.e. it can't connect).

If you want to change the timeout, you can use the `acquireTimeout` setting in the pool: https://github.com/mysqljs/mysql#pool-options
