### ISSUE TITLE
connection.destroy() is not a function?

### ISSUE THREAD

**Issue by PsyTae** [mysqljs/mysql#1781]
ln 432: if(connection._freeConnections.length > connection.config.connectionLimit) connection.destroy();

Uncaught Exception Error:
$ TypeError: connection.destroy is not a function
    at C:\nodeCode\Code\Code.js:432:89
    at C:\nodeCode\Code\node_modules\async\dist\async.js:421:16
    at processQueue (C:\nodeCode\Code\node_modules\async\dist\async.js:1565:20)
    at taskComplete (C:\nodeCode\Code\node_modules\async\dist\async.js:1588:9)
    at Query.<anonymous> (C:\nodeCode\Code\node_modules\async\dist\async.js:1612:17)
    at Query.onResult (C:\nodeCode\Code\node_modules\async\dist\async.js:906:16)
    at C:\nodeCode\Code\node_modules\mysql2\lib\commands\query.js:65:14
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by dougwilson** [comment]
Hi @PsyTae the module in your stack trace is a different module: `mysql2`. And I see you already filed a ticket in that issue tracker.
