### ISSUE TITLE
Parser.js:80

### ISSUE THREAD

**Issue by westrider** [mysqljs/mysql#1813]
Hi 

Please can you help me with this problem?
```
/bot/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'createOffer' of undefined
    at Query._callback (/var/www/html/bot/driver.js:659:65)
    at Query.Sequence.end (/var/www/html/bot/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/var/www/html/bot/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/var/www/html/bot/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/var/www/html/bot/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/www/html/bot/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/www/html/bot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/html/bot/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```
I dont know why is this error in 

Call code: 659 line 

                        var app = bots_list[my_inv[0]['bot_id']].createOffer(tradelink);
                        items.forEach(function(target) {
                          app.addMyItem({
                              appid: 730,
                              contextid: 2,
                              amount: 1,
                              assetid: target
                            });
                          });

Thank you so much

**Comment by dougwilson** [comment]
Hi @westrider that is a normal JavaScript error that has nothing to do with this module. It is saying that `bots_list[my_inv[0]['bot_id']]` in your code there is `undefined` and so you cannot call the method `createOffer` on it since it's not an object. Without the entirety of your code, it's hard to understand why that is happening.

**Comment by renatoOliveira25** [comment]
I'm having the same problem:

```
/home/renato/Dropbox/Workspace/NodeProjects/portal_noticias/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^
```

I have tried with and wihiout the 'throw', but leads to the same error. Can anyone help me pls? 
That's my entire js file:

```
module.exports = function(app) {

    app.get('/noticias', function(req, res){
        
        var mysql = require('mysql');

        var connection = mysql.createConnection({
            host : 'localhost',
            port : 3003,
            user : 'renato',
            password: '1234',
            database : 'portal_noticias'
        });

        /*
        connection.connect(function(error){
            if (error) throw error;
            connection.query("Select * FROM noticias", function(error, result, fields){
                if (error) throw error;
                res.render(result);
                console.log(result);
            });
        }); */

        
        connection.query('select * from noticias', function(error, result){
            res.render(result);
        });
        
        //res.render('noticias/noticias');   
    });
}; 
```

**Comment by kai-koch** [comment]
@renatoOliveira25
You need to provide more information. For instance the whole stack trace. Some code that can be used to reproduce the error.
Since it seems a non-mysql error, it is very unlikely that it is the same error as in the original post.
Also you have no error handling in ```connection.query```, it would be helpful to log the error in the callback.

Just from your code snippet, I would say it is bad practice to connect in a local function since ```connection``` is garbage collected, if no more reference is found after the function is executed and exits.
Instead create the connection at a higher level scope or inject the dependency into the routing model.

**Comment by kai-koch** [comment]
Also you connect to a non-standard port. Are you sure your DB listens at port 3003 instead of 3306?

**Comment by renatoOliveira25** [comment]
@kai-koch I found what I've done wrong... in this function I'm using the wrong method `render`, actually is `send`. Thanks for the support. (And yes, I'm using MySQL at the port 3303 'cause I've seen in a post that this could be the cause of the error).

`connection.query('select * from noticias', function(error, result){
            res.render(result);
        });`

**Comment by kanda94** [comment]
> @kai-koch I found what I've done wrong... in this function I'm using the wrong method `render`, actually is `send`. Thanks for the support. (And yes, I'm using MySQL at the port 3303 'cause I've seen in a post that this could be the cause of the error).
> 
> `connection.query('select * from noticias', function(error, result){ res.render(result); });`

please can you you explan this,i am also tired with this

**Comment by kai-koch** [comment]
If it is the same error as @renatoOliveira25  has, The object ```res``` has no method ```render()```.

I do not know which framework you guys are using so I can only guess. Maybe you have coppies old example code on a new version of your framework and the API has changed and ```render()``` is replaced by ```send()```.
It is very hard to debug remotley, if you do not give any hint what you are using.
Maybe you just forget to define a template or the route does not exist in your app. There are to many possibilities and I have not enough input to help you.
Provide the versions of node, mysqljs and the version of the framework you are using. And code that reproduces the error would be nice, too.

**Comment by provawebdev** [comment]
I am having the same error please help.

/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read property 'author' of undefined
    at Query.<anonymous> (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/routes/show.js:58:36)
    at Query.<anonymous> (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/opt/lampp/htdocs/afroza/storage_system/nodeMysql-master/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)

**Comment by alijab30000** [comment]
I am having the same error please help.
    throw err; // Rethrow non-MySQL errors
      ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
