### ISSUE TITLE
Error Geting info from database! 

### ISSUE THREAD

**Issue by jamalabo1** [mysqljs/mysql#1837]
```
/var/www/nodejs/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'seller' of undefined
    at Query._callback (/var/www/nodejs/stripe/app.js:70:30)
    at Query.Sequence.end (/var/www/nodejs/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/var/www/nodejs/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/var/www/nodejs/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/var/www/nodejs/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/www/nodejs/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/www/nodejs/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/nodejs/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
```

it runs one time ( can access the page one time ) and then the app get crashed!

**Comment by dougwilson** [comment]
Hi @jamalabo1 the error is `TypeError: Cannot read property 'seller' of undefined` which occurred in the file `/var/www/nodejs/stripe/app.js` on line 70. Can you share that file?

**Comment by dougwilson** [comment]
Closing since I never heard back.
