### ISSUE TITLE
etimeout error while running on google app engine

### ISSUE THREAD

**Issue by megancooper** [mysqljs/mysql#1857]
I have created a mysql database on google cloud that I'd like to access from a separate node web application (also running on google cloud). I am testing the connection locally on my computer first, and when I run the following code locally I can successfully establish a connection to my database and see the data in it.

```
    'use strict';

    // [START app]
    const express = require('express');
    const bodyParser = require('body-parser');
    const path = require('path');
    const app = express();
    const mysql      = require('mysql');

    var connection = mysql.createConnection({
      host     : 'Cloud SQL IP',
      user      : 'username',
      password  : 'password',
      database  : 'db_name'
    });



    // parse application/x-www-form-urlencoded
    app.use(bodyParser.urlencoded({ extended: false }))

    // parse application/json
    app.use(bodyParser.json())

    // Make globals.js accessible
    app.use(express.static(__dirname + '/'));


    app.get('/', (req, res) => {
	    connection.connect();
 
	    connection.query('SELECT * FROM Users', function (error, results, fields) {
  		    if (error) throw error;
  		    console.log(results);
	    });
 
	    connection.end();
  	    res.status(200).send('Hello World!');
    });

    app.get('/login', (req, res) => {
  	    res.status(200).send();
    });

    // [START server]
    const PORT = process.env.PORT || 8080;
    app.listen(PORT, () => {
      console.log(`App listening on port ${PORT}`);
      console.log('Press Ctrl+C to quit.');
    });
    // [END app]
```

However when run this same code in my google app engine (for both debugging on port 8080 and fully deployed on https://myapp.appspot.com) I get the following timeout error:

```
    { Error: connect ETIMEDOUT
        at Connection._handleConnectTimeout         (/home/megan_cooper2900/project/node_modules/mysql/lib/Connection.js:419:13)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/megan_cooper2900/project/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/megan_cooper2900/project/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/home/megan_cooper2900/project/node_modules/mysql/lib/Connection.js:130:18)
    at app.get (/home/megan_cooper2900/journeyma/app.js:31:13)
    at Layer.handle [as handle_request] (/home/megan_cooper2900/project/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/megan_cooper2900/project/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/megan_cooper2900/project/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/megan_cooper2900/project/node_modules/express/lib/router/layer.js:95:5)
    at     /home/megan_cooper2900/project/node_modules/express/lib/router/index.js:281:22
        at Function.process_params         (/home/megan_cooper2900/project/node_modules/express/lib/router/index.js:335:12)
      errorno: 'ETIMEDOUT',
      code: 'ETIMEDOUT',
      syscall: 'connect',
      fatal: true }
```

Why is this not working on the Google App Engine application?

**Comment by dougwilson** [comment]
It's possible you have a firewall between where you deployed and your MySQL server. That error indicates the three-way TCP handshake didn't complete within 10 seconds.

**Comment by dougwilson** [comment]
Closing since I didn't hear anything further.
