### ISSUE TITLE
Handling Connection timeout with Connections Pool

### ISSUE THREAD

**Issue by loretoparisi** [mysqljs/mysql#1870]
I'm using a connections pool like:

```javascript
var pool= mysql.GetInstance().createPool({
            // If true, the pool will queue the connection request and call it when one becomes available. If false, the pool will immediately call back with an error.
            waitForConnections: true,
            // The milliseconds before a timeout occurs during the connection acquisition.
            acquireTimeout: 10 * 1000,
            // The maximum number of connection requests the pool will queue before returning an error. If set to 0, there is no limit to the number of queued connection requests.
            queueLimit: 0,
            // The maximum number of connections to create at once.
            connectionLimit : 10,
            host            : this._options.mysql.host,
            user            : this._options.mysql.user,
            password        : this._options.mysql.password,
            database        : this._options.mysql.database
        });
        pool.on('connection', function (connection) {
            if(self.logger) self.logger.debug('new connection %d', connection.threadId);
        });
        pool.on('release', function (connection) {
            if(self.logger) self.logger.debug('Connection %d released', connection.threadId);
        });
        pool.on('acquire', function (connection) {
            if(self.logger) self.logger.debug('Connection %d acquired', connection.threadId);
        });
        pool.on('enqueue', function () {
            if(self.logger) self.logger.debug('Waiting for available connection slot');
        });
```

To handle timeout error we have the `error` callback on the connection like:

```javascript
connection.on('error', function(error) {
                if(error.code === 'PROTOCOL_CONNECTION_LOST' || 
                    error.code=='PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR' ||
                    error.code=='ETIMEDOUT') {
                    if(self.logger) self.logger.error('connection error:\n@', error);
                }
            });
```

Now, using the connections pool how to handle this error? Shall I attach the handler for each connection like:

```javascript
pool.on('connection', function (connection) {
            connection.on('error', function(error) {
                if(error.code === 'PROTOCOL_CONNECTION_LOST' || 
                    error.code=='PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR' ||
                    error.code=='ETIMEDOUT') {
                    if(self.logger) self.logger.error('connection error:\n@', error);
                }
            });
            if(self.logger) self.logger.debug('new connection %d', connection.threadId);
        });
```

o may I attach a global connection error handler for the pool? 
My aim it to avoid the program to crash, and bypass the problematic connections.

The error I get is

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (/node_modules/mysql/lib/Connection.js:419:13)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

and the program just exits with `1`.

**Comment by dougwilson** [comment]
That is stange, because our pool doesn't emit error events, as the pool handles them. I'm not sure what is emitting the error ib your example. Would you mind sharing a complete code example I can copy and paste and run to reproduce the issue? Something is bugged if you are getting that with the pool.

**Comment by loretoparisi** [comment]
@dougwilson Thank you. I will try to wrap my code in a test class to reproduce that issue.

**Comment by stoneburner** [comment]
i have the same issue, using pools and even when destroying connections after each use, after a few minutes the server gets terminated:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/<pathreplaced>/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/<pathreplaced>/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

this is the relevant part of my code:
```
var pool = mysql.createPool(config.mysql)

pool.on('acquire', function (connection) {
  connection.on('error', function(error) {
    console.log("connection error:",error) // <- this also dont work
    connection.close();
  })
  console.log('Connection %d acquired', connection.threadId);
});

pool.on('connection', function (connection) {
  console.log('connection established', connection.threadId)
});

pool.on('enqueue', function () {
  console.log('Waiting for available connection slot');
});

pool.on('release', function (connection) {
  console.log('Connection %d released', connection.threadId);
  connection.destroy()
});

function doQuery(sql, parameters, callback) {
  pool.getConnection(function(err, connection) {
    if (err) {
      callback(err)
    } else {
      connection.query(sql,parameters,  function (error, results, fields) {
        connection.release();
        callback(error,results,fields)
      })
    }
  })
}
```

**Comment by dougwilson** [comment]
I'm going to close this since I haven't heard anything back.
