### ISSUE TITLE
Error: Packets out of order. Got: 80 Expected: 0

### ISSUE THREAD

**Issue by sonukapoor** [mysqljs/mysql#1890]
I am trying to connect to our mysql server using the following code:
```

var mysql = require('mysql');
var db = mysql.createConnection({
  host: "XXX.XXX.XXX.XXX",
  port: XXXX,
  database: "XXX",
  user: "XX",
  password:" XXX",
  debug:true
});

db.connect(function(err) {
  if (err) console.error('error connecting: ' + err.stack);
  console.log("Connected!");
});
```

However I receive the following error message:

```
error connecting: Error: Packets out of order. Got: 80 Expected: 0
    at Parser.write (some-folder/code/node_modules/mysql/lib/protocol/Parser.js:42:19)
    at Protocol.write (some-folder/code/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (some-folder/code/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    --------------------
    at Protocol._enqueue (some-folder/code/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (some-folder/code/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (some-folder/code/node_modules/mysql/lib/Connection.js:130:18)
    at Object.<anonymous> (some-folder/code/src/db/index.js:21:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

Node version: 6.11.1
mySql Version: 5.6.38 

Any idea what I am missing here?

**Comment by dougwilson** [comment]
Nothing you're doing wrong; that usually means something is really wrong. Can you provide the version of this module you are using as well? I'll work on setting up a MySQL server version of exactly 5.6.38. I assume you're using the community version? Did you get it from a package manager or compile from source? Also would you be willing to use Wireshark to capture the packets during this on your machine?

**Comment by sonukapoor** [comment]
@dougwilson I think I was using the wrong port and don't believe its an issue with your package. Thanks for the quick response though. If you still need anything from my end, let me know.

**Comment by TheRockstarr33** [comment]
Hey! Sorry to comment on an older thread (I'm a bit new to GitHub and Node.js...) but has anyone found a solution to this? I'm running into the same problem myself. If I can provide any info, I'll be happy to help. I'm using Node version 8.9.4 at the moment!

**Comment by dougwilson** [comment]
Hi @TheRockstarr33 it's OK. Please feel free to open a new issue regarding what you're encountering as this issue has been resolved (connecting to wrong port). Please include in your report as much as possible, including the exact error you're getting, version of this module, and perhaps even code to reproduce the issue and we're happy to help.

Sorry I didn't see your post until I went to clean up this issue. Opening a new issue brings it to attention quicker.

**Comment by kac-** [comment]
Hi @dougwilson, crash occurs i.e. when you stop MySQL service while **mysqljs** connection (single or via pool) is open, server sends to clients "Connection was killed" which eventually kills whole node app.
Server on this error sets "Packet Number" to 0 (zero), that makes fatal exception on **mysqljs** side.
![packet decoded by wireshark](https://user-images.githubusercontent.com/604344/40665794-7610f618-635e-11e8-90ab-0129e6fb4691.png)

**Comment by dougwilson** [comment]
Hi @kac- very interesting. I wonder why then would OP get the message that mysqljs expected the packet number to be zero but the server sent packet number 80 if that's the case here?

**Comment by dougwilson** [comment]
Ah, interesting @kac- . Are you sure you've having the same issue here or do you want to create a new issue to describe your issue so we can take a deeper look?

**Comment by kac-** [comment]
It definitely looks like separate issue.
