### ISSUE TITLE
Trying to use FakeServer to test applications

### ISSUE THREAD

**Issue by MayamaTakeshi** [mysqljs/mysql#1902]
Hi,
I am starting an instance of FakeServer this way:
```
var FakeServer = require("mysql/test/FakeServer.js")
var common = require("mysql/test/common")

var server     = new FakeServer();

server.listen(3333, function (err) {
  console.log("FakeServer waiting connections")
})

server.on('connection', function(conn) {
  conn.handshake({
    protocolVersion: 10,
    protocol41: true,
  });
  conn.on('query', function(packet) {
    console.log("got query: " + packet.sql)
  })
})
```

If I connect to it using common.createConnection(), the above works.
However, if I try to connect to it using the mysql client (CLI) like this:
```
$ mysql -u admin -pfake --port=3333 -h 127.0.0.1 mydb
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0
```
or using python MySQLdb I get:
```
takeshi@takeshi-desktop:functional$ node t.js 
FakeServer waiting connections
/home/takeshi/tmp/test2/functional/node_modules/mysql/lib/protocol/Parser.js:20
  this._onError           = options.onError || function(err) { throw err; };
                                                               ^

Error: Offset of null terminated string not found.
    at Parser._nullByteOffset (/home/takeshi/tmp/test2/functional/node_modules/mysql/lib/protocol/Parser.js:302:20)
    at Parser.parseNullTerminatedString (/home/takeshi/tmp/test2/functional/node_modules/mysql/lib/protocol/Parser.js:288:23)
    at ClientAuthenticationPacket.parse (/home/takeshi/tmp/test2/functional/node_modules/mysql/lib/protocol/packets/ClientAuthenticationPacket.js:25:33)
    at FakeConnection._parsePacket (/home/takeshi/tmp/test2/functional/node_modules/mysql/test/FakeServer.js:264:10)
    at Parser.write (/home/takeshi/tmp/test2/functional/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at FakeConnection._handleData (/home/takeshi/tmp/test2/functional/node_modules/mysql/test/FakeServer.js:115:16)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
```

I know FakeServer is not one of the deliverables of this project but it would be nice to be able to use it a part of testing frameworks.

**Comment by MayamaTakeshi** [comment]
Hi,
comparing packets for connection with a real MySQL server I realized I need to set some extra handshake options:
```
var FakeServer = require("mysql/test/FakeServer.js")
var common = require("mysql/test/common")

var server     = new FakeServer();

server.listen(3333, function (err) {
  console.log("FakeServer waiting connections")
})

server.on('connection', function(conn) {
  conn.handshake({
    protocolVersion: 10,
    serverVersion: "some_version",
    threadId: 100,
    serverCapabilities1: 0xf7ff,
    serverLanguage: 8,
    serverStatus: 2,
    protocol41: true,
  });
  conn.on('query', function(packet) {
    console.log("got query: " + packet.sql)
  })
})
```
The above works.
