### ISSUE TITLE
Server closed connection

### ISSUE THREAD

**Issue by Serhioromano** [mysqljs/mysql#1918]
It used to work fine. But one moment it started to produce this error and then when I change something it is gone and than back again. Now it persist. I created very small file and still get this error.

```js
var mysql = require('mysql');

var con = mysql.createConnection({
    host: '127.0.0.1',
    user: 'root',
    password: 'root',
    database: 'mydb',
    charset: 'utf8_general_ci'
});
con.connect();
```

And this one also drops the same error

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/Users/sergey/Sites/Ulacos/backend/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/Users/sergey/Sites/Ulacos/backend/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I've no idea what to do next.

**Comment by dougwilson** [comment]
Hi @Serhioromano the only thing that error means is that the TCP/IP connection was closed by the remote. The stack trace show that it's getting triggered by the internal Node.js Socket events, so unless there is something wrong with the Node.js install, it would seem like something is terminating the TCP/IP connection.

Is it possible you can use Wireshark or similar to get a pcap of the event occurring?

**Comment by Serhioromano** [comment]
After I restart MySQL it works again. But only one time and after finish, the same problem. Can `connection.end()` be the problem?

 > Is it possible you can use Wireshark or similar to get a pcap of the event occurring?

Unfortunately I am not aware of this technology but I'll look what I can do.

**Comment by dougwilson** [comment]
Hi @Serhioromano `connection.end()` is just the method to close the TCP/IP connection that the object represents. I don't see it in your code example above, though. Ideally if you can get that packet capture, or if you can provide all the code and instructions so I can reproduce the issue I can debug it over on my side, otherwise unfortunately the environment that can be debugged is yours which I don't have access to :(

**Comment by Serhioromano** [comment]
My code is part of very complicated project. It is CLI tool for that project. But I wanted to extract it into a standalone project because I can see how others can benefit from it.

**Comment by Serhioromano** [comment]
Ok. Here it is. I've decoupled code into a different project.

https://github.com/Serhioromano/db-snapshot

You can try it. There is small instruction how to install in readme file. Everything works fine on dump and restore. But as soon as I set `-k` flag on restore with check and recreate constraints it loses connection.

Strange that it does work to the end and produce Finish! message. After that message no SQL queries are made, but it is impossible to run new commands. Connect get lost with  `PROTOCOL_CONNECTION_LOST` error on every new attempt to connect until I restart MySQL.

Even more strange that at the same time I can work with MySQL on the other client no problems. Looks like this error only for this client.

**Comment by dougwilson** [comment]
Thanks, I will play around with it today. Just looking at the code I remember users reporting this modulr does not work with the synchronize module. I suggest removing that module to see if that is the issue. Also remove process.exit because it also looks like you're calling it sync with your queries, but you need to wait for queries to complete before you exit the program. Another thing to try is to try the "mysql2" module instead of this module, which will narrow down to a general issue with your program or an issue with this module.

**Comment by dougwilson** [comment]
Another thing to try is to change https://github.com/Serhioromano/db-snapshot/blob/master/src/lib/restore.js#L22 to `sync(con, 'query', 'connect', 'end');` if I'm understanding the `synchronize` module documentation correctly.

**Comment by dougwilson** [comment]
It also seems from the docs that your call https://github.com/Serhioromano/db-snapshot/blob/master/src/lib/restore.js#L24 needs to be within the `sync.fiber` wrapper since you wrapped the `connect` method. Not sure if calling it outside the fiber would result in any issues, but it looks like it should be within the filter (and thus no callback) or you can remove the `'connect'` argument from the `sync` method call.

**Comment by Serhioromano** [comment]
> I remember users reporting this modulr does not work with the synchronize module. I suggest removing that module to see if that is the issue.

How can I call `query` synchronously then?

> Also remove process.exit because it also looks like you're calling it sync with your queries, but you need to wait for queries to complete before you exit the program.

Since I run it within `sync`, it should execute after query is executed right? And I do not know how to exit program correctly. If I remove it, I can to press Ctrl+C to stop execution otherwise it hangs.

> Not sure if calling it outside the fiber would result in any issues, but it looks like it should be within the filter (and thus no callback) or you can remove the 'connect' argument from the sync function call.

Callback works.

---

In general, I addressed most of you suggestions except removing `sync`. And issue still exists. After 2 consecutive runs of restore, connection breaks.

Could you reproduce error?

**Comment by dougwilson** [comment]
Unfortunately I didn't end up having any time on Friday to try it, so still need to. If you have spare time, putting together a pull request with a fix would be really appreciated! Otherwise I just need to find some time, which I don't have much of, unfortunately. The issue is also open here in case someone else can help too :+1:

**Comment by Serhioromano** [comment]
New data. After removing `process.exit()` no disconnections on consecutive calls. Everything works fine, and  only initial problem remains. As soon as I run restore with constraints, it finishes it normally, but next run connection problem.

With constraints means flag `-k` in a command so I restore constraints too. Those lines of code https://github.com/Serhioromano/db-snapshot/blob/master/src/lib/restore.js#L222-L259

I would put togather a PR but unfortunately I do not even understand where to start. I know I have trace stack on connection error, but something happen in previous run, which actually produce no error. I am in a complete dark here. Otherwise I would just suggest a fix.

**Comment by Serhioromano** [comment]
I've tried `mysql2` and now I have other problem.

```
/Users/sergey/Sites/#Projects/db-snapshot/node_modules/synchronize/sync.js:102
    if (called) throw new Error("defer can't be used twice!")
                ^

Error: defer can't be used twice!
    at Execute.onResult (/Users/sergey/Sites/#Projects/db-snapshot/node_modules/synchronize/sync.js:102:23)
    at Connection._notifyError (/Users/sergey/Sites/#Projects/db-snapshot/node_modules/mysql2/lib/connection.js:234:15)
    at Socket.<anonymous> (/Users/sergey/Sites/#Projects/db-snapshot/node_modules/mysql2/lib/connection.js:120:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
``` 

Some problems with `sync`

Let me try to get rid of it and see what happens.

**Comment by Serhioromano** [comment]
New information

I made a test with `mysql2` and `async` `await` calls. Everything works the same. As soon as I use constraint flag connection get lost.
