### ISSUE TITLE
using STR_TO_DATE in prepared INSERT gives "Incorrect parameter count in the call to native function 'STR_TO_DATE'" error

### ISSUE THREAD

**Issue by ktravelet** [mysqljs/mysql#1919]
I'm really really stuck on this, sorry if it's not related to the driver. 

slightly simplified:
```
const insertSql = 'insert into t1 values(STR_TO_DATE(?, '%c/%e/%Y'))'
const insertBinds = ['9/7/2016']

pool.query(insertSql, insertBinds, (err) => {
    if (err) {
        console.log(err)
    }
})

//Error: Incorrect parameter count in the call to native function 'STR_TO_DATE'
    at Packet.asError (***/node_modules/mysql2/lib/packets/packet.js:713:13)
    at Query.Command.execute (***/node_modules/mysql2/lib/commands/command.js:28:22)
    at PoolConnection.Connection.handlePacket (***/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (***/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (***/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (***/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
```

**Comment by dougwilson** [comment]
For some reason your code doesn't eveb compile as valid javascript. I changed the quotes since you used single quotes within single quotes and the query executed fine. Looks like you may have just messed up the quotes :+1: Here is the working code:

```js
const insertSql = 'insert into t1 values(STR_TO_DATE(?, "%c/%e/%Y"))'
const insertBinds = ['9/7/2016']

pool.query(insertSql, insertBinds, (err) => {
    if (err) {
        console.log(err)
    }
})
```
