### ISSUE TITLE
Error while querying

### ISSUE THREAD

**Issue by xeu100** [mysqljs/mysql#1930]
app.js
```
var port = ---;


var express = require('express');
var app = express();
app.enable('trust proxy')
app.use(express.static('./static/landing'));

var mysql = require('mysql');
var connection = mysql.createConnection({
    "host": "---",
    "port": ---,
    "user": "---",
    "password": "---",
    "database": "---"
});

var bodyParser = require('body-parser');
app.use(bodyParser.json());

var blah = require('./public/blah');
blah.init;

exports.app = app;
exports.connection = connection;
exports.logs = logs;

app.listen(port);
console.log('---');
```

public/blah.js
```
var main = require('../app.js');

function init() {
    var sql = "---";
    main.connection.query(sql, function (err, result) {
        if (err) throw err;
    });
}
```

(I replaced all sensitive fields with ---)

I have another js file where I am doing this but it doesn't error. When it gets to the blah.js file, it errors.

Error
```
C:\Users\---\---\---\---\---.js:5
    main.connection.query(sql, function (err, result) {
                    ^

TypeError: Cannot read property 'query' of undefined
    at init (C:\Users---\---\---\---\---.js:5:21)
    at Object.<anonymous> (C:\Users---\---\---\---\---.js:17:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users---\---\---\---\---.js:21:12)

Process finished with exit code 1
```

**Comment by dougwilson** [comment]
I tried to run your code but didn't get that error. Can you provide instruction on how I need to place your code above into new files and then the command to run to see the error above?

**Comment by kai-koch** [comment]
I think you got your requires messed up.
"app.js" requries "./public/blah.js"
"blah.js" requires "../app.js"
```main.connection``` is not exported yet, when it is used by blah.init

try this as "./public/blah.js"

```JS
function init() {
    var sql = "---";
    // connection refers to the connection object in app.js now 
    connection.query(sql, function (err, result) {
        if (err) throw err;
    });
}

exports.init = init;
```

**Comment by dougwilson** [comment]
Since I didn't hear back for a while from my question, and @kai-koch provided some additional information, I'm going to close this issue. @xeu100 let us know if you're still having trouble and can provide more info :) !
