### ISSUE TITLE
Can't catch PROTOCOL_CONNECTION_LOST error

### ISSUE THREAD

**Issue by dzek69** [mysqljs/mysql#1977]
I wrote a class to keep single connection alive for me and if error happens on connection it should just recreate the connection.

However, from time to time, on my local machine when I'm doing just nothing with the app I can see Node crashing due to uncaught PROTOCOL_CONNECTION_LOST even I am listening on error event.

```
{ Error: Connection lost: The server closed the connection.
web_1    |     at Protocol.end (/var/www/html/node_modules/mysql/lib/protocol/Protocol.js:113:13)
web_1    |     at Socket.<anonymous> (/var/www/html/node_modules/mysql/lib/Connection.js:109:28)
web_1    |     at Socket.emit (events.js:185:15)
web_1    |     at endReadableNT (_stream_readable.js:1101:12)
web_1    |     at process._tickCallback (internal/process/next_tick.js:114:19) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }
```

My method for (re)creating the connection:
```javascript
    _recreateConnection() {
        const {
            host, port, user, password, database,
        } = this._config;
        this._connection = mysql.createConnection({
            host,
            port,
            user,
            password,
            database,
            stringifyObjects,
            queryFormat,
            supportBigNumbers: true,
            bigNumberStrings: true,
        });

        this._connection.on("error", (error) => {
            console.error(error.fatal ? "Fatal" : "Unhandled", "MySQL error", error); // @todo better log
            this._recreateConnection();
        });
    }
```

Am I missing something?

**Comment by dougwilson** [comment]
The error event is where it should be emitted. I'm not sure what is happening off hand though. Would you be able to provide the following and we can dig into the issue?

1. Version of Node.js
2. Version of this module
3. Complete code we can run and reproduce the issue
4. Any setup instructions for the code and instructions to see the issue 

Thanks!

**Comment by dzek69** [comment]
It happens with no actual reason for me, but I'm gonna try to prepare something.

In the meantime:
node 9.8.0,
mysql package 2.15.0,
"mysql" server 10.0.34-MariaDB-0ubuntu0.16.04.1,
OS Ubuntu 16.04,

all these packaged into docker container (single container with node and maria), running on Windows  10 (Version 1709 Compilation 16299.309)

**Comment by dougwilson** [comment]
Yea, I just don't know from the code posted how the error would be slipping through unhandled. If you have a better next step for how I can help, let me know :+1:

**Comment by dzek69** [comment]
Update:
I was trying to prepare reproduction repository. According to https://github.com/mysqljs/mysql/issues/1824 to simulate PROTOCOL_CONNECTION_LOST I can setup MySQL server inside separate container and just kill it.

So I prepared two containers based on the same Ubuntu LAMP+node image I'm using while getting into the error described above. One for MySQL (to kill it), one for Node app to test the issue.

I run it. Node app connected to MySQL, then I killed the container... and the error was caught just as expected :(

I've moved back to single container solution and I'm gonna keep this running for few days. It should disconnect within about 3 days as it does usually. Then I'm gonna report if it get caught or not.

If this will work as expected, the error will get caught, then it's probably a weird problem in my application... But this currently sounds like a non-sense as the code presented is the single point of anything related with "mysql" import and error handling is added just after the connection is created and no matter what else is contained within the app - it should catch the error.

**Comment by dougwilson** [comment]
Keep us updated :+1:
