### ISSUE TITLE
process._tickCallback causing application to stop

### ISSUE THREAD

**Issue by yashgt** [mysqljs/mysql#1984]
I had raised this issue on nodejs. They have suggested to raise it against mysql module.
[Issue 19709](https://github.com/nodejs/node/issues/19708)

Version: 9.10.1
Platform: Linux Redhat
Subsystem:
mysql module: 2.15.0

Ever since I migrated from node 4.5 to 9.10.1
I get this error in my application after 2-3 hours and the application stops:
```
events.js:165
throw er; // Unhandled 'error' event
^

Error: Connection lost: The server closed the connection.
at Protocol.end (/home/ec2-user/production/code/admin/node_modules/mysql/lib/protocol/Protocol.js:113:13)
at Socket. (/home/ec2-user/production/code/admin/node_modules/mysql/lib/Connection.js:109:28)
at Socket.emit (events.js:185:15)
at endReadableNT (_stream_readable.js:1106:12)
at process._tickCallback (internal/process/next_tick.js:114:19)
Emitted 'error' event at:
at Connection._handleProtocolError (/home/ec2-user/production/code/admin/node_modules/mysql/lib/Connection.js:433:8)
at Protocol.emit (events.js:180:13)
at Protocol._delegateError (/home/ec2-user/production/code/admin/node_modules/mysql/lib/protocol/Protocol.js:392:10)
at Protocol.end (/home/ec2-user/production/code/admin/node_modules/mysql/lib/protocol/Protocol.js:117:8)
at Socket. (/home/ec2-user/production/code/admin/node_modules/mysql/lib/Connection.js:109:28)
[... lines matching original stack trace ...]
at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by dougwilson** [comment]
Hi @yashgt the error you are getting there is `Connection lost: The server closed the connection`. This error occurs when Node.js emits the event that the remote server has closed the TCP socket before we were finished writing data.

You can handle the error in whatever way you choose (even ignore it), by attaching an `error` listener to your `connection` object. You can find more information regarding handling errors with this module in our error handling documentation section https://github.com/mysqljs/mysql#error-handling 👍

**Comment by yashgt** [comment]
We create connections using a pool. If the connection obtained from the pool is in error, how do we fix that connection? In the below code, the connect function takes a command callback which expects a good connection to be passed to it. This connection comes from a pool. How should I structure my code to handle the error. The documentation at  https://github.com/mysqljs/mysql#error-handling shows only how to log the error and not how to recover. I do not want to report an error. My application should remain always-running and hence should recreate connections that fail.
```
exports.createPool = function createPool(dbConfig)
{
        logger.debug('Creating pool');
        pool = mysql.createPool(dbConfig);
};

exports.connect = function connect(command)
{
        pool.getConnection(     function(err, conn){
                if(!err)
                {
                        conn.on('error', function(err) {
                                logger.error(err); // 'ER_BAD_DB_ERROR'
                        });
                        command(conn);
                }
        });
};
```
