### ISSUE TITLE
when getConnection, an error occured!

### ISSUE THREAD

**Issue by Sailor20** [mysqljs/mysql#2010]
mysql pool getConnection err:  { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect [as _callback] (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at /app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/protocol/Protocol.js:398:18
    at Array.forEach (<anonymous>)
    at /app/yanxuan/tc-nodejs-ser/node_modules/mysql/lib/protocol/Protocol.js:397:13
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }

**Comment by dougwilson** [comment]
That error means the client gave up because your MySQL server did not respond after 10 seconds when trying to connect. You can adjust the timeout using the acquireTimeout pool option.

**Comment by Sailor20** [comment]
Hello, I set the acquireTimeout to 60000, but the error occured again!

**Comment by dougwilson** [comment]
You may need to involve something like Wireshark to see what is happening and why the MySQL server connection is timing out.
