### ISSUE TITLE
Error: Packets out of order. Got: 0 Expected: XXX

### ISSUE THREAD

**Issue by kac-** [mysqljs/mysql#2030]
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 0 Expected: 12
    at Parser.write (/PROJECT/node_modules/mysql/lib/protocol/Parser.js:42:19)
    at Protocol.write (/PROJECT/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/PROJECT/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```

```
Debian       9.4-i386
NodeJS       8.5.0
mysqljs      2.15.0
mysqld       10.1.26-MariaDB
```

Crash occurs when I stop MySQL (MariaDB) service while mysqljs connection (single or from pool) is open, server sends to clients `Connection was killed` error with *Packet Number* set to 0 (zero) what generates fatal error.
![packet decoded by wireshark](https://user-images.githubusercontent.com/604344/40665794-7610f618-635e-11e8-90ab-0129e6fb4691.png)

**Comment by kac-** [comment]
With MariaDB i think the best way to simulate this case in tests is to execute `KILL CONNECTION USER CURRENT_USER()`.
