### ISSUE TITLE
Connecting to online mysql database using nodejs.

### ISSUE THREAD

**Issue by EricOuma** [mysqljs/mysql#2056]
Am building a nodejs app locally but later I'll be hosting it in Heroku. I have a website hosted in cPanel. I am trying to fetch data from the database of the online website but I keep on getting this error:
```
error connecting: Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (E:\Documents\Computer and Coding\PlayGround\PROJECTS\SMSAPI\node_modules\mysql\lib\Connection.js:419:13)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:444:8)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol._enqueue (E:\Documents\Computer and Coding\PlayGround\PROJECTS\SMSAPI\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (E:\Documents\Computer and Coding\PlayGround\PROJECTS\SMSAPI\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at Connection.connect (E:\Documents\Computer and Coding\PlayGround\PROJECTS\SMSAPI\node_modules\mysql\lib\Connection.js:130:18)
    at Object.<anonymous> (E:\Documents\Computer and Coding\PlayGround\PROJECTS\SMSAPI\index.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
(node:11960) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
```
Kindly help me know the appropriate code to perform such connections

**Comment by dougwilson** [comment]
That error means that Node.js is unable to connect to the given host and port and the TCP connection just times out.

**Comment by mqliutie** [comment]
WOW! I deleted all hosts so the error shown.

The error gone when I add  host to `hosts` file
