### ISSUE TITLE
Crashing after running second query in a row.

### ISSUE THREAD

**Issue by AlexanderProd** [mysqljs/mysql#2069]
I'm using the following code to query a mysql table and it works on the first api call using express but as soon as I try another call it crashes. I'm running the latest mysqljs version from this repository. 

```
app.get('/tracks', function (req, res) {
    connection.connect();

    connection.query('SELECT * FROM tracks_posted LIMIT 0, 10', function (error, results, fields) {
      if (error) throw error;
      res.send(results)
    });

    connection.end();
});
```

This is the error code I'm getting:
```
events.js:167
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: Cannot enqueue Handshake after invoking quit.
[0]     at Protocol._validateEnqueue (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/protocol/Protocol.js:203:16)
[0]     at Protocol._enqueue (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/protocol/Protocol.js:138:13)
[0]     at Protocol.handshake (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/protocol/Protocol.js:51:23)
[0]     at Connection.connect (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/Connection.js:118:18)
[0]     at /Users/alexanderhoerl/Developer/react-soundcloud-clone/server.js:18:16
[0]     at Layer.handle [as handle_request] (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/express/lib/router/route.js:137:13)
[0]     at Route.dispatch (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/express/lib/router/route.js:112:3)
[0]     at Layer.handle [as handle_request] (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/express/lib/router/layer.js:95:5)
[0]     at /Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/express/lib/router/index.js:281:22
[0] Emitted 'error' event at:
[0]     at Connection._handleProtocolError (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/Connection.js:425:8)
[0]     at Protocol.emit (events.js:182:13)
[0]     at Protocol._delegateError (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/protocol/Protocol.js:390:10)
[0]     at Handshake.<anonymous> (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/protocol/Protocol.js:220:10)
[0]     at Handshake.emit (events.js:182:13)
[0]     at Handshake.Sequence.end (/Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
[0]     at /Users/alexanderhoerl/Developer/react-soundcloud-clone/node_modules/mysql/lib/protocol/Protocol.js:224:14
[0]     at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by dougwilson** [comment]
Hi @AlexanderProd based on the provided code and error, you're trying to `.connect()` on a `connection` object that has already been ended. You cannot re-open a connection once it is closed. You need to create a new `connection` object.

Simplified example:
```js
app.get('/tracks', function (req, res) {
    var connection = mysql.createConnection(/* your config */);

    connection.query('SELECT * FROM tracks_posted LIMIT 0, 10', function (error, results, fields) {
      if (error) throw error;
      res.send(results)
    });

    connection.end();
});

```
