### ISSUE TITLE
Query inactivity timeout

### ISSUE THREAD

**Issue by behind2** [mysqljs/mysql#2079]
{
  "stack": "Error: Query inactivity timeout\n
      at Query.\u003Canonymous> (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/Protocol.js:164:17)\n
      at Query.emit (events.js:180:13)\n
      at Query.emit (domain.js:440:23)\n
      at Query._onTimeout (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)\n
      at ontimeout (timers.js:466:11)\n
      at tryOnTimeout (timers.js:304:5)\n
      at Timer.listOnTimeout (timers.js:267:5)\n
      --------------------\n
      at Protocol._enqueue (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n
      at PoolConnection.query (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/Connection.js:208:25)\n
      at pool.getConnection (/usr/local/services/nodejs_pilot-1.0/lib/mysql/index.js:105:22)\n
      at Ping.onOperationComplete (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/Pool.js:110:5)\n
      at bound (domain.js:376:14)\n
      at Ping.runBound [as _callback] (domain.js:389:12)\n
      at Ping.Sequence.end (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)\n
      at Ping.Sequence.OkPacket (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)\n
      at Protocol._parsePacket (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n
      at Parser.write (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/Parser.js:76:12)\n
      at Protocol.write (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n
      at Socket.\u003Canonymous> (/usr/local/services/nodejs_pilot-1.0/node_modules/mysql/lib/Connection.js:103:28)\n
      at Socket.emit (events.js:180:13)\n
      at Socket.emit (domain.js:440:23)\n
      at addChunk (_stream_readable.js:274:12)\n
      at readableAddChunk (_stream_readable.js:261:11)",
  "message": "Query inactivity timeout"
}

What does "Query inactivity timeout" mean ? Why causes this question?  How can I resolve it?

**Comment by dougwilson** [comment]
That error should mean that your code did a query and specified a timeout value and the query took longer than that value. Are you passing a timeout in your query?

**Comment by dougwilson** [comment]
Closing due to no response.
