### ISSUE TITLE
DeprecationWarning: timers.enroll() is deprecated

### ISSUE THREAD

**Issue by dragonfriend0013** [mysqljs/mysql#2080]
Updated project to use node 10.8.0, updated mysql npm to 2.16.0.  When starting server i get:
```
(node:5423) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
2018-08-06 12:11:30.922 SpecDesigner WARN Warning issued.  DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.:DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
    at Protocol._startSequence (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:347:12)
    at Protocol._enqueue (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:190:10)
    at Protocol.handshake (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Pool.js:202:8)
    at MySQLStore.query (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/index.js:388:33)
    at MySQLStore.<anonymous> (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/index.js:110:9)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
(node:5423) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
2018-08-06 12:11:30.929 SpecDesigner WARN Warning issued.  DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.:DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
    at Protocol._dequeue (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:325:10)
    at Handshake.<anonymous> (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:161:12)
    at Handshake.emit (events.js:182:13)
    at Handshake.Sequence.end (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/sequences/Sequence.js:91:12)
    at Handshake.Sequence.OkPacket (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
```
Pool is initialized on server startup:
```js
var mysql = require("mysql");

var config = require("./config");
config.connection.password = config.secrets.DBpassword;

var pool = mysql.createPool(config.connection);

pool.query("USE " + config.connection.database);

module.exports = pool;
```

**Comment by dougwilson** [comment]
Thanks for the report! I copied your code into a file and ran with mysql 1.16.0 and Node.js 10.8.0 and there was no deprecation warning. Can you confirm that following the steps below has a deprecation report on your side?

(1) Place the following code into `ex.js`:
```js
var mysql = require("mysql");

var config = {
  connection: { database: 'test' },
  secrets: {}
};
config.connection.password = config.secrets.DBpassword;

var pool = mysql.createPool(config.connection);

pool.query("USE " + config.connection.database);

module.exports = pool;
```

(2) Run `npm install mysql@2.16.0`
(3) verify `node -v` is v10.8.0
(4) Run `node ex.js`

**Comment by dragonfriend0013** [comment]
I can confirm that i am on node V10.8.0,  Running ex.js as listed gave no errors

**Comment by dragonfriend0013** [comment]
my package.json is as follows:

{
  "name": "specdesigner",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node specdesigner.js",
    "start-dev": "node --prof specdesigner.js"
  },
  "dependencies": {
    "async": "^2.6.1",
    "body-parser": "^1.18.3",
    "compression": "^1.7.3",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.3",
    "dateformat": "^3.0.3",
    "debug": "^3.1.0",
    "diff-json": "^0.1.11",
    "ejs": "^2.6.1",
    "express": "^4.16.3",
    "express-breadcrumbs": "^0.0.2",
    "express-fileupload": "^0.4.0",
    "express-mysql-session": "^1.3.0",
    "express-session": "^1.15.6",
    "express-useragent": "^1.0.12",
    "helmet": "^3.13.0",
    "jquery": "^3.3.1",
    "jsdom": "^11.12.0",
    "morgan": "^1.9.0",
    "multer": "^1.3.1",
    "mysql": "^2.16.0",
    "node-unique-array": "^0.0.6",
    "nodemailer": "^4.6.7",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "passport-saml": "^0.33.0",
    "pdfkit": "^0.8.3",
    "pdfmake": "^0.1.37",
    "random-number": "0.0.9",
    "request-ip": "^2.1.1",
    "serve-favicon": "^2.5.0",
    "strftime": "^0.10.0",
    "supports-color": "^5.4.0",
    "underscore": "^1.9.1",
    "unescape": "^1.0.1",
    "uniq": "^1.0.1",
    "winston": "^2.4.3"
  },
  "devDependencies": {}
}

**Comment by dragonfriend0013** [comment]
ok, after further review, it appears that express-mysql-session is locked to mysql version 2.15.*.  I updated that packages mysql version to 2.16.* and did an npm install on that folder and it the app started correctly.  I will get with that project to get it updated to 2.16.  thanks.
