### ISSUE TITLE
Error on usage with tsconfig-paths

### ISSUE THREAD

**Issue by Bessonov** [mysqljs/mysql#2084]
I try to use mysql with ts-node and if I run following command:

```
node --inspect -r tsconfig-paths/register -r ts-node/register ./src/index.ts
```

I get this error:

```
[nodemon] starting `node --inspect -r tsconfig-paths/register -r ts-node/register ./src/index.ts`
Debugger listening on ws://127.0.0.1:9229/b04e6d86-95d7-4be9-9156-e538a5c7d9e9
For help see https://nodejs.org/en/docs/inspector
TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:704:11)
    at Protocol.<anonymous> (/home/developer/frontend/packages/server/node_modules/mysql/lib/Connection.js:88:26)
    at emitOne (events.js:116:13)
    at Protocol.emit (events.js:211:7)
    at Protocol._emitPacket (/home/developer/frontend/packages/server/node_modules/mysql/lib/protocol/Protocol.js:292:8)
    at Handshake.<anonymous> (/home/developer/frontend/packages/server/node_modules/mysql/lib/protocol/Protocol.js:157:12)
    at Handshake.EventEmitter.emit (/home/developer/frontend/packages/server/node_modules/events/events.js:81:17)
    at Handshake._sendCredentials (/home/developer/frontend/packages/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:91:8)
    at Handshake.HandshakeInitializationPacket (/home/developer/frontend/packages/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:81:10)
    at Protocol._parsePacket (/home/developer/frontend/packages/server/node_modules/mysql/lib/protocol/Protocol.js:278:23)
[nodemon] app crashed - waiting for file changes before starting...
```

with the current github version (`npm install mysqljs/mysql`). If i remove `-r tsconfig-paths/register`, then it works as expected.

After downgrade random modules, especially `ts-node`, `tsconfig-paths`, `mysql` and even `mariadb`. I found, that it breaks with mysql#v2.14.0. With bisect I was able to identify the commit: https://github.com/mysqljs/mysql/commit/310c6a7d1b2e14b63b572dbfbfa10128f20c6d52

It's a known issue or should I provide a reproduction?

**Comment by Bessonov** [comment]
Not reproducible with `mysql2`.

**Comment by dougwilson** [comment]
It is not a known issue, no, though that is because you're not using the module in a way that is a part of our test suite :) If you can provide a reproduction that uses as little things as possible on top of this module so we can determine what exactly is causing it that would help a lot.

The commit you bisected to is interesting -- it was our switch to `safe-buffer` to avoid the warnings of the now-deprecated `new Buffer` constructor that provides back-compact. I wonder if ultimately the bug is in the `safe-buffer` lib, though, and just showing through the fact that we're using it.

**Comment by dougwilson** [comment]
I tried to set some stuff up, but it's beyond my knowledge currently :) I just get
```
Couldn't find tsconfig.json. tsconfig-paths will be skipped
```

and everything works fine. My only guess based on the commit you pointed to and the stack trace is that the `Buffer` instance that `safe-buffer` has is not the same instance that Node.js itself has in your set up, so `instanceof` returns false. Can you try and run the following and see what output you get? (you may need to install` safe-buffer` at the top of your `node_modules`):
```
$ node -r tsconfig-paths/register -pe '({buffer:(require("buffer").Buffer===global.Buffer),safe:(require("safe-buffer").Buffer===global.Buffer)})'
```

**Comment by Bessonov** [comment]
Hey @dougwilson thank you for your fast feedback!

After I tried it to reproduce it, I'm not sure that it should or even can be fixed by `mysql` module. [Here is the reproduction example](https://github.com/Bessonov/repro-tsconfig-paths-error).

I use:

```
$ npm -v
5.6.0
$ node -v
v8.11.3
```

Note following:

1. If you run `npm run case1` or `npm run case2` you get error above.
2. There is no error with `npm run case3`, because there is no `tsconfig-paths`.
3. With `npm run case4` you don't get the error. The change is: `typeorm` was removed.
4. With `npm run case5` you get another error. I don't find the relevant difference with my setup, but in my setup I don't get any error.

For me, it seems like the problem is between `typeorm` and `tsconfig-paths`. You can close this issue, if you think that too.
