### ISSUE TITLE
When `pool.getConnection()` it gets an error: Connection acquired from wrong pool

### ISSUE THREAD

**Issue by leizongmin** [mysqljs/mysql#2094]
The error stack:

```text
Error: Connection acquired from wrong pool.
    at Pool.acquireConnection (/data/node/redbang-server/node_modules/mysql/lib/Pool.js:83:11)
    at Pool.getConnection (/data/node/redbang-server/node_modules/mysql/lib/Pool.js:38:10)
    at PoolCluster._getConnection (/data/node/redbang-server/node_modules/mysql/lib/PoolCluster.js:229:13)
    at PoolNamespace.getConnection (/data/node/redbang-server/node_modules/mysql/lib/PoolNamespace.js:40:11)
    at PoolCluster.getConnection (/data/node/redbang-server/node_modules/mysql/lib/PoolCluster.js:145:13)
    at Promise (/data/node/redbang-server/node_modules/@leizm/mysql/src/lib/connection.ts:370:12)
    at new Promise (<anonymous>)
    at Connection._query (/data/node/redbang-server/node_modules/@leizm/mysql/src/lib/connection.ts:368:12)
    at Connection.query (/data/node/redbang-server/node_modules/@leizm/mysql/src/lib/connection.ts:298:17)
    at QueryBuilder.exec [as _execCallback] (/data/node/redbang-server/node_modules/@leizm/mysql/src/lib/table.ts:241:32)
    at Promise (/data/node/redbang-server/node_modules/@leizm/mysql/src/lib/query.ts:615:12)
    at new Promise (<anonymous>)
    at QueryBuilder.exec (/data/node/redbang-server/node_modules/@leizm/mysql/src/lib/query.ts:611:12)
    at Object.findActByUuid (/data/node/redbang-server/src/services/activity.ts:45:6)
    at Object.handler (/data/node/redbang-server/src/controllers/callback/award_code.ts:38:42)
    at /data/node/redbang-server/src/framework/routes.ts:47:16
    at /data/node/redbang-server/node_modules/@leizm/web/src/lib/utils.ts:216:11
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    requestId: "in.1534479304978.9927375415220243"
    code: "UNKNOWN"
    message: "Connection acquired from wrong pool."
```

I try to debug the process, and know the `PoolConnection` instance gets an error **Connection lost: The server closed the connection**. After this connection closed event, `pool.getConnection()` will results an error **Connection acquired from wrong pool**, and if you call `pool.getConnection()` twice, it works right.

The related source code:

```javascript
Pool.prototype.acquireConnection = function acquireConnection(connection, cb) {
  if (connection._pool !== this) {
    throw new Error('Connection acquired from wrong pool.');
  }
  // ...
});
```

I found that `connection._pool = null`, so it throws this error.

**Comment by leizongmin** [comment]
I'am very sorry, it was my faults.  I use such codes to wrap the origin connection:

```javascript
new Proxy(conn);
```

When it was closed by server side, the `Pool` cannot remove this connection instance correctly (because `new Proxy(conn)` and `conn` are not the same object):

```javascript
Pool.prototype._removeConnection = function(connection) {
  connection._pool = null;

  // Remove connection from all connections
  spliceConnection(this._allConnections, connection);

  // Remove connection from free connections
  spliceConnection(this._freeConnections, connection);

  this.releaseConnection(connection);
};

function spliceConnection(array, connection) {
  var index;
  if ((index = array.indexOf(connection)) !== -1) {
    // Remove connection from all connections
    array.splice(index, 1);
  }
}
```
