### ISSUE TITLE
mysqlJS makes the server to crash

### ISSUE THREAD

**Issue by etiennnr** [mysqljs/mysql#2112]
Hello,

I got a problem when I try to send information from my front-end in JSON format. Basically, when I send the request (with fetch) with headers, It automatically sends an OPTIONS request which makes mysqlJS (and my server) crash...

Here is the logs (from Heroku):

```
2018-10-02T22:16:46.710600+00:00 heroku[router]: at=info method=OPTIONS path="/authentication" host=desolate-escarpment-15258.herokuapp.com request_id=e9bcb178-cb6a-42be-bd94-0b34e60f3e8c fwd="173.177.20.77" dyno=web.1 connect=0ms service=8ms status=204 bytes=301 protocol=https
2018-10-02T22:16:46.759403+00:00 app[web.1]: throw err; // Rethrow non-MySQL errors
2018-10-02T22:16:46.759390+00:00 app[web.1]: /app/node_modules/mysql/lib/protocol/Parser.js:80
2018-10-02T22:16:46.759405+00:00 app[web.1]: ^
2018-10-02T22:16:46.759410+00:00 app[web.1]: at Query.db.query (/app/server.js:64:32)
2018-10-02T22:16:46.759407+00:00 app[web.1]:
2018-10-02T22:16:46.759409+00:00 app[web.1]: TypeError: Cannot read property 'password' of undefined
2018-10-02T22:16:46.759417+00:00 app[web.1]: at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
2018-10-02T22:16:46.759413+00:00 app[web.1]: at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
2018-10-02T22:16:46.759415+00:00 app[web.1]: at Query._callback (/app/node_modules/mysql/lib/Connection.js:468:16)
2018-10-02T22:16:46.759422+00:00 app[web.1]: at Query._handleFinalResultPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
2018-10-02T22:16:46.759426+00:00 app[web.1]: at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:278:23)
2018-10-02T22:16:46.759424+00:00 app[web.1]: at Query.EofPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
2018-10-02T22:16:46.759427+00:00 app[web.1]: at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
2018-10-02T22:16:46.759429+00:00 app[web.1]: at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
2018-10-02T22:16:46.759431+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:91:28)
2018-10-02T22:16:46.771457+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/authentication" host=desolate-escarpment-15258.herokuapp.com request_id=8609e296-7bf7-4c7a-bf6d-242287dbeb57 fwd="173.177.20.77" dyno=web.1 connect=0ms service=29ms status=503 bytes=0 protocol=https
2018-10-02T22:16:46.869477+00:00 heroku[web.1]: Process exited with status 1
2018-10-02T22:16:46.887638+00:00 heroku[web.1]: State changed from up to crashed 
```

Here is the code from nodeJS : 
```
var express = require('express');
var app = express();
var cors = require('cors');
var bodyParser = require('body-parser')
var mysql = require("mysql");

//Enabeling all Access-Control-Allow-Origin
app.use(cors());
app.options('*', cors())

var port = process.env.PORT || 5000

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

//omitted mysql connections details

app.post('/authentication', (req, res) **=> {
    email = req.body.username,
    password = req.body.password,
    matching = "false"
    var dbpassword

    sql = "SELECT password FROM users WHERE email = ?";
    db.query(sql, email, (err, result, fields) => {
        if(err) {
            console.error('error query: ' + err.stack)
            return;
        }
        dbpassword = result[0].password;

         if(dbpassword === password){
        matching = "true";
        console.log(dbpassword + " : " + password);
        } 
        res.send({answer: matching});

    });
})

app.listen(port, function(){
    console.log("app running");
})
```

**Comment by dougwilson** [comment]
This is not an error with this module, but an issue with your logic. The error is that you are always expecting the query to return at least one result row but sometimes returns zero results. You need to add a condition when zero results are returned so you don't have an error

**Comment by etiennnr** [comment]
I did not even think about that... Did it and it works!

thanks!
