### ISSUE TITLE
Getting strange "ReferenceError: symbol is not defined at Query."

### ISSUE THREAD

**Issue by tr32** [mysqljs/mysql#2116]
This is how my code looks like:

```
router.post('/save', function(req, res, next) {
	let exchange = {
		name: null, 
		country_code: null
	};
	
	if(validate(req)) {
		...
		let qry = `INSERT INTO tbl_exchange (name, country_code) VALUES ('${exchange.name}', '${exchange.country_code}');`;
		console.log(qry); // -> INSERT INTO tbl_exchange (name, country_code) VALUES ('DAX', 'DE');
		conn.get().query(qry, function (err, result) { ... });
	}
}

```
What is strange about this is that it still works, the insert is done fine but in my log this error occurs anyway. Here is the error log:

```
{
    "error": {},
    "level": "error",
    "message": "uncaughtException: symbol is not defined\nReferenceError: symbol is not defined\n    at Query.<anonymous> (C:\\Dev\\Workspace\\node_dev\\my-app\\routes\\backend.js:143:30)\n    at Query.<anonymous> (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js:502:10)\n    at Query._callback (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js:468:16)\n    at Query.Sequence.end (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:139:8)\n    at Query.OkPacket (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:72:10)\n    at Protocol._parsePacket (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Protocol.js:278:23)\n    at Parser.write (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Parser.js:76:12)\n    at Protocol.write (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js:91:28)",
    "stack": "ReferenceError: symbol is not defined\n    at Query.<anonymous> (C:\\Dev\\Workspace\\node_dev\\my-app\\routes\\backend.js:143:30)\n    at Query.<anonymous> (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js:502:10)\n    at Query._callback (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js:468:16)\n    at Query.Sequence.end (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:139:8)\n    at Query.OkPacket (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:72:10)\n    at Protocol._parsePacket (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Protocol.js:278:23)\n    at Parser.write (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Parser.js:76:12)\n    at Protocol.write (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js:91:28)",
    "exception": true,
    "date": "Thu Oct 11 2018 03:12:32 GMT+0200 (Mitteleuropäische Sommerzeit)",
    "process": {
        "pid": 17284,
        "uid": null,
        "gid": null,
        "cwd": "C:\\Dev\\Workspace\\node_dev\\my-app",
        "execPath": "C:\\Program Files\\nodejs\\node.exe",
        "version": "v8.11.1",
        "argv": ["C:\\Program Files\\nodejs\\node.exe", "C:\\Dev\\Workspace\\node_dev\\my-app\\server"],
        "memoryUsage": {
            "rss": 36618240,
            "heapTotal": 18169856,
            "heapUsed": 14951904,
            "external": 127233
        }
    },
    "os": {
        "loadavg": [0, 0, 0],
        "uptime": 22957.618697
    },
    "trace": [{
        "column": 30,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\routes\\backend.js",
        "function": null,
        "line": 143,
        "method": null,
        "native": false
    }, {
        "column": 10,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js",
        "function": null,
        "line": 502,
        "method": null,
        "native": false
    }, {
        "column": 16,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js",
        "function": "Query._callback",
        "line": 468,
        "method": "_callback",
        "native": false
    }, {
        "column": 24,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js",
        "function": "Query.Sequence.end",
        "line": 83,
        "method": "end",
        "native": false
    }, {
        "column": 8,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js",
        "function": "Query._handleFinalResultPacket",
        "line": 139,
        "method": "_handleFinalResultPacket",
        "native": false
    }, {
        "column": 10,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js",
        "function": "Query.OkPacket",
        "line": 72,
        "method": "OkPacket",
        "native": false
    }, {
        "column": 23,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Protocol.js",
        "function": "Protocol._parsePacket",
        "line": 278,
        "method": "_parsePacket",
        "native": false
    }, {
        "column": 12,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Parser.js",
        "function": "Parser.write",
        "line": 76,
        "method": "write",
        "native": false
    }, {
        "column": 16,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\protocol\\Protocol.js",
        "function": "Protocol.write",
        "line": 38,
        "method": "write",
        "native": false
    }, {
        "column": 28,
        "file": "C:\\Dev\\Workspace\\node_dev\\my-app\\node_modules\\mysql\\lib\\Connection.js",
        "function": null,
        "line": 91,
        "method": null,
        "native": false
    }]
}
```

Using: "mysql": "^2.15.0"
MySQL DB Server-Version: 10.1.31-MariaDB

**Comment by dougwilson** [comment]
What is at line 143 in the file node_dev\\my-app\\routes\\backend.js ?

**Comment by tr32** [comment]
Can be closed, it was a small bug in my own application, thanks @dougwilson !
