### ISSUE TITLE
Error while connecting: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Sv443** [mysqljs/mysql#2118]
I'm sorry to ask such a broad question but I am a beginner in NodeJS and databases but I have to set up a database for my work and I just can't seem to get this to work:

I want to connect to a MySQL database on the server I set up at my house that is running MySQL on port 3306 through XAMPP and I want to connect to it while I'm at work. I tried this code using localhost and it worked so it makes me think there's some sort of firewall problem. The TCP port 3306 on my server is opened correctly and I tried adding and changing users about 20 times with different settings now.

Could the problem be a firewall or port restriction at my office? If so, what would you recommend me to check / do? I don't have any admin rights so I'll have to wait until that person arrives and I can't hold them up for too long. On my server I do have admin rights though.

This is my NodeJS code:
```javascript
var mysql = require('mysql');

var sqlquery = "SELECT * FROM users WHERE id >= 12";



var sqlconnection = mysql.createConnection({
    host: '2.205.169.200',
    port: 3306,
    user: "**********",
    password: "**********",
    database: "learning_over_here"
});


sqlconnection.connect(function(error) {
    if(!!error) {
        console.log("Connection " + error.stack);
        sqlconnection.end();
        return false;
    }
    else {
        console.log("CONNECTED SUCCESSFULLY");
        sendQuery();
        return true;
    }
});

function sendQuery() {
    sqlconnection.query(sqlquery, function(error, rows) {
        if(!!error) {
            console.log("Query " + error.stack);
            sqlconnection.end();
            return false;
        }
        else {
            var result = JSON.stringify(rows, null, 4);
            console.log("QUERY BEGIN -->");
            console.log(result);
            console.log("<-- QUERY END");
            sqlconnection.end();
            return true;
        }
    });
}
```

The error I get:
```
Connection Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (C:\Users\fes\Desktop\Code\node_mysql\node_modules\mysql\lib\Connection.js:411:13)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (C:\Users\fes\Desktop\Code\node_mysql\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\fes\Desktop\Code\node_mysql\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\Users\fes\Desktop\Code\node_mysql\node_modules\mysql\lib\Connection.js:118:18)
    at Object.<anonymous> (C:\Users\fes\Desktop\Code\node_mysql\index.js:24:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

Thanks for any help!

**Comment by Sv443** [comment]
I'm pretty certain it is a firewall problem. You can close the issue.

**Comment by Sv443** [comment]
I'm pretty certain it is a firewall problem. I closed the issue.
