### ISSUE TITLE
How to troubleshoot the PROTOCOL_CONNECTION_LOST problem in the connection pool

### ISSUE THREAD

**Issue by freeacger** [mysqljs/mysql#2122]
I searched for some related issues, but I'm not sure how to fix this in the connection pool. #1268

error：
```
error: { Error: Connection lost: The server closed the connection.
    at Protocol.end (/path/to/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/path/to/node_modules/mysql/lib/Connection.js:97:28)
    at Socket.<anonymous> (/path/to/node_modules/mysql/lib/Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at args.(anonymous function) (/usr/local/node/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
    --------------------
    at Protocol._enqueue (/path/to/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/path/to/node_modules/mysql/lib/Connection.js:200:25)
    at /path/to/src/lib/core/Mysql.js:68:32
    at Ping.onOperationComplete (/path/to/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.<anonymous> (/path/to/node_modules/mysql/lib/Connection.js:502:10)
    at Ping._callback (/path/to/node_modules/mysql/lib/Connection.js:468:16)
    at Ping.Sequence.end (/path/to/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Ping.Sequence.OkPacket (/path/to/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
    at Protocol._parsePacket (/path/to/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/path/to/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/path/to/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/path/to/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/path/to/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }
```

code：

```
    let config = {
        host: config.HOST,
        user: config.USERNAME,
        password: config.PASSWORD,
        database: config.DATABASE,
        port: config.PORT,
        connectionLimit: 100,
    };

    let pool = mysql.createPool(config);

    // ...
    
    query(sql, values) {
        return new Promise((resolve, reject) => {
            pool.getConnection((err, connection) => {
                if (err) {
                    reject(err);
                } else {
                    connection.query(sql, values, (err, rows) => {
                        connection.release();
                        if (err) {
                            reject(err)
                        } else {
                            resolve(rows)
                        }
                    })
                }
            })
        })
    }

    // ...
```

**Comment by freeacger** [comment]
@dougwilson help

**Comment by dougwilson** [comment]
The server closed the connection during your query. I don't think there is any fix for that. Does your query take a long time to run? Have you checked the server logs? Does running the same query for other client like "mysql2" have the same result?

**Comment by freeacger** [comment]
> The server closed the connection during your query. I don't think there is any fix for that. Does your query take a long time to run? Have you checked the server logs? Does running the same query for other client like "mysql2" have the same result?

By asking the database administrator, we know that the database middleware we are using does not support connection pooling.

Thank you for your help.
