### ISSUE TITLE
App crashes execute statement error

### ISSUE THREAD

**Issue by cimit1994** [mysqljs/mysql#2133]
```
insert into test.log_all (`entity`, `content`) values
========================[mysql error] { Error: ER_DATA_TOO_LONG: Data too long for column 'ENTITY' at row 1
    at Query.Sequence._packetToError (E:\cim\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (E:\cim\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\cim\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (E:\cim\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\cim\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\cim\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (E:\cim\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (E:\cim\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (E:\cim\node_modules\mysql\lib\Connection.js:200:25)
    at E:\cim\databases\mysql\mysql-connect.js:90:20
    at Handshake.onConnect (E:\cim\node_modules\mysql\lib\Pool.js:64:7)
    at Handshake.<anonymous> (E:\cim\node_modules\mysql\lib\Connection.js:502:10)
    at Handshake._callback (E:\cim\node_modules\mysql\lib\Connection.js:468:16)
    at Handshake.Sequence.end (E:\cim\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Handshake.Sequence.OkPacket (E:\cim\node_modules\mysql\lib\protocol\sequences\Sequence.js:92:8)
    at Protocol._parsePacket (E:\cim\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (E:\cim\node_modules\mysql\lib\protocol\Parser.js:76:12)
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlMessage: "Data too long for column 'ENTITY' at row 1",
  sqlState: '22001',
  index: 0,
  sql:
   "insert into test.log_all (`entity`, `content`) values ('entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2','content1')" }
E:\cim\node_modules\mysql\lib\protocol\Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

ReferenceError: stament is not defined
    at Query.<anonymous> (E:\cim\databases\mysql\mysql-connect.js:92:52)
    at Query.<anonymous> (E:\cim\node_modules\mysql\lib\Connection.js:502:10)
    at Query._callback (E:\cim\node_modules\mysql\lib\Connection.js:468:16)
    at Query.Sequence.end (E:\cim\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (E:\cim\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
    at Protocol._parsePacket (E:\cim\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (E:\cim\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\cim\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\cim\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (E:\cim\node_modules\mysql\lib\Connection.js:502:10)
[nodemon] app crashed - waiting for file changes before starting...
```

i am using pool connection with the version mysql@2.16.0

Could you recommend help me "how to push this error to error and the app is not crash"

Thank all,
Cimit

**Comment by cimit1994** [comment]
pool.getConnection(function (err, connection) {
        connection.query(statement, function (err, result) {       //this line
            if (err)
                errorCallback('Error stament : ' + stament + ', ERRROR : ' + err);
            console.log('result', result)
        }).on('error', function (err) {
            console.log("========================[mysql error]", err);
            console.log('=================================')
        });;
        connection.on('error', function (err) {
            console.log('err trigger = ', err); // 'ER_BAD_DB_ERROR'
            errorCallback('Error stament : ' + stament + ', ERRROR : ' + err);
        });
    })

**Comment by dougwilson** [comment]
The error is that the variable "stament" in your code was never declared in that file. I don't see it being declared i  what you pasted, either. Where is that variable declared?

**Comment by dougwilson** [comment]
I feel like it's a typo and you just missed a letter in your variable name i.e. the code you have says "stament" but I think you meant to put "statement" (note the missing "te").

**Comment by cimit1994** [comment]
my function :

exports.insertBatch = function (statement, arrValue, callback, errorCallback) {
    keys = statement.substring(statement.indexOf('(') + 1, statement.indexOf(')'));
    keys = keys.replace(/`/g, '').replace(/ /g, '').replace(/'/g, '').split(',')
    lastIdx = statement.lastIndexOf('(');
    let sql = statement.substring(0, lastIdx);
    console.log(sql);
    values = "";
    for (idx in arrValue) {
        values += "(";
        for (j in keys) {
            values += "'" + arrValue[idx][keys[j]] + "'" + ',';
        }
        values = values.substring(0, values.length - 1);
        values += "),";
    }
    values = values.substring(0, values.length - 1);
    statement = sql + values;
    pool.getConnection(function (err, connection) {
        connection.query(statement, function (err, result) {
            if (err)
                errorCallback('Error stament : ' + stament + ', ERRROR : ' + err);
            console.log('result', result)
        }).on('error', function (err) {
            console.log("========================[mysql error]", err);
            console.log('=================================')
        });;
        connection.on('error', function (err) {
            console.log('err trigger = ', err); // 'ER_BAD_DB_ERROR'
            errorCallback('Error stament : ' + stament + ', ERRROR : ' + err);
        });
    })
}


and call test

arrValue = [{ 'entity': 'entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2entity2', 'content': 'content1' }]
            let statement = "insert into test.log_all (`entity`, `content`) values (?,?)"
            exports.insertBatch(statement, arrValue, function (data) {
                console.log(data[0])
            }, function (error) {
                console.log(data)
            })
            connection.release();

**Comment by cimit1994** [comment]
when i set the field "entity" is correct, it is work well,
but when i send test wrong and get exception from MySQL 
=> App crashed

**Comment by dougwilson** [comment]
It's a typo and you just missed a letter in your variable name i.e. the code you have says "stament" but I think you meant to put "statement" (note the missing "te").

**Comment by dougwilson** [comment]
Error is in your own code, not this module: ReferenceError: stament is not defined
at Query. (E:\cim\databases\mysql\mysql-connect.js:92:52)

**Comment by cimit1994** [comment]
ok, let me check again.

Thank you so much

**Comment by kai-koch** [comment]
Besides the typo in the variable name, there is some more from the stack-trace you provided:
>> [mysql error] { Error: ER_DATA_TOO_LONG: Data too long for column 'ENTITY' at row 1

What is the Datatype and length of the Field 'entity'?
The string you want to write is 245 Chars long. Maybe your field 'entity' can not hold 245 chars?

You have 3 error-handlers set, but besides logging the error you do not check, if it is fatal, that could cause effects like your app crashing.

Further more you set an Error-Event-Handler on the query object. I am maybe not uptodate on the methods on ```connection.query```, but AFAIK you can not bind an error handler to the ```.query```-Object.
This could be another cause your app crashes.
Per mysqljs-convention you handle an error in the callback of the query.
```connection.on('error', function (err){}``` is correct and kind of a 'catch all', but not on the query-object, I believe.

One last 'best practice' tip:
You do not escape the values that you write to the DB, that could introduce an SQL-Attack to your app.
You do some Regex and String "magic" to bring your values into one statement in the form of
```SQL
insert into test.log_all (`entity`, `content`) values ("ent1","cont1"), ("ent2","cont2"), ("ent3","cont3")"
```
BUT you do not escape the values. You might want to rewrite your code to escape values.
One possible way you can see at https://github.com/kai-koch/osm_to_mysql_dump/blob/master/lib/osm_processing.js
It is not the only way to write queries in the way you intend to and surley not the best, but it escapes the value and is abstract enough to escape and write the queries with just a little adjustments for your usecase. I hope the code-documentaton is enough to provide you with enough input to get the hang of it. (Maybe run it with a small OpenStreetMap-file to get the hang of it.)
