### ISSUE TITLE
Parse Error when inserting records into tables in many-to-many relationship

### ISSUE THREAD

**Issue by hubitor** [mysqljs/mysql#2137]
For this query:

```
var query3 = `START TRANSACTION;
INSERT INTO permissions(name) VALUES('A Permission');
SET @last_permission_id = LAST_INSERT_ID();
SET @user_id = (SELECT id FROM users WHERE last_name LIKE '%Smith%');
INSERT INTO user_permission (user_id, permission_id) VALUES (@user_id, @last_permission_id);
COMMIT;`

connection.query(query3, function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});
```

I'm getting this error:

```
$ node src/index.js
/home/user/workspace/node.js/test01/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO permissions(name) VALUES('Something20');
SET @last_permission_id = L' at line 2
    at Query.Sequence._packetToError (/home/user/workspace/node.js/test01/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/user/workspace/node.js/test01/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/user/workspace/node.js/test01/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/user/workspace/node.js/test01/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/user/workspace/node.js/test01/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/user/workspace/node.js/test01/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/user/workspace/node.js/test01/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    --------------------
    at Protocol._enqueue (/home/user/workspace/node.js/test01/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/user/workspace/node.js/test01/node_modules/mysql/lib/Connection.js:200:25)
    at Object.<anonymous> (/home/user/workspace/node.js/test01/src/index.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
```

Is it because something is not supported? If yes, is there another way of doing it?

(Actually I'm using mysql with Knex and I've reported the issue here:
[https://github.com/tgriesser/knex/issues/2922#event-1980513052](url))

**Comment by dougwilson** [comment]
Because your query contained multiple statements, you need to enable multiple statements when you connect to the server. https://github.com/mysqljs/mysql#connection-options

Example: `conn = mysql.createConnection({ multipleStatements: true })`

See also https://github.com/mysqljs/mysql#multiple-statement-queries
