### ISSUE TITLE
Question: How to use with Sequelize.js v4

### ISSUE THREAD

**Issue by adonespitogo** [mysqljs/mysql#2148]
Hi,

I've read in the issues discussions about sequelize, I suppose this can be used with sequelize instaead of `mysql2`. But how?

When I try to run sequelize, i get this error:
```
Error: Please install mysql2 package manually
    at new ConnectionManager (/home/adonesp/Projects/espressowifi/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:38:15)
    at new MysqlDialect (/home/adonesp/Projects/espressowifi/node_modules/sequelize/lib/dialects/mysql/index.js:14:30)
    at new Sequelize (/home/adonesp/Projects/espressowifi/node_modules/sequelize/lib/sequelize.js:239:20)
    at read_config.read.then.cfg (/home/adonesp/Projects/espressowifi/piso-wifi.js:5916:20)
    at _fulfilled (/home/adonesp/Projects/espressowifi/node_modules/q/q.js:854:54)
    at /home/adonesp/Projects/espressowifi/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/adonesp/Projects/espressowifi/node_modules/q/q.js:816:13)
    at /home/adonesp/Projects/espressowifi/node_modules/q/q.js:877:14
    at runSingle (/home/adonesp/Projects/espressowifi/node_modules/q/q.js:137:13)
    at flush (/home/adonesp/Projects/espressowifi/node_modules/q/q.js:125:13)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

My sequelize config:

```
{
  host: '127.0.0.1',
  dialect: 'mysql',
  operatorAliases: false,
  pool: { max: 5, min: 0, acquire: 30000, idle: 10000 } 
}
```

**Comment by adonespitogo** [comment]
Ok, I just fount out `mysql2` is now free of native bindings, which is what I need. Thanks
