### ISSUE TITLE
Error: Packets out of order. Got: 83 Expected: 1

### ISSUE THREAD

**Issue by ChristopherBThai** [mysqljs/mysql#2179]
```
{ Error: Packets out of order. Got: 83 Expected: 1
     at Parser.write (/home/chris/.nvm/versions/node/v11.9.0/lib/node_modules/mysql/lib/protocol/Parser.js:42:19)
     at Protocol.write (/home/chris/.nvm/versions/node/v11.9.0/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
     at Socket.<anonymous> (/home/chris/.nvm/versions/node/v11.9.0/lib/node_modules/mysql/lib/Connection.js:91:28)
     at Socket.<anonymous> (/home/chris/.nvm/versions/node/v11.9.0/lib/node_modules/mysql/lib/Connection.js:502:10)
     at Socket.emit (events.js:197:13)
     at addChunk (_stream_readable.js:288:12)
     at readableAddChunk (_stream_readable.js:269:11)
     at Socket.Readable.push (_stream_readable.js:224:10)
     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
     --------------------
     at Protocol._enqueue (/home/chris/.nvm/versions/node/v11.9.0/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
     at Connection.query (/home/chris/.nvm/versions/node/v11.9.0/lib/node_modules/mysql/lib/Connection.js:200:25)
     at CommandInterface.execute (/home/chris/owo/methods/command/zoo/lootbox.js:39:9)
     at processTicksAndRejections (internal/process/next_tick.js:81:5) code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }
```
Can anybody help me with this issue?

Nodejs v11.9.0
MySQL Ver 15.1 Distrib 10.3.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
mysqljs v 2.16.0

**Comment by marcus-hiles** [comment]
@ChristopherBThai which line of code gives you this error please?

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by dresende** [comment]
This has happened to me using a MariaDB Galera Cluster on a Docker Swarm. I'm not sure what it was. We'll need to investigate later on. In the meantime, I'm abandoning MariaDB.

**Comment by dresende** [comment]
From what I collected from other issues here and other projects, it seems to be a shutdown packet from MariaDB that has an unexpected packet number.
