### ISSUE TITLE
Streaming directly on pool causes exception when closing pool later

### ISSUE THREAD

**Issue by 125m125** [mysqljs/mysql#2180]
When streaming the resulting rows directly on a pool without requesting a connection and then trying to close the pool causes an exception. 

Example code (each block was executed without the others)
```javascript
var mysql = require("mysql");
var db = mysql.createPool({
        host: "localhost",
        user: "test",
        password: "test",
        database: "test",
    });

// this works
db.query("SELECT CURRENT_TIMESTAMP,?,SLEEP(1)", [true], (err,res) => {
        console.log(err,res);
        db.end();
});

// this works
db.getConnection((err, con) => {
        con.query("SELECT CURRENT_TIMESTAMP,?,SLEEP(1)", [true])
            .on("result", console.log)
            .on("end", () => {
                con.release();
                db.end();
        });
});

// this throws exception (with or without timeout)
db.query("SELECT CURRENT_TIMESTAMP,?,SLEEP(1)", [true])
    .on("result", console.log)
    .on("end", () => setTimeout(db.end, 1000));
```

Exception:
```javascript
/home/.../tmp/test/node_modules/.registry.npmjs.org/mysql/2.16.0/node_modules/mysql/lib/Pool.js:180
  while (this._allConnections.length !== 0) {
                              ^

TypeError: Cannot read property 'length' of undefined
    at Timeout.Pool.end [as _onTimeout] (/home/.../tmp/test/node_modules/.registry.npmjs.org/mysql/2.16.0/node_modules/mysql/lib/Pool.js:180:31)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

node: v10.15.1
mysql (library): 2.16.0
mysql (server): 5.7.25-0ubuntu0.16.04.2
os: ubuntu 16.04

**Comment by dougwilson** [comment]
Hi @125m125 ! So the issue here is how you are using `setTimeout`. In JavaScript, your `db.end` there is a reference to the `.end` function and `setTimeout` will not call it as a method. There are two ways to write that such that `.end` is called as a method:

1. `setTimeout(() => db.end(), 1000)`
2. `setTImeout(db.end.bind(db), 1000)`

I hope that helps!

**Comment by 125m125** [comment]
That was indeed my mistake. Thanks a lot.
