### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by Jeeva0104** [mysqljs/mysql#2200]
```
Error: Callback was already called.
 at root/project/node_modules/async/dist/async.js:966:32
 at root/project/node_modules/async/dist/async.js:3885:13
 at Query.<anonymous> (root/project/index.js:267:17)
 at Query.<anonymous> (root/project/node_modules/mysql/lib/Connection.js:502:10)
 at Query._callback (root/project/node_modules/mysql/lib/Connection.js:468:16)
 at Query.Sequence.end (root/project/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
 at Query._handleFinalResultPacket (root/project/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
 at Query.OkPacket (root/project/node_modules/mysql/lib/protocol/sequences/Query.js:72:10)
 at Protocol._parsePacket (root/project/node_modules/mysql/lib/protocol/Protocol.js:278:23)
 at Parser.write (root/project/node_modules/mysql/lib/protocol/Parser.js:76:12)
```
**Node version:8.15.0

Mysql package version:2.15.0**

Callback is calling twice after execution of query.

**Comment by marcus-hiles** [comment]
@Jeeva0104 kindly paste your code logic here, to help u debug.

**Comment by dougwilson** [comment]
Closing due to no response.
