### ISSUE TITLE
Mysqljs does not catch error after invalid SQL.

### ISSUE THREAD

**Issue by Keydex** [mysqljs/mysql#2208]
Hello,

I have been trying to determine why my nodejs/express/mysqljs application is not catching errors on broken sql queries and proceeds to crash the node process. I'm not sure if it's mysqljs that is the issue

**Dependencies:**

    Using node version `10.15.3`
      "dependencies": {
        "body-parser": "^1.18.3",
        "dotenv": "^7.0.0",
        "express": "^4.16.4",
        "mailcomposer": "^4.0.2",
        "mailgun-js": "^0.22.0",
        "mysql": "^2.16.0",
        "promise-mysql": "^3.3.1"
      }

When purposefully breaking a sql query, **I should expect** node to throw an error and resume operation as normal. Here is the code snippet.

    app.get('/v1/breakNode', function (req, res) {
      let broken_Query = 'INSERT INTO testdb.testtable (product) VALUES ("Morethanone","Value")'
      connection.query(broken_Query, function (err, rows, fields) {
        if (err) {
          throw err
          res.status(500).send(err)
        }
        res.status(200).send({"message":"Data Retrieved Successfully","data":rows})
      })
    })

**But,** the server then returns nothing and crashes with the following error message

    /Users/anthony/work/serviceCall/node_modules/mysql/lib/protocol/Parser.js:80
            throw err; // Rethrow non-MySQL errors
            ^
    
    Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
        at Query.Sequence._packetToError (/Users/anthony/work/serviceCall/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
        at Query.ErrorPacket (/Users/anthony/work/serviceCall/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
        at Protocol._parsePacket (/Users/anthony/work/serviceCall/node_modules/mysql/lib/protocol/Protocol.js:278:23)
        at Parser.write (/Users/anthony/work/serviceCall/node_modules/mysql/lib/protocol/Parser.js:76:12)
        at Protocol.write (/Users/anthony/work/serviceCall/node_modules/mysql/lib/protocol/Protocol.js:38:16)
        at Socket.<anonymous> (/Users/anthony/work/serviceCall/node_modules/mysql/lib/Connection.js:91:28)
        at Socket.<anonymous> (/Users/anthony/work/serviceCall/node_modules/mysql/lib/Connection.js:502:10)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        --------------------
        at Protocol._enqueue (/Users/anthony/work/serviceCall/node_modules/mysql/lib/protocol/Protocol.js:144:48)
        at Connection.query (/Users/anthony/work/serviceCall/node_modules/mysql/lib/Connection.js:200:25)
        at /Users/anthony/work/serviceCall/index.js:208:14
        at Layer.handle [as handle_request] (/Users/anthony/work/serviceCall/node_modules/express/lib/router/layer.js:95:5)
        at next (/Users/anthony/work/serviceCall/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/Users/anthony/work/serviceCall/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/Users/anthony/work/serviceCall/node_modules/express/lib/router/layer.js:95:5)
        at /Users/anthony/work/serviceCall/node_modules/express/lib/router/index.js:281:22
        at Function.process_params (/Users/anthony/work/serviceCall/node_modules/express/lib/router/index.js:335:12)
        at next (/Users/anthony/work/serviceCall/node_modules/express/lib/router/index.js:275:10)

However, if I do something different such as pass in an undefined variable to the connection.query **broken_Query1**

    app.get('/v1/breakNode', function (req, res) {
      let broken_Query = 'INSERT INTO testdb.testtable (product) VALUES ("Morethanone","Value")'
      connection.query(broken_Query1, function (err, rows, fields) {
        if (err) {
          throw err
          res.status(500).send(err)
        }
        res.status(200).send({"message":"Data Retrieved Successfully","data":rows})
      })
    })

Node prints out the error, **however it still continues to run**

    ReferenceError: broken_Query1 is not defined
        at /Users/anthony/work/serviceCall/index.js:208:20
        at Layer.handle [as handle_request] (/Users/anthony/work/serviceCall/node_modules/express/lib/router/layer.js:95:5)
        at next (/Users/anthony/work/serviceCall/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/Users/anthony/work/serviceCall/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/Users/anthony/work/serviceCall/node_modules/express/lib/router/layer.js:95:5)
        at /Users/anthony/work/serviceCall/node_modules/express/lib/router/index.js:281:22
        at Function.process_params (/Users/anthony/work/serviceCall/node_modules/express/lib/router/index.js:335:12)
        at next (/Users/anthony/work/serviceCall/node_modules/express/lib/router/index.js:275:10)
        at jsonParser (/Users/anthony/work/serviceCall/node_modules/body-parser/lib/types/json.js:110:7)
        at Layer.handle [as handle_request] (/Users/anthony/work/serviceCall/node_modules/express/lib/router/layer.js:95:5)

It also successfully returns an Internal Server Error of 500. 

I understand this is the difference between having serverside error vs data base errors, but I would assume it could catch it. Try catch does not work.

**Comment by dougwilson** [comment]
This is a limitation of async callbacks in Node.js. When you `throw err` in your query callback, it is uncatchable.

Here is an example of this in action:
```js
function doQuery(callback) {
  setTimeout(callback, 10)
}

try {
  doQuery(function () {
    throw new Error('test')
    console.log('here')
  })
} catch (e) {
  console.log('caught: ' + e)
}
```

The above will print neither `console.log`.

**Comment by dougwilson** [comment]
Node.js has an overview of how errors work and are propagated here: https://nodejs.org/dist/latest-v10.x/docs/api/errors.html#errors_error_propagation_and_interception

**Comment by Keydex** [comment]
@dougwilson I've been trying to figure this out for hours thank you! You put it in a way that made sense. I wasn't aware that when you throw an error it forces the application to crash, I thought it was just a convenient way to log an error out to console.

**Comment by dougwilson** [comment]
It's no problem :) Express also provides a simplistic mechanism to just write out an error as well, with the `next` argument:
```js
app.get('/v1/breakNode', function (req, res, next) {
  let broken_Query = 'INSERT INTO testdb.testtable (product) VALUES ("Morethanone","Value")'
  connection.query(broken_Query, function (err, rows, fields) {
    if (err) {
      next(err)
    } else {
      res.status(200).send({"message":"Data Retrieved Successfully","data":rows})
    }
  })
})
```
