### ISSUE TITLE
error handling with callback

### ISSUE THREAD

**Issue by prashantnirgun** [mysqljs/mysql#2229]
I am new to express.js I have callback but the query is failed it is giving error . I purposely made mistatake to check the error handling
```
(node:6631) UnhandledPromiseRejectionWarning: Error: ER_BAD_FIELD_ERROR: Unknown column 'name2' in 'field list'
    at Query.Sequence._packetToError (/home/prashant/www/mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/prashant/www/mysql/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/prashant/www/mysql/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/prashant/www/mysql/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/prashant/www/mysql/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/prashant/www/mysql/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/prashant/www/mysql/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/prashant/www/mysql/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Pool.query (/home/prashant/www/mysql/node_modules/mysql/lib/Pool.js:199:23)
    at Pool.query (internal/util.js:230:26)
    at Object.get2 (/home/prashant/www/mysql/models/index.js:58:8)
    at app.get (/home/prashant/www/mysql/routes/api.js:64:13)
    at Layer.handle [as handle_request] (/home/prashant/www/mysql/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/prashant/www/mysql/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/prashant/www/mysql/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/prashant/www/mysql/node_modules/express/lib/router/layer.js:95:5)
    at /home/prashant/www/mysql/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/prashant/www/mysql/node_modules/express/lib/router/index.js:335:12)
(node:6631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6631) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
::1 - - [09/Jun/2019:13:26:18 +0000] "GET /api/posts1 HTTP/1.1" - - "-" "-"
```

database.js 
```js
const mysql = require("mysql");
const util = require("util");

var pool = mysql.createPool({
  connectionLimit: 100, //important
  host: "162.241.175.189",
  user: "airport",
  password: "S0jm%m00",
  database: "tssnetin_airport_production",
  debug: false,
  multipleStatements: true
});
pool.query = util.promisify(pool.query); 
module.exports = pool;
```
router.js
```js
app.get("/api/posts1", (req, res) => {
    try {
      console.log("before get2");
      let opt = {
        table: "member",
        columns: "id, name2, city_id",
        limit: 10,
        verbose: true
      };
      model.get2(opt, result => {
        res.send(result);
      });
    } catch (error) {
      //console.log("GET /api/posts error", error);
      //res.status(401).send("error in endpoint");
    }
  });
```

model.js
```js
get2(params, callback) {
    let sql = `SELECT ${params.columns ? params.columns : "*"} FROM ${
      params.table
    }${params.where ? " WHERE " + params.where : ""}${
      typeof params.soft_delete === "undefined" || params.soft_delete
        ? (!!params.where ? " AND" : " WHERE") + " deleted_by_user_id > 0"
        : ""
    }${params.group_by ? " GROUP BY " + params.group_by : ""}${
      params.order_by ? " ORDER BY " + params.order_by : ""
    }${params.limit > 0 ? " LIMIT " + params.limit : ""}${
      params.limit > 0 && params.offset > 0 ? ", " + params.offset : ""
    }`;
    pool
      .query(sql)
      .then(result => {
        if (params.verbose) {
          output = { data: result, sql };
        } else {
          output = { data: result };
        }

        callback(output);
      })
      .catch(error => {
        console.log("error inside get2", error);
        throw error;
      });
  }
};
```

**Comment by dougwilson** [comment]
Hi @prashantnirgun this error you're seeing is due to the mixing of callbacks and promises and how you are handling errors. The best way to clean up the above is probably just to change your `get2` to use a Node.js-style callback (https://nodejs.org/dist/latest-v10.x/docs/api/errors.html#errors_error_first_callbacks) and then handle that error in your `get2` callback:

router.js
```js
app.get("/api/posts1", (req, res) => {
    console.log("before get2");
    let opt = {
      table: "member",
      columns: "id, name2, city_id",
      limit: 10,
      verbose: true
    };
    model.get2(opt, (error, result) => {
      if (error) {
        console.log("GET /api/posts error", error);
        res.status(401).send("error in endpoint");
      } else {
        res.send(result);
      }
    });
  });
```

model.js
```js
get2(params, callback) {
    let sql = `SELECT ${params.columns ? params.columns : "*"} FROM ${
      params.table
    }${params.where ? " WHERE " + params.where : ""}${
      typeof params.soft_delete === "undefined" || params.soft_delete
        ? (!!params.where ? " AND" : " WHERE") + " deleted_by_user_id > 0"
        : ""
    }${params.group_by ? " GROUP BY " + params.group_by : ""}${
      params.order_by ? " ORDER BY " + params.order_by : ""
    }${params.limit > 0 ? " LIMIT " + params.limit : ""}${
      params.limit > 0 && params.offset > 0 ? ", " + params.offset : ""
    }`;
    pool
      .query(sql)
      .then(result => {
        if (params.verbose) {
          output = { data: result, sql };
        } else {
          output = { data: result };
        }

        callback(null, output);
      })
      .catch(error => {
        console.log("error inside get2", error);
        callback(error);
      });
  }
};
```

**Comment by prashantnirgun** [comment]
great just had one more quetion I want to handle the mysql error using a standard error handler throughout the app. I want to print error message on console and latter in log file. I want to write the error handler inside databse.js file
`const mysql = require("mysql");
const util = require("util");

var pool = mysql.createPool({
  connectionLimit: 100, //important
  host: "162.241.175.189",
  user: "airport",
  password: "S0jm%m00",
  database: "tssnetin_airport_production",
  debug: false,
  multipleStatements: true
});

pool.query = util.promisify(pool.query); // Magic happens here.

pool.sqlErrorHandler = function(error) {
  console.log("**************Database Error Stack Begin****************");
  console.log("error.code", error.code);
  console.log("error.errno", error.errno);
  console.log("error.sql", error.sql);
  console.log("error.sqlState", error.sqlState);
  console.log("error.sqlMessage", error.sqlMessage);
  console.log("**************Database Error Stack End****************");
};

module.exports = pool;`

This is throwing error directly inside browser 500 Internal Server Error
