### ISSUE TITLE
Error: getaddrinfo ENOTFOUND when trying to connect to remote database with correct credentials

### ISSUE THREAD

**Issue by gfcf14** [mysqljs/mysql#2239]
Hi. I'm trying to implement express in my react application to access my database tables and for that I came across this package. I implemented a `server` folder (which starts along with the `yarn start` script via `concurrently` and `nodemon`) with `index.js` like this:
```
const express = require('express');
const mysql = require('mysql');

const app = express();

const con = mysql.createConnection({
  host: 'xxxxx',
  user: 'xxxxx',
  password: 'xxxxx',
  database: 'xxxxx',
});

con.connect( err => {
  if (err) {
    console.log(err);
  }
})

app.get('/api/fetch-list', (req, res) => {
  // code to fetch
});

const PORT = 3001;// process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log(`App server now listening on port ${PORT}`);
});
```
Then, the route/path `/api/fetch-list` gets called in this component:
```
import React from 'react';
import axios from 'axios';

function renderTable() {
  axios.get(`${process.env.PUBLIC_URL}/api/fetch-list`).then(res => {
    console.log(res.data);
  });
}

export function component() {
  return (
    <div>
      {renderTable()}
    </div>
  );
}
```
And this component is rendered once I go to `http:localhost:3000/table`. So once I run the project and go to that address, I get the following error in the terminal console:
```
{ Error: getaddrinfo ENOTFOUND xxxxx xxxxx:3306
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
    --------------------
    at Protocol._enqueue (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/Connection.js:119:18)
    at Object.<anonymous> (/home/gfcf14/Desktop/greendream-redesign/src/server/index.js:27:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'xxxxx',
  host: 'xxxxx',
  port: 3306,
  fatal: true }
```
I'm not certain why this could be happening. I know the credentials I use are correct given that this works on my website on old php code. For a moment I thought this may have to do with where my db is, as I have it hosted on 1&1 (ionos) and they don't grant me a dedicated server. So I changed the credentials to a gearhost space where I have another database (the credentials of which I still use) and I get this error instead:
```

{ Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xxxxx'@'myipaddress' (using password: YES)
    at Handshake.Sequence._packetToError (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/gfcf14/Desktop/greendream-redesign/node_modules/mysql/lib/Connection.js:119:18)
    at Object.<anonymous> (/home/gfcf14/Desktop/greendream-redesign/src/server/index.js:27:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: 'Access denied for user \'xxxxx\'@\'myipaddress\' (using password: YES)',
  sqlState: '28000',
  fatal: true }
```
So it doesn't work for that one either. I might have to check the permissions for that site (which at simple sight seem to be `READ & WRITE`), but how could I get the connection for the first database to work? Please let me know if you see something I may have missed

**Comment by dougwilson** [comment]
The `ENOTFOUND` is an error coming from Node.js DNS lookup routine (https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback). According to their docs:

> Keep in mind that err.code will be set to 'ENOTFOUND' not only when the hostname does not exist but also when the lookup fails in other ways such as no available file descriptors.

So it sounds like the issue is that the DNS lookup is failing for `xxxxx` on your system. That is likely something outside of what this module would be able to help. Can you do a `nslookup xxxxx` on that machine and see what the result is?

**Comment by gfcf14** [comment]
Mmm. For the 1&1 db I get this on Linux Mint's terminal:
```
Server:         127.0.1.1
Address:        127.0.1.1#53

** server can't find xxxxx: NXDOMAIN
```
And on Windows 10 I get:
```
*** Can't find address for server xxxxx: Non-existent domain 
```
Now, for the Gearhost db I get this on linux:
```
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	xxxxx
Address: xxxxx
```
And on windows:
```
Server:  xxxxx
Address:  xxxxx

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to xxxxx timed-out
```
`NXDOMAIN` means non-existent right? If this is the case then why would I still get my tables on my website? (for example [here](https://www.greendreampg.com/programs.php) )

**Comment by dougwilson** [comment]
Yea, NXDOMAIN is the nslookup equivalent of ENOTFOUND in Node.js. Without access to your systems I'm not sure I can answer that question, as I have no idea how that is set up, etc. I can just help with the information presented so far.

**Comment by gfcf14** [comment]
@dougwilson Is there a way I could provide this info to you, like in a personal message?

**Comment by dougwilson** [comment]
You could, but this is just open source software provided as a best effort. I may not really have time to access your systems and diagnose it for free, though maybe others may. Can you put the IP address as the `host` parameter to see if it works by avoiding the DNS lookup that Node.js is doing?

**Comment by gfcf14** [comment]
@dougwilson I understand. I tried changing `host` to `127.0.1.1` and I get a `ECONNREFUSED`

**Comment by gfcf14** [comment]
@dougwilson That's the one I got from the `nslookup`:
```
Server:         127.0.1.1
Address:        127.0.1.1#53

** server can't find xxxxx: NXDOMAIN
```
Maybe that's not the right one? It looks like the one for `localhost` but understandably different since I ran this on a virtual machine

**Comment by dougwilson** [comment]
That IP printed from nslookup is the IP address of the DNS server, not the MySQL server. The MySQL server IP was not found, hence the NXDOMAIN response.

**Comment by gfcf14** [comment]
I'm closing this because it is possible that the database gets a NXDOMAIN on ipconfig because it is configured to only work inside the provider domain, and nowhere else
