### ISSUE TITLE
Microsoft SQL server

### ISSUE THREAD

**Issue by CrazyAlien1** [mysqljs/mysql#2256]
Is there adicional configuration to connect to a Microsoft SQL server?
I'm using this configuration:

```js
const mc = mysql.createConnection({
    host: 'AnIP',
    user: 'user',
    password: 'user',
    database: 'mydatabase',
    port: 1433,
    connectTimeout: 3000
});
```

I've managed to connect with a different package mssql: https://www.npmjs.com/package/mssql
But with this library I'm getting this error:

```
error connecting: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
    --------------------
    at Protocol._enqueue (C:\Users\myself\Desktop\Pub\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\myself\Desktop\Pub\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\Users\myself\Desktop\Pub\node_modules\mysql\lib\Connection.js:119:18)
    at Object.<anonymous> (C:\Users\myself\Desktop\Pub\index.js:27:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
Reached
error:  { Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
    --------------------
    at Protocol._enqueue (C:\Users\myself\Desktop\Pub\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\myself\Desktop\Pub\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\Users\myself\Desktop\Pub\node_modules\mysql\lib\Connection.js:119:18)
    at Object.<anonymous> (C:\Users\myself\Desktop\Pub\index.js:27:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true }
```

**Comment by ZJONSSON** [comment]
This library only connects to mysql servers.  If you want to connect to mssql you can use [mssql](https://www.npmjs.com/package/mssql) or [tedious](https://www.npmjs.com/package/tedious)  (or alternatively use mysql as a database instead of mssql)
