### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError

### ISSUE THREAD

**Issue by Wurstfach404** [mysqljs/mysql#2293]
Hey, I want to get playerData from every of my SteamID's stored in the db.
I have to wait inbetween the requests, otherwise I don't get all the data I want.

Never did anything with js before and someone told me I should try it with promises.
So I ran into this and have no clue what I have do now and what I did wrong...

Error: 
```
...
GC Session available
(node:13002) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'query' of undefined
    at /root/node_modules/csgobot/index2.js:99:35
    at Ping.onOperationComplete (/root/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.<anonymous> (/root/node_modules/mysql/lib/Connection.js:526:10)
    at Ping._callback (/root/node_modules/mysql/lib/Connection.js:488:16)
    at Ping.Sequence.end (/root/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Ping.Sequence.OkPacket (/root/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
    at Protocol._parsePacket (/root/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/root/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/root/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/root/node_modules/mysql/lib/protocol/Protocol.js:38:16)
(node:13002) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13002) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
And thats a bit of my current code:

```
function getRequestPlayer(account_id) {
  return new Promise((resolve, reject) => {
    csgo.requestPlayersProfile(account_id, function (ranking) {
      console.log(ranking);
      resolve(ranking);
    });
  });
}


csgo.on("connectedToGC", async function () {
  console.log("connectedToGC");
  // Check connection to game coordinator
  if (csgo.haveGCSession) {
    console.log("GC Session available");
    // Check Database
    const connection = await pool.getConnection(async function (err){
      if (err) throw err;
    const rows = await connection.query("SELECT * FROM Users WHERE (MainSteamGroup = '1' || CommunitySteamGroup = '1' || vip = '1') && Friendlist = '1'");
    await Promise.all(rows.map(row => {
      console.log("rows");
      const account_id = new SteamID(`${row.SteamID64}`);
      return getRequestPlayer(account_id);
    }));
    });
  };
});
```

I also tried to add an setInterval to loop everything but it seems, that this doesn't work either...

**Comment by dougwilson** [comment]
Hello and sorry you are having problems. This module you cannot `await` the result of `pool.getConnection` for the connection object, which is what ultimately leads to your error. You can read more on the API at https://github.com/mysqljs/mysql#pooling-connections
