### ISSUE TITLE
on docker run mysql，it turns Error: read ECONNRESET

### ISSUE THREAD

**Issue by roy2651** [mysqljs/mysql#2315]
"mysql": “2.18.1”
node verison : 7.9
when I npm run start ：
it turns error:
```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:581:26)
    --------------------
    at Protocol._enqueue (/usr/local/tm.managementstudio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/local/tm.managementstudio/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/usr/local/tm.managementstudio/server/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/usr/local/tm.managementstudio/server/node_modules/mysql/lib/Pool.js:48:16)
    at Promise (/usr/local/tm.managementstudio/server/service/hyperspaceDB.js:42:14)
    at Function.run (/usr/local/tm.managementstudio/server/service/hyperspaceDB.js:41:12)
    at Function.Inter_PublicExecute (/usr/local/tm.managementstudio/server/service/hyperspaceDB.js:16:26)
    at Function.getGroups (/usr/local/tm.managementstudio/server/service/internet/index.js:245:41)
    at router.get (/usr/local/tm.managementstudio/server/routes/api/internet.js:147:19)
    at Layer.handle [as handle_request] (/usr/local/tm.managementstudio/server/node_modules/express/lib/router/layer.js:95:5)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
```

**Comment by roy2651** [comment]
what's this problem？

**Comment by ryan-sandy** [comment]
Sounds like you cannot connect. Is your docker container configured properly? Can the container access the internet?

**Comment by roy2651** [comment]
I telnet on my docker on my mysql database ip+port，it's ok

**Comment by roy2651** [comment]
![image](https://user-images.githubusercontent.com/14157170/76286433-210cc180-62dd-11ea-9706-bc3a40fed788.png)

**Comment by roy2651** [comment]
I have changed my node on docker to v12.13

**Comment by dougwilson** [comment]
I'm sorry, but this is beyond the scope of this issue tracker. If Node.js cannot connect to your server, there is either something blocking the port, or an issue with Node.js itself.
