### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by loretoparisi** [mysqljs/mysql#2324]
I'm getting a connection timeout even if I put a high timeout error:

```javascript
// defaults
            this._options = {
                host     : '',
                user     : '',
                password : '',
                database : '',
                // The milliseconds before a timeout occurs during the initial connection to the MySQL server
                connectTimeout: 1000 * 240
            };
```
I'm using a connection pool:

```javascript
var pool = mysql.createPool({
                    // If true, the pool will queue the connection request and call it when one becomes available. If false, the pool will immediately call back with an error.
                    waitForConnections: true,
                    // The milliseconds before a timeout occurs during the connection acquisition.
                    acquireTimeout: this._options.mysql.connectTimeout,
                    // The maximum number of connection requests the pool will queue before returning an error. If set to 0, there is no limit to the number of queued connection requests.
                    queueLimit: 0,
                    // The maximum number of connections to create at once.
                    connectionLimit: 5,
                    host: this._options.mysql.host,
                    user: this._options.mysql.user,
                    password: this._options.mysql.password,
                    database: this._options.mysql.database
                });
```

Stacktrace:

```
Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/node_modules/mysql/lib/Connection.js:412:13)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
    --------------------
    at Protocol._enqueue (/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/node_modules/mysql/lib/Pool.js:48:16)
```

**Comment by dougwilson** [comment]
If increasing the timeout does not make it work, then you have an issue occurring in your network stack somewhere, which is beyond the scope of this module, unfortunately.

**Comment by loretoparisi** [comment]
@dougwilson thank you Douglas, confirmed that, after several attempts, this was due to google `8.8.8.8` dns + VPN that was resolving AWS IP public instead of private!
