### ISSUE TITLE
Driver blocking node event loop

### ISSUE THREAD

**Issue by dgottlie** [mysqljs/mysql#233]
When using the driver to connect to mysql over our network, the node event loop blocks until all of the results are returned.  This does not occur when using the instance of mysql running on my local machine or with the JDBC mysql driver over the network so it seems like there’s some interaction between the driver and our network. 

I've posted the test code I’m using below, but am not really sure about the next steps to debug the problem so any suggestions would be appreciated.

``` javascript
mySql  = require('mysql')
conn  =  mySql.createConnection 
    host         : ''
    port         : '4930'
    user         : ''
    password     : ''
    database     : ''
    insecureAuth : true

conn.connect()
conn.query  "SELECT * from users", (err, rows) =>
    if err
        console.error err.message
    else
        delta = new Date() - last
        console.error('EVENT LOOP BLOCKED FOR', delta, "ms")
        console.log rows.length
    throw "done"
conn.end()

last = new Date()
setInterval( ->
    delta = new Date() - last
    if (delta > 2)
        console.error('EVENT LOOP BLOCKED FOR', delta, "ms")
    last = new Date()
, 1)
```

**Comment by avnersorek** [comment]
I'm having the same issue
Detailed here - http://stackoverflow.com/questions/30886173/nodejs-mysql-query-blocking-event-loop
I've got a much smaller table - ~115K rows
I'd appreciate any advice thanks

**Comment by dougwilson** [comment]
Hi @avnersorek ! It would be really neat if someone could put together a flamegraph of what Node.js is spending it's time doing during your query, however 115k rows is still _a lot of rows_, and I feel like a lot of those blocks may be in the v8 garbage collector or similar while we are trying to construct a 115k element array for you.

**Comment by avnersorek** [comment]
Hi @dougwilson ! Thanks for your help. Besides this being an application issue for me, I'd also love to take this opportunity and learn a little more about the inside workings of node, so I'd really appreciate any explanation regarding the matter.

I changed the query to ``SELECT SLEEP(5);`` and it really does not block at all, so I guess that implies the blocking happens when parsing the results.

I change my code to this, in order to keep the query running and generate the flame graph (also change to the streaming API) : 
```
function runQuery() {
  console.time('query');
  connection.query(query)
  .on('end', function() {
    console.timeEnd('query');
    runQuery();
  });
}

connection.connect(function(err) {
  runQuery();
});
```

:octocat: won't let me attach an SVG to this comment to I've uploaded the flamegraph here : https://drive.google.com/file/d/0B1p0cQY4eBDhczlETUhJMUZkU0U/view?usp=sharing

Thanks for the help !!!

**Comment by dougwilson** [comment]
Thank you so much, @avnersorek ! So according to the flamegraph, most of the time is taking up by v8 setting properties on object (i.e. within v8 itself from us trying to create all those row objects). The function in the list from us that is actually taking any significant time is the `typeCast` function, so we can look into if/how that can be optimized, but it won't really help too much, according to the graph.

**Comment by logidelic** [comment]
I appreciate that this is an old thread by now, but since it's still Open, I guess this is still the case? I've been trying to figure out why I'm seeing blocks in my own Node server, such as the below. Is it plausible that these are caused by what is being discussed here?

Thanks much.

```
ERROR: BURST:blocked - Blocked for 27.6ms
 operation started here:
    at Socket.connect (net.js:950:7)
    at Object.connect (net.js:178:17)
    at PoolConnection.connect (/home/user/myproj/node/node_modules/mysql/lib/Connection.js:79:13)
    at Pool.getConnection (/home/user/myproj/node/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/user/myproj/node/node_modules/mysql/lib/Pool.js:202:8)
    at MySQLStore.query (/home/user/myproj/node/node_modules/express-mysql-session/index.js:432:33)
    at MySQLStore.get (/home/user/myproj/node/node_modules/express-mysql-session/index.js:162:8)
    at session (/home/user/myproj/node/node_modules/express-session/index.js:474:11)
    at Layer.handle [as handle_request] (/home/user/myproj/node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/myproj/node/node_modules/express/lib/router/index.js:317:13)
    at /home/user/myproj/node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/user/myproj/node/node_modules/express/lib/router/index.js:335:12)
    at next (/home/user/myproj/node/node_modules/express/lib/router/index.js:275:10)
    ...
```

**Comment by felixge** [comment]
I'm no longer involved with this project, but decided to take a quick look since it seems interesting.

As far as I can tell, my theory from 2012 is probably correct and there seems to be a scheduling issue in the node core, as demonstrated by the code here:

https://gist.github.com/felixge/d16ee6b128af7256862bf83fe2f34d8d#file-blocked-by-loop-js
https://gist.github.com/felixge/d16ee6b128af7256862bf83fe2f34d8d#file-blocked-by-net-client-txt

Firing a 100 million loop iteration every 1s seems to block the event loop for ~60ms. That seems reasonable.

Firing the same loop in a busy socket's `'data'` callback however blocks the event loop for up to 1800ms. This seems unreasonable because the network callback gets scheduled 30x in a row while the timer has to wait.

So if your application requires fair scheduling between network and timer events, I'd suggest you raise an issue with the node.js core to get their feedback on this.

It might also be possible to implement some sort of cooperative scheduling in node-mysql by yielding back to the event loop after a certain amount of time. But if that's what it takes to get reasonable scheduling in node, I'd rather ditch it for Go 🤪.

**Comment by logidelic** [comment]
Fascinating, thank you @felixge . I agree that this is crazy, but I wonder what other Node DB implementations are doing and if they are subject to the same gotcha.

If I'm following you, wrapping the socket's `data` callback in a `setImmediate` would probably "fix" the problem. I'm going to give it a try and will report back. I admit that this would not be ideal (for performance reasons), but I think that there should at least be an optional way to work around this problem...

Thanks again.

**Comment by felixge** [comment]
@logidelic yeah, they should help. I.e you should be able to see better timer latencies in exchange of slightly lower overall  throughput.

**Comment by dougwilson** [comment]
Unless you're talking about a different issue in this thread from the OP, I think the provided flame graphs are pretty straight forward for where the bottleneck is, so I don't think that is going to help. The blocking is still going to happen, even if it's moved with a `setImmediate` to occur at a different time...

**Comment by felixge** [comment]
@dougwilson are you sure?

I just modified my example to use `socket.pause()` and `setImmediate` and was able to reduce the timer starvation from ~1800ms at a time to ~80ms:

https://gist.github.com/felixge/d16ee6b128af7256862bf83fe2f34d8d#file-blocked-by-net-js

vs

https://gist.github.com/felixge/d16ee6b128af7256862bf83fe2f34d8d#file-blocked-by-net-improved-js

The flamegraph obviously shows why the callback is eating a lot of CPU time, but it doesn't show scheduling issues. By using `setImmediate` we're able to coerce the scheduler from it's default behavior of executing queued I/O events up to the internal `callback limit` to instead schedule evenly between I/O and timer events.

See https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/

**Comment by dougwilson** [comment]
Nice! It would be very interesting to know if this impacts the wall clock of large query results, but fixing scheduling lock ups is more important than raw throughput for sure. Hopefully it doesn't cause the query parsing time as a total against the wall clock much impact.

**Comment by felixge** [comment]
> Nice! It would be very interesting to know if this impacts the wall clock of large query results, but fixing scheduling lock ups is more important than raw throughput for sure. Hopefully it doesn't cause the query parsing time as a total against the wall clock much impact.

Yeah, that could be a concern.

One could combat this by having each connection instance setup a `setInterval` of `1ms` which updates a `this._lastTimer` property. If `this._lastTimer` gets too far behind (e.g. 10ms), then the connection can call `socket.pause()` and `setImmediate()`.

That being said, one should certainly question the wisdom of implementing an I/O scheduler inside of a database client library. It'd be much better to seek solutions for this in the node core ...

**Comment by logidelic** [comment]
According to [Node peeps](https://github.com/nodejs/node/issues/31953#), we shouldn't be blocking things in that callback. The suggestion is that the parsing should be moved to a worker thread.

**Comment by dougwilson** [comment]
My understanding is that workers threads are not made for parsing, either. This is because they run in a separate v8 isolate, so all the parsing work done there would not be available back on the main thread without stringifying the data and parsing it back in the main thread to turn it back into object, which would block again. Please correct me if I am mistaken, though.

**Comment by felixge** [comment]
@logidelic I replied to the node thread. I think node has a scheduling problem and the suggested workaround seems unreasonable for many scenarios, including node-mysql. Let’s see the discussion continues

**Comment by logidelic** [comment]
Thanks for that @felixge . I have a feeling that they are going to stick to the, "this is by design and not our problem" line but we shall see.

I haven't looked at the internals of the Socket stuff in node, but I'm scared that the pause/resume stuff might be a hit on throughput. One alternative is to do something like:

```
var queue = [];

socket.on('data', data => {
    queue.push(data);
    if(queue.length == 1) setImmediate(processData);
})

function processData() {
    var data = queue.shift();
    if(queue.length) setImmediate(processData);
    // Parse/process data now...
}
```

This way we are processing each data event in sequential ticks (which is probably what most users would expect would happen)... Of course it may use a bit more memory for the queue.

**Comment by felixge** [comment]
@logidelic any sort of attempt to implement user-land scheduling will be a tradeoff between latency and throughput.

That being said, I suspect your proposal will have a higher overhead than mine (as every callback gets deferred, even if the event loop hasn't be blocked much), and also seems to allow unbound memory usage which might could cause significant issues for people dealing with very large query results.
