### ISSUE TITLE
MySQL Error: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by Nandhan-augment** [mysqljs/mysql#2352]
I'm getting this error and my server stopped working.
```
{ Error: connect ECONNREFUSED 127.0.0.1:3306
at Object._errnoException (util.js:992:11)
at _exceptionWithHostPort (util.js:1014:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:145:48)
at Protocol.handshake (node_modules/mysql/lib/protocol/Protocol.js:52:23)
at Connection.connect (/node_modules/mysql/lib/Connection.js:130:18)
at Object.<anonymous> (//config.js:15:12)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 3306,
fatal: true }
```

**Comment by dougwilson** [comment]
Hi @Nandhan-augment , the error you are getting there is from Node.js's network implementation. You can find more information about errors from Node.js at https://nodejs.org/dist/latest-v14.x/docs/api/errors.html#errors_common_system_errors

> ECONNREFUSED (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.
