### ISSUE TITLE
Error: Handshake inactivity timeout

### ISSUE THREAD

**Issue by lajpatshah** [mysqljs/mysql#2379]
Hello

I am not able to find the issue related to the error mentioned. It is occurring quite frequently and abruptly. 

- my app is running a mysql pool and i can see active connections in mysql.

- suddenly after few hours node stops getting response from mysql and below error is thrown. 

I am not able to understand why is this happening even though there are active connections. Because of this users are getting server response error for couple of minutes. 

I have used pool.getConnection() as per your doc. Why getconnection is getting timeout when there are connections shown in mysql. 

Is there a better way to manage such fatal errors where I can reconnect once it occurs?

Is there anyway I can trace the root cause of this error? My db config is working perfectly on my test server. But on production it is throwing errors. Please help.

**Error in mysql**  - Both errors are printed in the console separately.

- Bad Handshake 

-  Got an error reading communication packets

**Error in Node**

error : getDbConnection :     { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/var/app/current/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:198:13)
    at Handshake.EventEmitter.emit (domain.js:448:20)
    at Handshake._onTimeout (/var/app/current/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/var/app/current/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    --------------------
    at Protocol._enqueue (/var/app/current/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/var/app/current/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/var/app/current/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/var/app/current/node_modules/mysql/lib/Pool.js:48:16)
    at Promise._execute (/var/app/current/node_modules/bluebird/js/release/debuggability.js:411:9)
    at Promise._resolveFromExecutor (/var/app/current/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/var/app/current/node_modules/bluebird/js/release/promise.js:103:10)
    at Promise._execute (/var/app/current/node_modules/bluebird/js/release/debuggability.js:411:9)
    at Promise._resolveFromExecutor (/var/app/current/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/var/app/current/node_modules/bluebird/js/release/promise.js:103:10)
    at tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/current/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/var/app/current/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/var/app/current/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:102:5)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }

**Comment by leomongeg** [comment]
Hello @lajpatshah , 

I was wondering, how did you solve your issue?

I am experiencing the same problem, maybe there was an issue of configuration in the MySQL server..

Thank you in advance.
Regards!

**Comment by lajpatshah** [comment]
Hello @leomongeg 

Would be glad if my suggestion can help you.
The issue is in MySQL configuration. After setting below values the errors have stopped occurring. 
innodb_io_capacity | 400 
innodb_lru_scan_depth | 256
What I found was in MySQL 5.7 the default value for innodb_io_capacity was 100. While for a SSD the value should be more. So I randomly choose 400 to see what happens. Fortunately it worked.
Do read this article https://www.percona.com/blog/2019/12/18/give-love-to-your-ssds-reduce-innodb_io_capacity_max/
I have not done thorough testing with other values as the issue was occurring on my live website. Its a pending task at my end. Will share my analysis once done. But for now the above values are giving me decent results.

Thanks for asking.

Kind Regards
Lajpat
