### ISSUE TITLE
Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by lmaoguy123** [mysqljs/mysql#2448]
TypeError: Cannot read property 'query' of undefined
    at Client.<anonymous> (/Users/danielstrategytoweb/Documents/bot-discord/src/bot.js:14:24)
    at Client.emit (events.js:315:20)
    at Object.module.exports [as GUILD_CREATE] (/Users/danielstrategytoweb/Documents/bot-discord/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:33:14)
    at WebSocketManager.handlePacket (/Users/danielstrategytoweb/Documents/bot-discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/Users/danielstrategytoweb/Documents/bot-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/Users/danielstrategytoweb/Documents/bot-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/Users/danielstrategytoweb/Documents/bot-discord/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/Users/danielstrategytoweb/Documents/bot-discord/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:315:20

Im on macOS and my code is:

`client.on('guildCreate', async (guild) => {`
   `try{`
      `await connection.query(`
         ``INSERT INTO Guilds VALUES('${guild.id}', '${guild.ownerID}', '${guild.createdAt}', '${guild.name}')``
     ` );`
      `await connection.query(`
         ``INSERT INTO GuildConfigurable VALUES('.', '${guild.id}')``
      `);`
   `} catch(err) {`
     `console.log(err);`
   `}`
`});`

I've been looking for hours and i didn't found anything. I need help.
<img width="898" alt="Captura de pantalla 2020-12-31 a las 20 46 49" src="https://user-images.githubusercontent.com/66006649/103423857-74703900-4ba9-11eb-8e67-262c96458947.png">

**Comment by dougwilson** [comment]
Hi! That error means that the connection variable is not defined in your code. This would need to be fixed in your code and unfortunately isn't coming from this module.
