### ISSUE TITLE
Packets out of order. Got: 1 Expected: 3

### ISSUE THREAD

**Issue by farman05** [mysqljs/mysql#2451]
```
{ Error: Packets out of order. Got: 1 Expected: 3
    at Parser._tryReadPacketHeader (/project_folder/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/project_folder/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/project_folder/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/project_folder/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/project_folder/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }
```

```

const handleConnectDisconnect = ()=>{
    const functionName = "handleConnectDisconnect";
    log.info(functionName,"Handle connect disconnect get called","connecting to database");
    // creds.debug = true;
    const connection = mysql.createConnection(creds); // Recreate the connection, since
                                                    // the old one cannot be reused.
    connection.connect((err)=> {              // The server is either down
      if(err) {                                     // or restarting (takes a while sometimes).
        log.error(functionName,"error of connecting to db",err);
        setTimeout(handleConnectDisconnect, 2000); // We introduce a delay before attempting to reconnect,
      }                                     // to avoid a hot loop, and to allow our node script to
    });                                     // process asynchronous requests in the meantime.
                                            // If you're also serving http, display a 503 error.
    connection.on('error', (err)=> {
      if(err.code === 'PROTOCOL_CONNECTION_LOST') { // Connection to the MySQL server is usually
        log.error(functionName,"error of PROTOCOL_CONNECTION_LOST, reconnecting to db again",err);
        handleConnectDisconnect();                         // lost due to either server restart, or a
      } else {                                      // connnection idle timeout (the wait_timeout
            log.error(functionName,"error of dbConnection, reconnecting to db again",err);
            handleConnectDisconnect();                                   // server variable configures this)
      }
    });
    con = util.promisify(connection.query).bind(connection)

}
```

How can i handle the error more efficiently and moreover dont encounter that error

**Comment by noyearzero** [comment]
I too get Packets out of order randomly for the past few months.  I hadn't made any changes or upgrades to any code and it just started happening one day.  I can always fix it by restarting the SQL server (mariadb in my case) and restarting the node process.  It runs fine for a while but then craps out eventually.  It's always on the most basic query:
`SELECT 1 FROM emails WHERE send = '1' AND sent = '0' AND (not_before IS NULL OR not_before < '"+now+"') LIMIT 1`
Other node scripts that connect to the DB in the same way always run fine.  Other connections to the database from PHP are never affected.  

I too am doing util.promisify() on the query.  I've also tried upgrading node to the latest version with no change (now at 14.16.0 from either v9 or v10).  I tried using the  mariadb node package which is async by default.... the issue still happens there in the same way.  

The only thing I can think of is it's a bug with not properly releasing pooled connections, or some issues with queries happening at the same time.  Hard to say because it's super hard to debug since it can take several days or longer to reproduce.

**Comment by Zikoel** [comment]
If you manage all your query with a single `connection` can happen that sometimes there are errors due the nature of the network between node and the db! My suggestion is not to use a single connection but a connection pool that is more performant and reconnect automatically the error connections, after that you can retry the failed query! In my production application every few day a connection go in error but this should not be a problem for a robust application... many other things on the network can fails

**Comment by noyearzero** [comment]
For me, I am pooling connections.  And just reconnecting doesn't fix my issue.  I have to restart the DB service.  I think it maybe  related to a MariaDB 10.3 bug.

**Comment by Zikoel** [comment]
Maybe you are right, this kind of error seems related to MariaDB here [c# driver](https://github.com/mysql-net/MySqlConnector/issues/662) and here [maria db issue tracker](https://jira.mariadb.org/browse/MDEV-19893); the error that you report is not exactly on the packer 0 so I can't to be 100% sure but seems exists a relation.

**Comment by dougwilson** [comment]
Correct, if that were the issue I would expect to see "Got: 0" in the error from this module.

Unfortunately we can only speculate with the information provided. If you could provide a method for us to reproduce the issue, we can debug it, otherwise it is only possible to debug in your environment. If you cannot help us replicate, I would say the next best thing would be to provide us a packet capture of when the issue occurs.

**Comment by IlyasMirzaaliev** [comment]
try to give grand access to SQL server

**Comment by shellord** [comment]
I'm also have this issue. It just started happening recently.

**Comment by nvvetal** [comment]
If you making SQL requests after a long period of time - you can get a same issue.

Fix of that possible by tune this values in mysql service config:

interactive_timeout

wait_timeout

**Comment by dougwilson** [comment]
I know this has been opened for a while and "unresolved" -- but there is just not enough information on what the issue is. You're welcome to contribute a fix, or provide perhaps some packet captures during the time to see what is happening, or steps to reproduce it.

**Comment by sawrubgupta** [comment]
C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\protocol\Parser.js:470
    var err = new Error(
              ^
Error: Packets out of order. Got: 1 Expected: 0
    at Parser._tryReadPacketHeader (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\protocol\Parser.js:470:15)
    at Parser.write (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\protocol\Parser.js:33:29)
    at Protocol.write (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    --------------------
    at Protocol._enqueue (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\user\Desktop\vkardsBackendApp\node_modules\mysql\lib\Pool.js:48:16)
    at Object.<anonymous> (C:\Users\user\Desktop\vkardsBackendApp\src\db.ts:32:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)


same error
