### ISSUE TITLE
README section on fatal errors is inaccurate

### ISSUE THREAD

**Issue by bmaupin** [mysqljs/mysql#2519]
[The README gives this example on fatal errors](https://github.com/mysqljs/mysql#error-handling), which I was trying to use to test generating a fatal error for an issue I'm having:

```javascript
var connection = require('mysql').createConnection({
  port: 84943, // WRONG PORT
});

connection.connect(function(err) {
  console.log(err.code); // 'ECONNREFUSED'
  console.log(err.fatal); // true
});

connection.query('SELECT 1', function (error, results, fields) {
  console.log(error.code); // 'ECONNREFUSED'
  console.log(error.fatal); // true
});
```

However the code to log `err.code` is never reached:

```
$ node .
internal/validators.js:217
    throw new ERR_SOCKET_BAD_PORT(name, port, allowZero);
    ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 84943.
    at validatePort (internal/validators.js:217:11)
    at lookupAndConnect (net.js:1002:5)
    at Socket.connect (net.js:978:5)
    at Object.connect (net.js:189:17)
    at Connection.connect (node_modules/mysql/lib/Connection.js:76:13)
    at Object.<anonymous> (app.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'ERR_SOCKET_BAD_PORT'
}
```

Not only that, but the error that is thrown does not have `err.fatal` set. Using this code:

```javascript
var connection = require('mysql').createConnection({
  port: 84943, // WRONG PORT
});

try {
  connection.connect(function (err) {
    if (err) {
      console.error('error: ' + err.stack);
    }
  });
} catch (err) {
  console.log('err.code=', err.code);
  console.log('err.fatal=', err.fatal);
}
```

I get this output:

```
$ node .
err.code= ERR_SOCKET_BAD_PORT
err.fatal=
```

Maybe it would be better to use a different example? Thanks!

**Comment by dougwilson** [comment]
It looks like Node.js changed how it handles bad ports like that, which is why the example is not working with the current Node.js . It should still work, so it may just be a bug in the module now and not an issue with the docs.

**Comment by bmaupin** [comment]
Would you happen to have another suggestion as to how I can reproduce a fatal error?

For a little bit of background, I'm indirectly using this library via [loopback-connector-mysql](https://github.com/loopbackio/loopback-connector-mysql). Admittedly without a full understanding of either library, I *believe* what's happening is the pool connections are encountering a fatal error, and since that library doesn't seem to have any provisions for dealing with fatal errors, those connections do not get reused, and then of course the pool becomes unusable because it's full of dead connections:

```
Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at PoolConnection.query (/usr/src/app/node_modules/mysql/lib/Connection.js:198:25)
    at runQuery (/usr/src/app/node_modules/loopback-connector-mysql/lib/mysql.js:197:16)
```

This becomes a problem because then the application completely hangs. I would even prefer that the application crashed, because at least that way Kubernetes could restart the pod.

More specifically, this seems to be the error that's causing the above error, so I am trying to figure out how to reproduce it; if I can manage that, I should be able to file a bug with loopback-connector-mysql:

```
Error: read ETIMEDOUT
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)
    --------------------
    at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/usr/src/app/node_modules/mysql/lib/Connection.js:198:25)
    at runQuery (/usr/src/app/node_modules/loopback-connector-mysql/lib/mysql.js:197:16)
```

I've been going through the suggestions here on how to reproduce a timeout error: https://stackoverflow.com/q/100841/399105

e.g. 

```
nc -l 3306
```

(https://stackoverflow.com/a/37465639/399105)

But rather than hit that error, I get this one:

```
Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/bmaupin/workspace/work/netcmdb-api/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:400:28)
    at Handshake._onTimeout (/home/bmaupin/workspace/work/netcmdb-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/home/bmaupin/workspace/work/netcmdb-api/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
    --------------------
    at Protocol._enqueue (/home/bmaupin/workspace/work/netcmdb-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/bmaupin/workspace/work/netcmdb-api/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/bmaupin/workspace/work/netcmdb-api/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/bmaupin/workspace/work/netcmdb-api/node_modules/mysql/lib/Pool.js:48:16)
```

I'm not sure what the difference is; maybe `Handshake inactivity timeout` isn't a fatal error, so the pool is able to terminate the connection and create a new one? At any rate, it doesn't trigger the `Error: Cannot enqueue Query after fatal error.` that I'm trying to reproduce in order to file the bug.

Thanks!

**Comment by bmaupin** [comment]
Hmm, I think my hunch was wrong. I called some long-running queries and killed the database while they were running. Using this I was able to determine that the connection received fatal errors:

```javascript
connection.on("error", function (err) {
  console.log("DEBUG: err.code=", err.code);
  console.log("DEBUG: err.fatal=", err.fatal);
});
```

```
Object.keys(txError)= [ 'fatal', 'code' ]
txError.fatal= true
2021-09-17T14:38:47.223Z [netcmdb-api] error undefined - Error: Connection lost: The server closed the connection.
    at Protocol.end (node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    --------------------
    at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:144:48)
```

Once I restarted the database, everything worked fine again.

So while I understood this to mean that a connection couldn't be added to the queue after a fatal error without some extra work, I must've misunderstood: `Cannot enqueue Query after fatal error.`

So I still don't understand the original issue I ran into, more specifically why the application needed to be restarted to connect to the database. There must be some kind of special scenario where a database connection fails in a way that it can't recover from. So maybe this is an issue with this library after all? I guess I'll open a separate bug for it.

**Comment by dougwilson** [comment]
I updated the README to use a commonly blocked port instead of an invalid port, which addresses your main issue. I will also follow up with a fix to forward thrown errors from Node.js connect to the callback as well.
