### ISSUE TITLE
Load data infile fails with EPIPE for large files

### ISSUE THREAD

**Issue by coryvirok** [mysqljs/mysql#359]
Looks like this fails for large files due to an EPIPE exception. Ideally, packets would implement a stream interface so we can pump the file data to the connection without having to read in the whole file first.

``` javascript
var fs = require('fs');
var mysql = require('mysql');

var connection = mysql.createConnection({host: 'localhost', user: 'admin', debug: true});

var table = 'load_data_test';
connection.query('DROP DATABASE tmp');
connection.query('CREATE DATABASE tmp');
connection.query('USE tmp');
connection.query([
    'CREATE TEMPORARY TABLE `' + table + '` (',
        '`id` int(11) unsigned NOT NULL AUTO_INCREMENT,',
        '`title` varchar(255),',
        'PRIMARY KEY (`id`)',
    ') ENGINE=InnoDB DEFAULT CHARSET=utf8'].join('\n'));

var path = '/tmp/tmp.sql';

var stream = fs.createWriteStream(path, {flags: 'w'});

stream.on('close', function() {
  var sql =
    'LOAD DATA LOCAL INFILE ? INTO TABLE ' + table + ' ' +
      'FIELDS TERMINATED BY ? (id, title)';

      var ok;
      connection.query(sql, [path, ','], function(err, _ok) {
        if (err) {
          console.error(err);
          throw err;
        }
      });
});

for (var i = 0; i < 100000; ++i) {
  stream.write(i + ',' + i + ': The quick brown fox jumps over some stuff\n');
}
stream.end();
```

produces:

```
<-- HandshakeInitializationPacket
{ protocolVersion: 10,
  serverVersion: '5.5.15',
  threadId: 6955,
  scrambleBuff1: <Buffer 47 56 59 3c 60 4e 48 5b>,
  filler1: <Buffer 00>,
  serverCapabilities1: 63487,
  serverLanguage: 8,
  serverStatus: 2,
  serverCapabilities2: 32783,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 00 00 00 00>,
  scrambleBuff2: <Buffer 72 4d 67 41 4e 42 40 5c 2e 6c 5a 5e>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password' }

--> ClientAuthenticationPacket
{ clientFlags: 193487,
  maxPacketSize: 0,
  charsetNumber: 33,
  filler: undefined,
  user: 'admin',
  scrambleBuff: <Buffer >,
  database: undefined }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  changedRows: 0 }

--> ComQueryPacket
{ command: 3, sql: 'DROP DATABASE tmp' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 258,
  warningCount: 0,
  message: '',
  changedRows: 0 }

--> ComQueryPacket
{ command: 3, sql: 'CREATE DATABASE tmp' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  changedRows: 0 }

--> ComQueryPacket
{ command: 3, sql: 'USE tmp' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  changedRows: 0 }

--> ComQueryPacket
{ command: 3,
  sql: 'CREATE TEMPORARY TABLE `load_data_test` (\n`id` int(11) unsigned NOT NULL AUTO_INCREMENT,\n`title` varchar(255),\nPRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  changedRows: 0 }

--> ComQueryPacket
{ command: 3,
  sql: 'LOAD DATA LOCAL INFILE \'/tmp/tmp.sql\' INTO TABLE load_data_test FIELDS TERMINATED BY \',\' (id, title)' }

<-- ResultSetHeaderPacket
{ fieldCount: null, extra: '/tmp/tmp.sql' }

--> LocalDataFilePacket
{ data: '0,0: The quick brown  ...

<snip>


--> EmptyPacket
{}

{ [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write', fatal: true }

/tmp.js:30
          throw err;
                ^
Error: write EPIPE
    at errnoException (net.js:769:11)
    at Object.afterWrite (net.js:593:19)
    --------------------
    at Query.Sequence (node_modules/mysql/lib/protocol/sequences/Sequence.js:15:21)
    at new Query (node_modules/mysql/lib/protocol/sequences/Query.js:11:12)
    at Protocol.query (node_ratchet/node_modules/mysql/lib/protocol/Protocol.js:41:24)
    at Connection.query (node_ratchet/node_modules/mysql/lib/Connection.js:90:25)
    at null.<anonymous> (tmp.js:27:18)
    at EventEmitter.emit (events.js:93:17)
    at WriteStream.flush (fs.js:1517:12)
    at Object.oncomplete (fs.js:297:15)
```

**Comment by danger89** [comment]
I have similar problems...
https://github.com/mysqljs/mysql/issues/2021

**Comment by silentrob** [comment]
Wow, this was a blast from the past. Thanks :)
