### ISSUE TITLE
TypeError: Object 10 has no method 'apply'

### ISSUE THREAD

**Issue by dhruvbird** [mysqljs/mysql#371]
Am I doing something wrong? I get the following error (I've requested for 10 rows using LIMIT 10).
Using: "version": "2.0.0-alpha5",

```
TypeError: Object 10 has no method 'apply'
    at Query.end (/home/dhruvbird/projects/wikipins.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:66:24)
    at Query.ErrorPacket (/home/dhruvbird/projects/wikipins.org/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/home/dhruvbird/projects/wikipins.org/node_modules/mysql/lib/protocol/Protocol.js:165:23)
    at Parser._onPacket (native)
    at Parser.write (/home/dhruvbird/projects/wikipins.org/node_modules/mysql/lib/protocol/Parser.js:60:12)
    at Protocol.write (/home/dhruvbird/projects/wikipins.org/node_modules/mysql/lib/protocol/Protocol.js:32:16)
    at Socket.ondata (stream.js:38:26)
    at Socket.emit (events.js:67:17)
    at TCP.onread (net.js:367:14)
```

**Comment by toymachiner62** [comment]
I did the same thing. Glad this thread existed.
