### ISSUE TITLE
Server disconnect, not reconnecting.

### ISSUE THREAD

**Issue by jareddlc** [mysqljs/mysql#375]
Hello my node.js server is disconnecting and it runs the routine to reconnect however it doesn't quite reconnect.  I am using it in conjuction with express.js. Here is my server code:

```
//------------------------- Setup
//---MySQL
var mysql = require('mysql');
var DATABASE = 'website';
var sTable = 'test';
var sIndexColumn = '*';
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'user',
  password : 'pass', 
  database : 'db',
});

function handleDisconnect(connection){
  connection.on('error', function(err){
    if(!err.fatal)
    {
      return;
    }
    if(err.code !== 'PROTOCOL_CONNECTION_LOST')
    {
      throw err;
    }
    console.log('\nRe-connecting lost connection: ' +err.stack);

    connection = mysql.createConnection(connection.config);
    handleDisconnect(connection);
    connection.connect();
  });
}

handleDisconnect(connection);
//connection.connect();

startup();
console.log('Server initilizing...');

//---ExpressJS
var express = require('express');
var app = express();

//---Middleware: Allows cross-domain requests (CORS)
var allowCrossDomain = function(req, res, next){
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
  res.header('Access-Control-Allow-Headers', 'Content-Type');
  next();
}

//---App config
app.configure(function() {
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.use(express.bodyParser());
  app.use(express.cookieParser());
  app.use(express.session({ secret: 'secret'}));
  app.use(express.methodOverride());
  app.use(allowCrossDomain);
  app.use(app.router);
  app.use(express.static(__dirname + '/public'));
});


//------------------------- Endpoints
/*
app.all('/', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With");
  next();
 });*/

app.get('/', function(req, res, next){
  console.log('GET request to /');
});

app.get('/server', function(req, res, next){
  console.log('GET request to /server');
  request = req.query;
  server(res);
})

app.listen(8888);
console.log('Express server started on port 8888');
```

when i check my server after a few hours i get this message

```
Re-connecting lost connection: Error: Connection lost: The server closed the connection.
    at Protocol.end (/var/www/db/node_modules/mysql/lib/protocol/Protocol.js:59:13)
    at Socket.onend (stream.js:66:10)
    at Socket.EventEmitter.emit (events.js:126:20)
    at TCP.onread (net.js:417:51)
```

any help greatly appreciated :D

**Comment by vishalims095** [comment]
var mysql = require('mysql')
var connection = mysql.createPool({
  host: "",
  user: "root",
  password: "",
  database: "",
  port : ""
})
connection.getConnection((err, connection) => {
    if (err) {
        if (err.code === 'PROTOCOL_CONNECTION_LOST') {
            console.error('Database connection was closed.')
        }
        if (err.code === 'ER_CON_COUNT_ERROR') {
            console.error('Database has too many connections.')
        }
        if (err.code === 'ECONNREFUSED') {
            console.error('Database connection was refused.')
        }
    }
    if (connection) connection.release()
    return
})
module.exports = connection
