### ISSUE TITLE
Deadlocked crash

### ISSUE THREAD

**Issue by wmertens** [mysqljs/mysql#572]
Doing lots of insertions. No clue why this happened.

I'm using the connection pool if that makes a difference. For each insert I get a connection from the pool, do the insert and end the connection.

```
Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
  at Query.Sequence._packetToError (/home/techzone/tz-stats/node_modules/mysql/lib/protocol/sequences/Sequence.js:32:14)
  at Query.ErrorPacket (/home/techzone/tz-stats/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
  at Protocol._parsePacket (/home/techzone/tz-stats/node_modules/mysql/lib/protocol/Protocol.js:172:24)
  at Parser.write (/home/techzone/tz-stats/node_modules/mysql/lib/protocol/Parser.js:62:12)
  at Protocol.write (/home/techzone/tz-stats/node_modules/mysql/lib/protocol/Protocol.js:37:16)
  at Socket.ondata (stream.js:51:26)
  at Socket.EventEmitter.emit (events.js:117:20)
  at Socket.<anonymous> (_stream_readable.js:736:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
    --------------------
  at Query.Sequence (/home/techzone/tz-stats/node_modules/mysql/lib/protocol/sequences/Sequence.js:15:20)
  at new Query (/home/techzone/tz-stats/node_modules/mysql/lib/protocol/sequences/Query.js:12:12)
  at Function.Connection.createQuery (/home/techzone/tz-stats/node_modules/mysql/lib/Connection.js:48:10)
  at Connection.query (/home/techzone/tz-stats/node_modules/mysql/lib/Connection.js:100:26)
From previous event:
  at /home/techzone/tz-stats/db.coffee:30:14, <js>:47:18
```

**Comment by cbshakumar** [comment]
I ran into a similar problem and found it to be due to indexes/key constraints.
It is possible to get a partial lock based on having composite indexes or composite keys.

http://stackoverflow.com/questions/15412838/deadlock-issue-when-transaction-tries-to-accuire-a-lock-its-already-holding

I solved this by changing the table schema to a primary key with a single column.

**Comment by umutm** [comment]
I experienced the same error and Google got me here :).

MySQL has a suggestion for handling them (https://dev.mysql.com/doc/refman/5.6/en/error-messages-server.html#error_er_lock_deadlock).

**Comment by tapasudenia** [comment]
I have the same issue, I want to delete the rows by some ID and then add in a transaction. How do I restart the transaction or change the concurrent connections?

module.exports.updateTableAByProjectID = async (
  projectID,
  insertValuesFormat,
  insertValues
) => {
  log.debug('Entering updateTableAByProjectID ');
  await util.executeTransaction(async (connection) => {
    await util.executeChangeQuery(
        'SELECT * FROM TableA where projectID = ? FOR UPDATE',
        [projectID],
        connection
    );

    // Delete Users
    await util.executeChangeQuery(
        'DELETE FROM TableA WHERE projectID = ?',
        [projectID],
        connection
    );

    // This is bulk insert, insertValuesFormat - (?,?,?), (?,?,?) format
    const insertQuery =
      'INSERT IGNORE INTO TableA (colA, projectID, ColC) VALUES ' +
      insertValuesFormat;
    await util.executeChangeQuery(insertQuery, insertValues, connection);
  });
};

module.exports.executeChangeQuery = async (query, params, connection) => {
  log.debug('Entering executeChangeQuery');
  let rows;
  try {
    if (connection) {
      log.debug('executeChangeQuery Query ' + query);
      rows = await connection.execute(query, params);
    } else {
      rows = await mysqlPool.execute(query, params);
    }
    // Checking for rows[0] which is an extra layer on ROLLBACK.
    if (rows && Array.isArray(rows[0])) {
      rows = rows[0];
    }
    return rows;
  } catch (err) {
    log.error(err);
    throw err;
  }
};

module.exports.executeTransaction = async (func) => {
  log.debug('Entering executeTransaction');
  const connection = await mysqlPool.getConnection();
  try {
    await connection.beginTransaction();
    const result = await func(connection);
    await connection.commit();
    connection.release();
    return result;
  } catch (err) {
    log.error(err);
    await connection.rollback();
    connection.release();
    throw err;
  }
};
