### ISSUE TITLE
TypeError: Object #<Connection> has no method 'release'

### ISSUE THREAD

**Issue by JohnLouderback** [mysqljs/mysql#596]
```
TypeError: Object #<Connection> has no method 'release'
    at Query._callback (/routes/autoSignIn.js:23:20)
    at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:66:24)
    at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.OkPacket (node_modules/mysql/lib/protocol/sequences/Query.js:77:10)
    at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:172:24)
    at Parser.write (node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.ondata (stream.js:51:26)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:710:14)
19 Sep 15:26:13 - [nodemon] app crashed - waiting for file changes before starting...
```

In my code I call the release method on my connection and the program crashes telling me the above. Why? I create the pool, get connection on request, and then pass the connection to my request handler. Everything works except it tells me the connection has no method 'release'. What gives?
Thanks,
-John

**Comment by pcemma** [comment]
It works! Thank you.

**Comment by dresende** [comment]
Instead of that command you should just install the latest version (not alpha anymore). If it doesn't install that perhaps means you have a specific version in `package.json`. You should be installing `2.7.0`.
