### ISSUE TITLE
Pool getConnection frequently throws an error

### ISSUE THREAD

**Issue by jqdometita** [mysqljs/mysql#824]
https://github.com/felixge/node-mysql/blob/master/lib/Pool.js#L72

Getting an error when getting a connection from an existing pool.
Is this a normal case, if yes, what can you suggest to avoid it?

**Comment by vurumadla** [comment]
i am getting a frequent error shown below and it is leading to crash of application.... can anyone help on this. 

D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'query' of undefined
    at D:\Users\vurumadl\Desktop\bg_latest_5pm\appOriginal.js:671:13
    at Handshake.onConnect [as _callback] (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\Pool.js:58:9)
    at Handshake.Sequence.end (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Handshake.ErrorPacket (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\sequences\Handshake.js:105:8)
    at Protocol._parsePacket (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\Connection.js:104:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
