### ISSUE TITLE
Cannot enqueue Query after fatal error

### ISSUE THREAD

**Issue by viki53** [mysqljs/mysql#832]
Hi, I keep getting this error when I try to insert a new row in a table. Everything worked fine before and I didn't modify the query recently.

More details about the error stack: 

```
Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (mysql/lib/protocol/Protocol.js:155:16)
    at Protocol._enqueue (mysql/lib/protocol/Protocol.js:104:13)
    at PoolConnection.Connection.query (mysql/lib/Connection.js:166:25)
```

Thing is I don't see anything about a fatal error anywhere in the logs.

Any idea what may be the problem?

**Comment by tak215** [comment]
Hi, I think this issue is similar to mine:
1. Connect to MySQL
2. End MySQL service (should not quit node script)
3. Start MySQL service, Node reconnects to MySQL
4. Query the DB -> FAIL (Cannot enqueue Query after fatal error.)

I solved this issue by recreating a new connection with the use of promises (q).

mysql-con.js
```
'use strict';
var config          = require('./../config.js');
var colors          = require('colors');
var mysql           = require('mysql');
var q               = require('q');
var MySQLConnection = {};

MySQLConnection.connect = function(){
    var d = q.defer();
    MySQLConnection.connection = mysql.createConnection({
        host                : 'localhost',
        user                : 'root',
        password            : 'password',
        database            : 'database'
    });

    MySQLConnection.connection.connect(function (err) {
        if(err) {
            console.log('Not connected '.red, err.toString().red, ' RETRYING...'.blue);
            return d.reject();
        } else {
            console.log('Connected to Mysql. Exporting..'.blue);
            return d.resolve(MySQLConnection.connection);
        }
    });
    return d.promise;
};

module.exports = MySQLConnection;
```

mysqlAPI.js
```
var mysqlCon        = require('./mysql-con.js');
mysqlCon.connect().then(function(con){
   console.log('connected!');
    mysql = con;
    mysql.on('error', function (err, result) {
        console.log('error occurred. Reconneting...'.purple);
        mysqlAPI.reconnect();
    });
    mysql.query('SELECT 1 + 1 AS solution', function (err, results) {
            if(err) console.log('err',err);
            console.log('Works bro ',results);
    });
});

mysqlAPI.reconnect = function(){
    mysqlCon.connect().then(function(con){
      console.log("connected. getting new reference");
        mysql = con;
        mysql.on('error', function (err, result) {
            mysqlAPI.reconnect();
        });
    }, function (error) {
      console.log("try again");
        setTimeout(mysqlAPI.reconnect, 2000);
    });
};

```


I hope this helps.
