### ISSUE TITLE
Error: Packets out of order. Got: 0 Expected: 2

### ISSUE THREAD

**Issue by kornelski** [mysqljs/mysql#844]
Once in a while I'm seeing this error thrown:

```
at Parser._trackAndVerifyPacketNumber (node_modules/mysql/lib/protocol/Parser.js:322:15)
at Parser.write (node_modules/mysql/lib/protocol/Parser.js:40:12)
at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:37:16)
at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:75:28)
at Socket.EventEmitter.emit (events.js:107:17)
at readableAddChunk (_stream_readable.js:159:16)
at Socket.Readable.push (_stream_readable.js:126:10)
at TCP.onread (net.js:514:20)
```

I'm running MySQL 5.5.18 and node v0.11.12. I'm using connection pools.

Oddly, the error is thrown long after my app finishes querying data and responds to the request.
- Is that a problem I should be worried about? Incompatibility or maybe just a network error?
- Is it possible to catch that error and handle it gracefully? (other than via a `domain`)

**Comment by TarSzator** [comment]
I have still this issue. I try to use a prepared statement to insert data in to a simple table.
The problem seems to have something todo with the string length of one of the fields.
So the everything works fine, but when I try to store a string with the length of 89,764,572 into the Longtext colum I get the error:

> Packets out of order. Got: 2 Expected: 7
