### ISSUE TITLE
PoolCluster: Cannot enqueue Quit after fatal error

### ISSUE THREAD

**Issue by benthor** [mysqljs/mysql#879]
I have a PoolCluster of three nodes, all selected into one wildcard Round Robin pool. 

canRetry is enabled and removeNodeErrorCount is set to 1

Every 30 seconds, I get a connection from the pool, check for any error and in case everything is fine, I run a 'SELECT 1' on the pool.

This works fine when all 3 nodes are reachable. However, when I take one of them offline (i.e., blackhole the route to that node) and the round robin reaches that node, I _often_ get:

```
Error: Cannot enqueue Quit after fatal error.
at Protocol._validateEnqueue (node_modules/mysql/lib/protocol/Protocol.js:192:16)
at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:129:13)
at Protocol.quit (node_modules/mysql/lib/protocol/Protocol.js:87:36)
at PoolConnection.end [as _realEnd] (node_modules/mysql/lib/Connection.js:214:18)
at Pool.end (node_modules/mysql/lib/Pool.js:158:16)
at PoolCluster._increaseErrorCount (node_modules/mysql/lib/PoolCluster.js:135:17)
at node_modules/mysql/lib/PoolCluster.js:153:12
at Pool.<anonymous> (node_modules/mysql/lib/Pool.js:47:16)
at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
at node_modules/mysql/lib/protocol/Protocol.js:367:16
```

My debugging shows that _when_ this happens, it happens during the getConnection call. Code preceding that is executed but the callback is never called, the function body simply isn't reached before I get the above stacktrace.

_Sometimes_ everything goes fine and the remove event is triggered without issue. Interesting case of a heisenbug.

Note: I am running node-mysql version 2.4.1 and node version 0.10.26

**Comment by ratneshdeepak** [comment]
Getting Quit inactivity timeout  again with 2.8.0

Error: Quit inactivity timeout 
 at Quit.sequence.on.on.on.on.on.self._connection._startTLS.err.code (/var/task/node_modules/mysql/lib/protocol/Protocol.js:154:17) 
 at Quit.emit (events.js:92:17) 
 at Quit._onTimeout (/var/task/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8) 
 at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by dougwilson** [comment]
Hi @ratneshdeepak , this issue is _only_ regarding the "PoolCluster: Cannot enqueue Quit after fatal error" error, which is different from what you posted.

The error "Quit inactivity timeout" occurs only when your have a misconfigured firewall somewhere on your network dropping FIN-related packets, because we waited 30 seconds for a FIN to close down the TCP connection but ever got it and gave up.

If you need help in addition to this explanation, please feel free to open a new issue :)
