### ISSUE TITLE
Pool Error

### ISSUE THREAD

**Issue by nyrsimon** [mysqljs/mysql#896]
Hi

Am experiencing a very strange issue with connection pools. It seems everything is working fine _most_ of the time. However if I wait several minutes and then access the webpage (which makes an ajax call which fires the query) then I get a weird handshake error:

```
query error:Error: Handshake inactivity timeout
Application has thrown an uncaught exception and is terminated:
Error: Handshake inactivity timeout
    at Handshake.sequence.on.on.on.on.on.self._connection._startTLS.err.code (D:\home\site\wwwroot\node_m
odules\mysql\lib\protocol\Protocol.js:153:17)
    at Handshake.emit (events.js:92:17)
    at Handshake._onTimeout (D:\home\site\wwwroot\node_modules\mysql\lib\protocol\sequences\Sequence.js:1
16:8)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
    --------------------
    at Protocol._enqueue (D:\home\site\wwwroot\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at Protocol.handshake (D:\home\site\wwwroot\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (D:\home\site\wwwroot\node_modules\mysql\lib\Connection.js:108:18)
    at Pool.getConnection (D:\home\site\wwwroot\node_modules\mysql\lib\Pool.js:42:23)
    at Pool.releaseConnection (D:\home\site\wwwroot\node_modules\mysql\lib\Pool.js:123:10)
    at Pool._removeConnection (D:\home\site\wwwroot\node_modules\mysql\lib\Pool.js:216:8)
    at Ping._callback (D:\home\site\wwwroot\node_modules\mysql\lib\Pool.js:87:10)
    at Ping.Sequence.end (D:\home\site\wwwroot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:2
4)
    at D:\home\site\wwwroot\node_modules\mysql\lib\protocol\Protocol.js:367:16
    at Array.forEach (native)
```

It looks like something is timing out. Is it possible I am not releasing something (have checked all my code and can't see that).

I can visit the page hundreds of times and it will work - it seems to only cause this problem after several minutes of inactivity.  

Any help is VERY much appreciated!

Thanks
Simon

**Comment by neilunadkat** [comment]
I faced the same issue. The node service and the mysql were running on the same instance on Azure and I kept getting this error every time. 
When I changed the db host to 'localhost' it started working. 
This is so weird.
